
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public interface movelladot_pc_sdkConstants {
  public final static int THREAD_PRIORITY_IDLE = movelladot_pc_sdkJNI.THREAD_PRIORITY_IDLE_get();
  public final static int THREAD_PRIORITY_LOWEST = movelladot_pc_sdkJNI.THREAD_PRIORITY_LOWEST_get();
  public final static int THREAD_PRIORITY_BELOW_NORMAL = movelladot_pc_sdkJNI.THREAD_PRIORITY_BELOW_NORMAL_get();
  public final static int THREAD_PRIORITY_NORMAL = movelladot_pc_sdkJNI.THREAD_PRIORITY_NORMAL_get();
  public final static int THREAD_PRIORITY_ABOVE_NORMAL = movelladot_pc_sdkJNI.THREAD_PRIORITY_ABOVE_NORMAL_get();
  public final static int THREAD_PRIORITY_HIGHEST = movelladot_pc_sdkJNI.THREAD_PRIORITY_HIGHEST_get();
  public final static int THREAD_PRIORITY_TIME_CRITICAL = movelladot_pc_sdkJNI.THREAD_PRIORITY_TIME_CRITICAL_get();
  public final static String __LOC__ = movelladot_pc_sdkJNI.__LOC___get();
  public final static int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = movelladot_pc_sdkJNI._CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_get();
  public final static String XSENS_PFSHARED = movelladot_pc_sdkJNI.XSENS_PFSHARED_get();
  public final static String XSENS_PFPRE = movelladot_pc_sdkJNI.XSENS_PFPRE_get();
  public final static String XSENS_PFBITS = movelladot_pc_sdkJNI.XSENS_PFBITS_get();
  public final static int QT_NO_DEBUG = movelladot_pc_sdkJNI.QT_NO_DEBUG_get();
  public final static String XSENS_PFCONF = movelladot_pc_sdkJNI.XSENS_PFCONF_get();
  public final static String XSENS_PFFULL = movelladot_pc_sdkJNI.XSENS_PFFULL_get();
  public final static int XSREAL_ALLOWS_MEMCPY = movelladot_pc_sdkJNI.XSREAL_ALLOWS_MEMCPY_get();
  public final static int XS_IND_PREAMBLE = movelladot_pc_sdkJNI.XS_IND_PREAMBLE_get();
  public final static int XS_IND_BID = movelladot_pc_sdkJNI.XS_IND_BID_get();
  public final static int XS_IND_MID = movelladot_pc_sdkJNI.XS_IND_MID_get();
  public final static int XS_IND_LEN = movelladot_pc_sdkJNI.XS_IND_LEN_get();
  public final static int XS_IND_DATA0 = movelladot_pc_sdkJNI.XS_IND_DATA0_get();
  public final static int XS_IND_LENEXTH = movelladot_pc_sdkJNI.XS_IND_LENEXTH_get();
  public final static int XS_IND_LENEXTL = movelladot_pc_sdkJNI.XS_IND_LENEXTL_get();
  public final static int XS_IND_DATAEXT0 = movelladot_pc_sdkJNI.XS_IND_DATAEXT0_get();
  public final static int XS_SELFTEST_OK = movelladot_pc_sdkJNI.XS_SELFTEST_OK_get();
  public final static int XS_LEN_TRANSPORTMODE = movelladot_pc_sdkJNI.XS_LEN_TRANSPORTMODE_get();
  public final static int XS_LEN_DEVICEID = movelladot_pc_sdkJNI.XS_LEN_DEVICEID_get();
  public final static int XS_LEN_INITBUSRESULTS = movelladot_pc_sdkJNI.XS_LEN_INITBUSRESULTS_get();
  public final static int XS_LEN_PERIOD = movelladot_pc_sdkJNI.XS_LEN_PERIOD_get();
  public final static int XS_LEN_BUSPWR = movelladot_pc_sdkJNI.XS_LEN_BUSPWR_get();
  public final static int XS_LEN_DATALENGTH = movelladot_pc_sdkJNI.XS_LEN_DATALENGTH_get();
  public final static int XS_LEN_CONFIGURATION = movelladot_pc_sdkJNI.XS_LEN_CONFIGURATION_get();
  public final static int XS_LEN_FIRMWAREREV = movelladot_pc_sdkJNI.XS_LEN_FIRMWAREREV_get();
  public final static int XS_LEN_BTDISABLE = movelladot_pc_sdkJNI.XS_LEN_BTDISABLE_get();
  public final static int XS_LEN_OPMODE = movelladot_pc_sdkJNI.XS_LEN_OPMODE_get();
  public final static int XS_LEN_BAUDRATE = movelladot_pc_sdkJNI.XS_LEN_BAUDRATE_get();
  public final static int XS_LEN_SYNCMODE = movelladot_pc_sdkJNI.XS_LEN_SYNCMODE_get();
  public final static int XS_LEN_PRODUCTCODE = movelladot_pc_sdkJNI.XS_LEN_PRODUCTCODE_get();
  public final static int XS_LEN_PROCESSINGFLAGS = movelladot_pc_sdkJNI.XS_LEN_PROCESSINGFLAGS_get();
  public final static int XS_LEN_XMPWROFF = movelladot_pc_sdkJNI.XS_LEN_XMPWROFF_get();
  public final static int XS_LEN_OUTPUTMODE = movelladot_pc_sdkJNI.XS_LEN_OUTPUTMODE_get();
  public final static int XS_LEN_OUTPUTSETTINGS = movelladot_pc_sdkJNI.XS_LEN_OUTPUTSETTINGS_get();
  public final static int XS_LEN_OUTPUTSKIPFACTOR = movelladot_pc_sdkJNI.XS_LEN_OUTPUTSKIPFACTOR_get();
  public final static int XS_LEN_SYNCINMODE = movelladot_pc_sdkJNI.XS_LEN_SYNCINMODE_get();
  public final static int XS_LEN_SYNCINSKIPFACTOR = movelladot_pc_sdkJNI.XS_LEN_SYNCINSKIPFACTOR_get();
  public final static int XS_LEN_SYNCINOFFSET = movelladot_pc_sdkJNI.XS_LEN_SYNCINOFFSET_get();
  public final static int XS_LEN_SYNCOUTMODE = movelladot_pc_sdkJNI.XS_LEN_SYNCOUTMODE_get();
  public final static int XS_LEN_SYNCOUTSKIPFACTOR = movelladot_pc_sdkJNI.XS_LEN_SYNCOUTSKIPFACTOR_get();
  public final static int XS_LEN_SYNCOUTOFFSET = movelladot_pc_sdkJNI.XS_LEN_SYNCOUTOFFSET_get();
  public final static int XS_LEN_SYNCOUTPULSEWIDTH = movelladot_pc_sdkJNI.XS_LEN_SYNCOUTPULSEWIDTH_get();
  public final static int XS_LEN_ERRORMODE = movelladot_pc_sdkJNI.XS_LEN_ERRORMODE_get();
  public final static int XS_LEN_TRANSMITDELAY = movelladot_pc_sdkJNI.XS_LEN_TRANSMITDELAY_get();
  public final static int XS_LEN_OBJECTALIGNMENT = movelladot_pc_sdkJNI.XS_LEN_OBJECTALIGNMENT_get();
  public final static int XS_LEN_ALIGNMENTROTATION = movelladot_pc_sdkJNI.XS_LEN_ALIGNMENTROTATION_get();
  public final static int XS_LEN_XMERRORMODE = movelladot_pc_sdkJNI.XS_LEN_XMERRORMODE_get();
  public final static int XS_LEN_BUFFERSIZE = movelladot_pc_sdkJNI.XS_LEN_BUFFERSIZE_get();
  public final static int XS_LEN_HEADING = movelladot_pc_sdkJNI.XS_LEN_HEADING_get();
  public final static int XS_LEN_MAGNETICFIELD = movelladot_pc_sdkJNI.XS_LEN_MAGNETICFIELD_get();
  public final static int XS_LEN_LOCATIONID = movelladot_pc_sdkJNI.XS_LEN_LOCATIONID_get();
  public final static int XS_LEN_EXTOUTPUTMODE = movelladot_pc_sdkJNI.XS_LEN_EXTOUTPUTMODE_get();
  public final static int XS_LEN_INITTRACKMODE = movelladot_pc_sdkJNI.XS_LEN_INITTRACKMODE_get();
  public final static int XS_LEN_STOREFILTERSTATE = movelladot_pc_sdkJNI.XS_LEN_STOREFILTERSTATE_get();
  public final static int XS_LEN_UTCTIME = movelladot_pc_sdkJNI.XS_LEN_UTCTIME_get();
  public final static int XS_LEN_FILTERPROFILELABEL = movelladot_pc_sdkJNI.XS_LEN_FILTERPROFILELABEL_get();
  public final static int XS_LEN_FILTERPROFILEFULL = movelladot_pc_sdkJNI.XS_LEN_FILTERPROFILEFULL_get();
  public final static int XS_LEN_REQFILTERPROFILEACK = movelladot_pc_sdkJNI.XS_LEN_REQFILTERPROFILEACK_get();
  public final static int XS_LEN_SETFILTERPROFILE = movelladot_pc_sdkJNI.XS_LEN_SETFILTERPROFILE_get();
  public final static int XS_LEN_GRAVITYMAGNITUDE = movelladot_pc_sdkJNI.XS_LEN_GRAVITYMAGNITUDE_get();
  public final static int XS_LEN_GPSLEVERARM = movelladot_pc_sdkJNI.XS_LEN_GPSLEVERARM_get();
  public final static int XS_LEN_LATLONALT = movelladot_pc_sdkJNI.XS_LEN_LATLONALT_get();
  public final static int XS_LEN_SETNOROTATION = movelladot_pc_sdkJNI.XS_LEN_SETNOROTATION_get();
  public final static int XS_LEN_FILTERSETTINGS = movelladot_pc_sdkJNI.XS_LEN_FILTERSETTINGS_get();
  public final static int XS_LEN_AMD = movelladot_pc_sdkJNI.XS_LEN_AMD_get();
  public final static int XS_LEN_RESETORIENTATION = movelladot_pc_sdkJNI.XS_LEN_RESETORIENTATION_get();
  public final static int XS_LEN_GPSSTATUS = movelladot_pc_sdkJNI.XS_LEN_GPSSTATUS_get();
  public final static int XS_LEN_CLIENTUSAGE = movelladot_pc_sdkJNI.XS_LEN_CLIENTUSAGE_get();
  public final static int XS_LEN_CLIENTPRIORITY = movelladot_pc_sdkJNI.XS_LEN_CLIENTPRIORITY_get();
  public final static int XS_LEN_WIRELESSCONFIG = movelladot_pc_sdkJNI.XS_LEN_WIRELESSCONFIG_get();
  public final static int XS_LEN_INFOREQUEST = movelladot_pc_sdkJNI.XS_LEN_INFOREQUEST_get();
  public final static int XS_LEN_SETOUTPUTTRIGGER = movelladot_pc_sdkJNI.XS_LEN_SETOUTPUTTRIGGER_get();
  public final static int XS_LEN_SETINPUTTRIGGER = movelladot_pc_sdkJNI.XS_LEN_SETINPUTTRIGGER_get();
  public final static int XS_LEN_RAWDATA = movelladot_pc_sdkJNI.XS_LEN_RAWDATA_get();
  public final static int XS_LEN_CALIBDATA = movelladot_pc_sdkJNI.XS_LEN_CALIBDATA_get();
  public final static int XS_LEN_CALIB_ACCDATA = movelladot_pc_sdkJNI.XS_LEN_CALIB_ACCDATA_get();
  public final static int XS_LEN_CALIB_GYRDATA = movelladot_pc_sdkJNI.XS_LEN_CALIB_GYRDATA_get();
  public final static int XS_LEN_CALIB_MAGDATA = movelladot_pc_sdkJNI.XS_LEN_CALIB_MAGDATA_get();
  public final static int XS_LEN_ORIENT_QUATDATA = movelladot_pc_sdkJNI.XS_LEN_ORIENT_QUATDATA_get();
  public final static int XS_LEN_ORIENT_EULERDATA = movelladot_pc_sdkJNI.XS_LEN_ORIENT_EULERDATA_get();
  public final static int XS_LEN_ORIENT_MATRIXSTA = movelladot_pc_sdkJNI.XS_LEN_ORIENT_MATRIXSTA_get();
  public final static int XS_LEN_SAMPLECNT = movelladot_pc_sdkJNI.XS_LEN_SAMPLECNT_get();
  public final static int XS_LEN_TEMPDATA = movelladot_pc_sdkJNI.XS_LEN_TEMPDATA_get();
  public final static int XS_LEN_CALIBDATA_FLT = movelladot_pc_sdkJNI.XS_LEN_CALIBDATA_FLT_get();
  public final static int XS_LEN_TEMPDATA_FLT = movelladot_pc_sdkJNI.XS_LEN_TEMPDATA_FLT_get();
  public final static int XS_LEN_ORIENT_QUATDATA_FLT = movelladot_pc_sdkJNI.XS_LEN_ORIENT_QUATDATA_FLT_get();
  public final static int XS_LEN_ORIENT_EULERDATA_FLT = movelladot_pc_sdkJNI.XS_LEN_ORIENT_EULERDATA_FLT_get();
  public final static int XS_LEN_ORIENT_MATRIXSTA_FLT = movelladot_pc_sdkJNI.XS_LEN_ORIENT_MATRIXSTA_FLT_get();
  public final static int XS_INVALIDSETTINGVALUE = movelladot_pc_sdkJNI.XS_INVALIDSETTINGVALUE_get();
  public final static int XS_CONF_MASTERDID = movelladot_pc_sdkJNI.XS_CONF_MASTERDID_get();
  public final static int XS_CONF_PERIOD = movelladot_pc_sdkJNI.XS_CONF_PERIOD_get();
  public final static int XS_CONF_OUTPUTSKIPFACTOR = movelladot_pc_sdkJNI.XS_CONF_OUTPUTSKIPFACTOR_get();
  public final static int XS_CONF_SYNCIN_MODE = movelladot_pc_sdkJNI.XS_CONF_SYNCIN_MODE_get();
  public final static int XS_CONF_SYNCIN_SKIPFACTOR = movelladot_pc_sdkJNI.XS_CONF_SYNCIN_SKIPFACTOR_get();
  public final static int XS_CONF_SYNCIN_OFFSET = movelladot_pc_sdkJNI.XS_CONF_SYNCIN_OFFSET_get();
  public final static int XS_CONF_DATE = movelladot_pc_sdkJNI.XS_CONF_DATE_get();
  public final static int XS_CONF_TIME = movelladot_pc_sdkJNI.XS_CONF_TIME_get();
  public final static int XS_CONF_NUMDEVICES = movelladot_pc_sdkJNI.XS_CONF_NUMDEVICES_get();
  public final static int XS_CONF_DID = movelladot_pc_sdkJNI.XS_CONF_DID_get();
  public final static int XS_CONF_DATALENGTH = movelladot_pc_sdkJNI.XS_CONF_DATALENGTH_get();
  public final static int XS_CONF_OUTPUTMODE = movelladot_pc_sdkJNI.XS_CONF_OUTPUTMODE_get();
  public final static int XS_CONF_OUTPUTSETTINGS = movelladot_pc_sdkJNI.XS_CONF_OUTPUTSETTINGS_get();
  public final static int XS_CONF_BLOCKLEN = movelladot_pc_sdkJNI.XS_CONF_BLOCKLEN_get();
  public final static int XS_CONF_MASTERDIDLEN = movelladot_pc_sdkJNI.XS_CONF_MASTERDIDLEN_get();
  public final static int XS_CONF_PERIODLEN = movelladot_pc_sdkJNI.XS_CONF_PERIODLEN_get();
  public final static int XS_CONF_OUTPUTSKIPFACTORLEN = movelladot_pc_sdkJNI.XS_CONF_OUTPUTSKIPFACTORLEN_get();
  public final static int XS_CONF_SYNCIN_MODELEN = movelladot_pc_sdkJNI.XS_CONF_SYNCIN_MODELEN_get();
  public final static int XS_CONF_SYNCIN_SKIPFACTORLEN = movelladot_pc_sdkJNI.XS_CONF_SYNCIN_SKIPFACTORLEN_get();
  public final static int XS_CONF_SYNCIN_OFFSETLEN = movelladot_pc_sdkJNI.XS_CONF_SYNCIN_OFFSETLEN_get();
  public final static int XS_CONF_DATELEN = movelladot_pc_sdkJNI.XS_CONF_DATELEN_get();
  public final static int XS_CONF_TIMELEN = movelladot_pc_sdkJNI.XS_CONF_TIMELEN_get();
  public final static int XS_CONF_RESERVED_CLIENTLEN = movelladot_pc_sdkJNI.XS_CONF_RESERVED_CLIENTLEN_get();
  public final static int XS_CONF_RESERVED_HOSTLEN = movelladot_pc_sdkJNI.XS_CONF_RESERVED_HOSTLEN_get();
  public final static int XS_CONF_NUMDEVICESLEN = movelladot_pc_sdkJNI.XS_CONF_NUMDEVICESLEN_get();
  public final static int XS_CONF_DIDLEN = movelladot_pc_sdkJNI.XS_CONF_DIDLEN_get();
  public final static int XS_CONF_DATALENGTHLEN = movelladot_pc_sdkJNI.XS_CONF_DATALENGTHLEN_get();
  public final static int XS_CONF_OUTPUTMODELEN = movelladot_pc_sdkJNI.XS_CONF_OUTPUTMODELEN_get();
  public final static int XS_CONF_OUTPUTSETTINGSLEN = movelladot_pc_sdkJNI.XS_CONF_OUTPUTSETTINGSLEN_get();
  public final static double XS_SYNC_CLOCKFREQMHZ = movelladot_pc_sdkJNI.XS_SYNC_CLOCKFREQMHZ_get();
  public final static double XS_SYNC_CLOCK_NS_TO_TICKS = movelladot_pc_sdkJNI.XS_SYNC_CLOCK_NS_TO_TICKS_get();
  public final static double XS_SYNC_CLOCK_TICKS_TO_NS = movelladot_pc_sdkJNI.XS_SYNC_CLOCK_TICKS_TO_NS_get();
  public final static double XS_SYNC_CLOCK_US_TO_TICKS = movelladot_pc_sdkJNI.XS_SYNC_CLOCK_US_TO_TICKS_get();
  public final static double XS_SYNC_CLOCK_TICKS_TO_US = movelladot_pc_sdkJNI.XS_SYNC_CLOCK_TICKS_TO_US_get();
  public final static int XS_PARAM_SYNCIN_MODE = movelladot_pc_sdkJNI.XS_PARAM_SYNCIN_MODE_get();
  public final static int XS_PARAM_SYNCIN_SKIPFACTOR = movelladot_pc_sdkJNI.XS_PARAM_SYNCIN_SKIPFACTOR_get();
  public final static int XS_PARAM_SYNCIN_OFFSET = movelladot_pc_sdkJNI.XS_PARAM_SYNCIN_OFFSET_get();
  public final static int XS_SYNCIN_DISABLED = movelladot_pc_sdkJNI.XS_SYNCIN_DISABLED_get();
  public final static int XS_SYNCIN_EDGE_RISING = movelladot_pc_sdkJNI.XS_SYNCIN_EDGE_RISING_get();
  public final static int XS_SYNCIN_EDGE_FALLING = movelladot_pc_sdkJNI.XS_SYNCIN_EDGE_FALLING_get();
  public final static int XS_SYNCIN_EDGE_BOTH = movelladot_pc_sdkJNI.XS_SYNCIN_EDGE_BOTH_get();
  public final static int XS_SYNCIN_EDGE_MASK = movelladot_pc_sdkJNI.XS_SYNCIN_EDGE_MASK_get();
  public final static int XS_SYNCIN_TYPE_DOSAMPLING = movelladot_pc_sdkJNI.XS_SYNCIN_TYPE_DOSAMPLING_get();
  public final static int XS_SYNCIN_TYPE_SENDLASTDATA = movelladot_pc_sdkJNI.XS_SYNCIN_TYPE_SENDLASTDATA_get();
  public final static int XS_SYNCIN_TYPE_CLOCK = movelladot_pc_sdkJNI.XS_SYNCIN_TYPE_CLOCK_get();
  public final static int XS_SYNCIN_TYPE_MASK = movelladot_pc_sdkJNI.XS_SYNCIN_TYPE_MASK_get();
  public final static int XS_PARAM_SYNCOUT_MODE = movelladot_pc_sdkJNI.XS_PARAM_SYNCOUT_MODE_get();
  public final static int XS_PARAM_SYNCOUT_SKIPFACTOR = movelladot_pc_sdkJNI.XS_PARAM_SYNCOUT_SKIPFACTOR_get();
  public final static int XS_PARAM_SYNCOUT_OFFSET = movelladot_pc_sdkJNI.XS_PARAM_SYNCOUT_OFFSET_get();
  public final static int XS_PARAM_SYNCOUT_PULSEWIDTH = movelladot_pc_sdkJNI.XS_PARAM_SYNCOUT_PULSEWIDTH_get();
  public final static int XS_SYNCOUT_DISABLED = movelladot_pc_sdkJNI.XS_SYNCOUT_DISABLED_get();
  public final static int XS_SYNCOUT_TYPE_TOGGLE = movelladot_pc_sdkJNI.XS_SYNCOUT_TYPE_TOGGLE_get();
  public final static int XS_SYNCOUT_TYPE_PULSE = movelladot_pc_sdkJNI.XS_SYNCOUT_TYPE_PULSE_get();
  public final static int XS_SYNCOUT_POL_NEG = movelladot_pc_sdkJNI.XS_SYNCOUT_POL_NEG_get();
  public final static int XS_SYNCOUT_POL_POS = movelladot_pc_sdkJNI.XS_SYNCOUT_POL_POS_get();
  public final static int XS_SYNCOUT_TYPE_MASK = movelladot_pc_sdkJNI.XS_SYNCOUT_TYPE_MASK_get();
  public final static int XS_SYNCOUT_POL_MASK = movelladot_pc_sdkJNI.XS_SYNCOUT_POL_MASK_get();
  public final static int XS_INITTRACKMODE_DISABLED = movelladot_pc_sdkJNI.XS_INITTRACKMODE_DISABLED_get();
  public final static int XS_INITTRACKMODE_ENABLED = movelladot_pc_sdkJNI.XS_INITTRACKMODE_ENABLED_get();
  public final static int XS_PARAM_FILTER_GAIN = movelladot_pc_sdkJNI.XS_PARAM_FILTER_GAIN_get();
  public final static int XS_PARAM_FILTER_RHO = movelladot_pc_sdkJNI.XS_PARAM_FILTER_RHO_get();
  public final static int XS_DONOTSTORE = movelladot_pc_sdkJNI.XS_DONOTSTORE_get();
  public final static int XS_STORE = movelladot_pc_sdkJNI.XS_STORE_get();
  public final static int XS_AMDSETTING_DISABLED = movelladot_pc_sdkJNI.XS_AMDSETTING_DISABLED_get();
  public final static int XS_AMDSETTING_ENABLED = movelladot_pc_sdkJNI.XS_AMDSETTING_ENABLED_get();
  public final static int XS_PARAM_ROTSENSOR = movelladot_pc_sdkJNI.XS_PARAM_ROTSENSOR_get();
  public final static int XS_PARAM_ROTLOCAL = movelladot_pc_sdkJNI.XS_PARAM_ROTLOCAL_get();
  public final static int XS_SENDRAWSTRING_INIT = movelladot_pc_sdkJNI.XS_SENDRAWSTRING_INIT_get();
  public final static int XS_SENDRAWSTRING_DEFAULT = movelladot_pc_sdkJNI.XS_SENDRAWSTRING_DEFAULT_get();
  public final static int XS_SENDRAWSTRING_SEND = movelladot_pc_sdkJNI.XS_SENDRAWSTRING_SEND_get();
  public final static int XS_TO_DEFAULT = movelladot_pc_sdkJNI.XS_TO_DEFAULT_get();
  public final static int XS_TO_INIT = movelladot_pc_sdkJNI.XS_TO_INIT_get();
  public final static int XS_TO_RETRY = movelladot_pc_sdkJNI.XS_TO_RETRY_get();
  public final static int XS_PERIOD_10HZ = movelladot_pc_sdkJNI.XS_PERIOD_10HZ_get();
  public final static int XS_PERIOD_12HZ = movelladot_pc_sdkJNI.XS_PERIOD_12HZ_get();
  public final static int XS_PERIOD_15HZ = movelladot_pc_sdkJNI.XS_PERIOD_15HZ_get();
  public final static int XS_PERIOD_16HZ = movelladot_pc_sdkJNI.XS_PERIOD_16HZ_get();
  public final static int XS_PERIOD_18HZ = movelladot_pc_sdkJNI.XS_PERIOD_18HZ_get();
  public final static int XS_PERIOD_20HZ = movelladot_pc_sdkJNI.XS_PERIOD_20HZ_get();
  public final static int XS_PERIOD_24HZ = movelladot_pc_sdkJNI.XS_PERIOD_24HZ_get();
  public final static int XS_PERIOD_25HZ = movelladot_pc_sdkJNI.XS_PERIOD_25HZ_get();
  public final static int XS_PERIOD_30HZ = movelladot_pc_sdkJNI.XS_PERIOD_30HZ_get();
  public final static int XS_PERIOD_32HZ = movelladot_pc_sdkJNI.XS_PERIOD_32HZ_get();
  public final static int XS_PERIOD_36HZ = movelladot_pc_sdkJNI.XS_PERIOD_36HZ_get();
  public final static int XS_PERIOD_40HZ = movelladot_pc_sdkJNI.XS_PERIOD_40HZ_get();
  public final static int XS_PERIOD_45HZ = movelladot_pc_sdkJNI.XS_PERIOD_45HZ_get();
  public final static int XS_PERIOD_48HZ = movelladot_pc_sdkJNI.XS_PERIOD_48HZ_get();
  public final static int XS_PERIOD_50HZ = movelladot_pc_sdkJNI.XS_PERIOD_50HZ_get();
  public final static int XS_PERIOD_60HZ = movelladot_pc_sdkJNI.XS_PERIOD_60HZ_get();
  public final static int XS_PERIOD_64HZ = movelladot_pc_sdkJNI.XS_PERIOD_64HZ_get();
  public final static int XS_PERIOD_72HZ = movelladot_pc_sdkJNI.XS_PERIOD_72HZ_get();
  public final static int XS_PERIOD_75HZ = movelladot_pc_sdkJNI.XS_PERIOD_75HZ_get();
  public final static int XS_PERIOD_80HZ = movelladot_pc_sdkJNI.XS_PERIOD_80HZ_get();
  public final static int XS_PERIOD_90HZ = movelladot_pc_sdkJNI.XS_PERIOD_90HZ_get();
  public final static int XS_PERIOD_96HZ = movelladot_pc_sdkJNI.XS_PERIOD_96HZ_get();
  public final static int XS_PERIOD_100HZ = movelladot_pc_sdkJNI.XS_PERIOD_100HZ_get();
  public final static int XS_PERIOD_120HZ = movelladot_pc_sdkJNI.XS_PERIOD_120HZ_get();
  public final static int XS_PERIOD_128HZ = movelladot_pc_sdkJNI.XS_PERIOD_128HZ_get();
  public final static int XS_PERIOD_144HZ = movelladot_pc_sdkJNI.XS_PERIOD_144HZ_get();
  public final static int XS_PERIOD_150HZ = movelladot_pc_sdkJNI.XS_PERIOD_150HZ_get();
  public final static int XS_PERIOD_160HZ = movelladot_pc_sdkJNI.XS_PERIOD_160HZ_get();
  public final static int XS_PERIOD_180HZ = movelladot_pc_sdkJNI.XS_PERIOD_180HZ_get();
  public final static int XS_PERIOD_192HZ = movelladot_pc_sdkJNI.XS_PERIOD_192HZ_get();
  public final static int XS_PERIOD_200HZ = movelladot_pc_sdkJNI.XS_PERIOD_200HZ_get();
  public final static int XS_PERIOD_225HZ = movelladot_pc_sdkJNI.XS_PERIOD_225HZ_get();
  public final static int XS_PERIOD_240HZ = movelladot_pc_sdkJNI.XS_PERIOD_240HZ_get();
  public final static int XS_PERIOD_256HZ = movelladot_pc_sdkJNI.XS_PERIOD_256HZ_get();
  public final static int XS_PERIOD_288HZ = movelladot_pc_sdkJNI.XS_PERIOD_288HZ_get();
  public final static int XS_PERIOD_300HZ = movelladot_pc_sdkJNI.XS_PERIOD_300HZ_get();
  public final static int XS_PERIOD_320HZ = movelladot_pc_sdkJNI.XS_PERIOD_320HZ_get();
  public final static int XS_PERIOD_360HZ = movelladot_pc_sdkJNI.XS_PERIOD_360HZ_get();
  public final static int XS_PERIOD_384HZ = movelladot_pc_sdkJNI.XS_PERIOD_384HZ_get();
  public final static int XS_PERIOD_400HZ = movelladot_pc_sdkJNI.XS_PERIOD_400HZ_get();
  public final static int XS_PERIOD_450HZ = movelladot_pc_sdkJNI.XS_PERIOD_450HZ_get();
  public final static int XS_PERIOD_480HZ = movelladot_pc_sdkJNI.XS_PERIOD_480HZ_get();
  public final static int XS_PERIOD_512HZ = movelladot_pc_sdkJNI.XS_PERIOD_512HZ_get();
  public final static int XS_PERIOD_576HZ = movelladot_pc_sdkJNI.XS_PERIOD_576HZ_get();
  public final static int XS_PERIOD_600HZ = movelladot_pc_sdkJNI.XS_PERIOD_600HZ_get();
  public final static int XS_PERIOD_640HZ = movelladot_pc_sdkJNI.XS_PERIOD_640HZ_get();
  public final static int XS_PERIOD_720HZ = movelladot_pc_sdkJNI.XS_PERIOD_720HZ_get();
  public final static int XS_PERIOD_768HZ = movelladot_pc_sdkJNI.XS_PERIOD_768HZ_get();
  public final static int XS_PERIOD_800HZ = movelladot_pc_sdkJNI.XS_PERIOD_800HZ_get();
  public final static int XS_PERIOD_900HZ = movelladot_pc_sdkJNI.XS_PERIOD_900HZ_get();
  public final static int XS_PERIOD_960HZ = movelladot_pc_sdkJNI.XS_PERIOD_960HZ_get();
  public final static int XS_PERIOD_1152HZ = movelladot_pc_sdkJNI.XS_PERIOD_1152HZ_get();
  public final static int XS_PERIOD_1200HZ = movelladot_pc_sdkJNI.XS_PERIOD_1200HZ_get();
  public final static int XS_PERIOD_1280HZ = movelladot_pc_sdkJNI.XS_PERIOD_1280HZ_get();
  public final static int XS_PERIOD_1440HZ = movelladot_pc_sdkJNI.XS_PERIOD_1440HZ_get();
  public final static int XS_PERIOD_1536HZ = movelladot_pc_sdkJNI.XS_PERIOD_1536HZ_get();
  public final static int XS_PERIOD_1600HZ = movelladot_pc_sdkJNI.XS_PERIOD_1600HZ_get();
  public final static int XS_PERIOD_1800HZ = movelladot_pc_sdkJNI.XS_PERIOD_1800HZ_get();
  public final static int XS_PERIOD_1920HZ = movelladot_pc_sdkJNI.XS_PERIOD_1920HZ_get();
  public final static int XS_PERIOD_2304HZ = movelladot_pc_sdkJNI.XS_PERIOD_2304HZ_get();
  public final static int XS_PERIOD_2400HZ = movelladot_pc_sdkJNI.XS_PERIOD_2400HZ_get();
  public final static int XS_PERIOD_2560HZ = movelladot_pc_sdkJNI.XS_PERIOD_2560HZ_get();
  public final static int XS_PERIOD_2880HZ = movelladot_pc_sdkJNI.XS_PERIOD_2880HZ_get();
  public final static int XS_PERIOD_3200HZ = movelladot_pc_sdkJNI.XS_PERIOD_3200HZ_get();
  public final static int XS_PERIOD_3600HZ = movelladot_pc_sdkJNI.XS_PERIOD_3600HZ_get();
  public final static int XS_PERIOD_3840HZ = movelladot_pc_sdkJNI.XS_PERIOD_3840HZ_get();
  public final static int XS_PERIOD_4608HZ = movelladot_pc_sdkJNI.XS_PERIOD_4608HZ_get();
  public final static int XS_PERIOD_4800HZ = movelladot_pc_sdkJNI.XS_PERIOD_4800HZ_get();
  public final static int XS_PERIOD_5760HZ = movelladot_pc_sdkJNI.XS_PERIOD_5760HZ_get();
  public final static int XS_PERIOD_6400HZ = movelladot_pc_sdkJNI.XS_PERIOD_6400HZ_get();
  public final static int XS_PERIOD_7200HZ = movelladot_pc_sdkJNI.XS_PERIOD_7200HZ_get();
  public final static int XS_PERIOD_7680HZ = movelladot_pc_sdkJNI.XS_PERIOD_7680HZ_get();
  public final static int XS_PERIOD_9600HZ = movelladot_pc_sdkJNI.XS_PERIOD_9600HZ_get();
  public final static int XS_PERIOD_11520HZ = movelladot_pc_sdkJNI.XS_PERIOD_11520HZ_get();
  public final static int XSDEVICEID_PRODUCT_CODE_LEN = movelladot_pc_sdkJNI.XSDEVICEID_PRODUCT_CODE_LEN_get();
  public final static String XSDEVICEID_PRODUCT_CODE_INIT = movelladot_pc_sdkJNI.XSDEVICEID_PRODUCT_CODE_INIT_get();
  public final static int WANTXSMATH2 = movelladot_pc_sdkJNI.WANTXSMATH2_get();
  public final static int XSENS_VENDOR_ID = movelladot_pc_sdkJNI.XSENS_VENDOR_ID_get();
  public final static int FTDI_VENDOR_ID = movelladot_pc_sdkJNI.FTDI_VENDOR_ID_get();
  public final static int XDI_MAX_FREQUENCY_VAL = movelladot_pc_sdkJNI.XDI_MAX_FREQUENCY_VAL_get();
  public final static int XS_BID_MASTER = movelladot_pc_sdkJNI.XS_BID_MASTER_get();
  public final static int XS_BID_BROADCAST = movelladot_pc_sdkJNI.XS_BID_BROADCAST_get();
  public final static int XS_BID_MT = movelladot_pc_sdkJNI.XS_BID_MT_get();
  public final static int XS_BID_INVALID = movelladot_pc_sdkJNI.XS_BID_INVALID_get();
  public final static int XS_BID_DYNAMIC = movelladot_pc_sdkJNI.XS_BID_DYNAMIC_get();
  public final static int XS_PREAMBLE = movelladot_pc_sdkJNI.XS_PREAMBLE_get();
  public final static int XS_EXTLENCODE = movelladot_pc_sdkJNI.XS_EXTLENCODE_get();
  public final static int XS_LEN_MSGHEADER = movelladot_pc_sdkJNI.XS_LEN_MSGHEADER_get();
  public final static int XS_LEN_MSGEXTHEADER = movelladot_pc_sdkJNI.XS_LEN_MSGEXTHEADER_get();
  public final static int XS_LEN_MSGHEADERCS = movelladot_pc_sdkJNI.XS_LEN_MSGHEADERCS_get();
  public final static int XS_LEN_MSGEXTHEADERCS = movelladot_pc_sdkJNI.XS_LEN_MSGEXTHEADERCS_get();
  public final static int XS_LEN_CHECKSUM = movelladot_pc_sdkJNI.XS_LEN_CHECKSUM_get();
  public final static int XS_LEN_UNSIGSHORT = movelladot_pc_sdkJNI.XS_LEN_UNSIGSHORT_get();
  public final static int XS_LEN_UNSIGINT = movelladot_pc_sdkJNI.XS_LEN_UNSIGINT_get();
  public final static int XS_LEN_FLOAT = movelladot_pc_sdkJNI.XS_LEN_FLOAT_get();
  public final static int XS_MAXDATALEN = movelladot_pc_sdkJNI.XS_MAXDATALEN_get();
  public final static int XS_MAXSHORTDATALEN = movelladot_pc_sdkJNI.XS_MAXSHORTDATALEN_get();
  public final static int XS_MAXMSGLEN = movelladot_pc_sdkJNI.XS_MAXMSGLEN_get();
  public final static int XS_MAXSHORTMSGLEN = movelladot_pc_sdkJNI.XS_MAXSHORTMSGLEN_get();
  public final static int XS_MAXGARBAGE = movelladot_pc_sdkJNI.XS_MAXGARBAGE_get();
  public final static int GNSS_PVT_FLAGS_GNSS_FIX_NONE = movelladot_pc_sdkJNI.GNSS_PVT_FLAGS_GNSS_FIX_NONE_get();
  public final static int GNSS_PVT_FLAGS_GNSS_FIX_SINGLE = movelladot_pc_sdkJNI.GNSS_PVT_FLAGS_GNSS_FIX_SINGLE_get();
  public final static int GNSS_PVT_FLAGS_GNSS_FIX_DIFFERENTIAL = movelladot_pc_sdkJNI.GNSS_PVT_FLAGS_GNSS_FIX_DIFFERENTIAL_get();
  public final static int GNSS_PVT_FLAGS_CARRIER_SOLUTION_NONE = movelladot_pc_sdkJNI.GNSS_PVT_FLAGS_CARRIER_SOLUTION_NONE_get();
  public final static int GNSS_PVT_FLAGS_CARRIER_SOLUTION_FLOATING = movelladot_pc_sdkJNI.GNSS_PVT_FLAGS_CARRIER_SOLUTION_FLOATING_get();
  public final static int GNSS_PVT_FLAGS_CARRIER_SOLUTION_FIXED = movelladot_pc_sdkJNI.GNSS_PVT_FLAGS_CARRIER_SOLUTION_FIXED_get();
  public final static int GNSS_ACCURACY_DEFAULT_DEVIATION = movelladot_pc_sdkJNI.GNSS_ACCURACY_DEFAULT_DEVIATION_get();
  public final static int FSFL_ClipAccShift = movelladot_pc_sdkJNI.FSFL_ClipAccShift_get();
  public final static int FSFL_ClipGyrShift = movelladot_pc_sdkJNI.FSFL_ClipGyrShift_get();
  public final static int FSFL_ClipMagshift = movelladot_pc_sdkJNI.FSFL_ClipMagshift_get();
  public final static int FSFL_RotationShift = movelladot_pc_sdkJNI.FSFL_RotationShift_get();
  public final static int XSFINGERSEGMENTCOUNT = movelladot_pc_sdkJNI.XSFINGERSEGMENTCOUNT_get();
  public final static int XS_MAX_FILTERPROFILES = movelladot_pc_sdkJNI.XS_MAX_FILTERPROFILES_get();
  public final static int XS_LEN_FILTERPROFILELABEL_TERM = movelladot_pc_sdkJNI.XS_LEN_FILTERPROFILELABEL_TERM_get();
  public final static int XS_LEN_FILTERPROFILEKIND_TERM = movelladot_pc_sdkJNI.XS_LEN_FILTERPROFILEKIND_TERM_get();
  public final static int XS_MAX_FILTERPROFILES_IN_MT = movelladot_pc_sdkJNI.XS_MAX_FILTERPROFILES_IN_MT_get();
}
