
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class movelladot_pc_sdk implements movelladot_pc_sdkConstants {
  public static boolean xorBool(boolean a, boolean b) {
    return movelladot_pc_sdkJNI.xorBool(a, b);
  }

  public static String toXsString(XsDataFlags s) {
    return movelladot_pc_sdkJNI.toXsString(s.swigValue());
  }

  public static XsArrayDescriptor getG_xsStringDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsStringDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static String makeNiceProductCode(String pc, int maxSz) {
    return movelladot_pc_sdkJNI.makeNiceProductCode__SWIG_0(pc, maxSz);
  }

  public static String makeNiceProductCode(String pc) {
    return movelladot_pc_sdkJNI.makeNiceProductCode__SWIG_1(pc);
  }

  public static String makeNiceProductCode(SWIGTYPE_p_unsigned_char pc, int maxSz) {
    return movelladot_pc_sdkJNI.makeNiceProductCode__SWIG_2(SWIGTYPE_p_unsigned_char.getCPtr(pc), maxSz);
  }

  public static String makeNiceProductCode(SWIGTYPE_p_unsigned_char pc) {
    return movelladot_pc_sdkJNI.makeNiceProductCode__SWIG_3(SWIGTYPE_p_unsigned_char.getCPtr(pc));
  }

  public static String XsResultValueToString(XsResultValue result) {
    return movelladot_pc_sdkJNI.XsResultValueToString(result.swigValue());
  }

  public static double getXsMath_e() {
    return movelladot_pc_sdkJNI.XsMath_e_get();
  }

  public static double getXsMath_pi() {
    return movelladot_pc_sdkJNI.XsMath_pi_get();
  }

  public static double getXsMath_tinyValue() {
    return movelladot_pc_sdkJNI.XsMath_tinyValue_get();
  }

  public static double getXsMath_hugeValue() {
    return movelladot_pc_sdkJNI.XsMath_hugeValue_get();
  }

  public static double getXsMath_epsilon() {
    return movelladot_pc_sdkJNI.XsMath_epsilon_get();
  }

  public static double getXsMath_sqrtEpsilon() {
    return movelladot_pc_sdkJNI.XsMath_sqrtEpsilon_get();
  }

  public static double getXsMath_denormalized() {
    return movelladot_pc_sdkJNI.XsMath_denormalized_get();
  }

  public static double getXsMath_sqrtDenormalized() {
    return movelladot_pc_sdkJNI.XsMath_sqrtDenormalized_get();
  }

  public static double getXsMath_rad2degValue() {
    return movelladot_pc_sdkJNI.XsMath_rad2degValue_get();
  }

  public static double getXsMath_deg2radValue() {
    return movelladot_pc_sdkJNI.XsMath_deg2radValue_get();
  }

  public static double getXsMath_zero() {
    return movelladot_pc_sdkJNI.XsMath_zero_get();
  }

  public static double getXsMath_pt25() {
    return movelladot_pc_sdkJNI.XsMath_pt25_get();
  }

  public static double getXsMath_pt5() {
    return movelladot_pc_sdkJNI.XsMath_pt5_get();
  }

  public static double getXsMath_minusPt5() {
    return movelladot_pc_sdkJNI.XsMath_minusPt5_get();
  }

  public static double getXsMath_one() {
    return movelladot_pc_sdkJNI.XsMath_one_get();
  }

  public static double getXsMath_minusOne() {
    return movelladot_pc_sdkJNI.XsMath_minusOne_get();
  }

  public static double getXsMath_two() {
    return movelladot_pc_sdkJNI.XsMath_two_get();
  }

  public static double getXsMath_four() {
    return movelladot_pc_sdkJNI.XsMath_four_get();
  }

  public static double getXsMath_minusTwo() {
    return movelladot_pc_sdkJNI.XsMath_minusTwo_get();
  }

  public static double getXsMath_minusHalfPi() {
    return movelladot_pc_sdkJNI.XsMath_minusHalfPi_get();
  }

  public static double getXsMath_halfPi() {
    return movelladot_pc_sdkJNI.XsMath_halfPi_get();
  }

  public static double getXsMath_twoPi() {
    return movelladot_pc_sdkJNI.XsMath_twoPi_get();
  }

  public static double getXsMath_sqrt2() {
    return movelladot_pc_sdkJNI.XsMath_sqrt2_get();
  }

  public static double getXsMath_sqrtHalf() {
    return movelladot_pc_sdkJNI.XsMath_sqrtHalf_get();
  }

  public static double getXsMath_infinity() {
    return movelladot_pc_sdkJNI.XsMath_infinity_get();
  }

  public static double getE() {
    return movelladot_pc_sdkJNI.e_get();
  }

  public static double getPi() {
    return movelladot_pc_sdkJNI.pi_get();
  }

  public static double getTinyValue() {
    return movelladot_pc_sdkJNI.tinyValue_get();
  }

  public static double getHugeValue() {
    return movelladot_pc_sdkJNI.hugeValue_get();
  }

  public static double getEpsilon() {
    return movelladot_pc_sdkJNI.epsilon_get();
  }

  public static double getSqrtEpsilon() {
    return movelladot_pc_sdkJNI.sqrtEpsilon_get();
  }

  public static double getDenormalized() {
    return movelladot_pc_sdkJNI.denormalized_get();
  }

  public static double getSqrtDenormalized() {
    return movelladot_pc_sdkJNI.sqrtDenormalized_get();
  }

  public static double getRad2degValue() {
    return movelladot_pc_sdkJNI.rad2degValue_get();
  }

  public static double getDeg2radValue() {
    return movelladot_pc_sdkJNI.deg2radValue_get();
  }

  public static double getZero() {
    return movelladot_pc_sdkJNI.zero_get();
  }

  public static double getPt25() {
    return movelladot_pc_sdkJNI.pt25_get();
  }

  public static double getPt5() {
    return movelladot_pc_sdkJNI.pt5_get();
  }

  public static double getMinusPt5() {
    return movelladot_pc_sdkJNI.minusPt5_get();
  }

  public static double getOne() {
    return movelladot_pc_sdkJNI.one_get();
  }

  public static double getMinusOne() {
    return movelladot_pc_sdkJNI.minusOne_get();
  }

  public static double getTwo() {
    return movelladot_pc_sdkJNI.two_get();
  }

  public static double getFour() {
    return movelladot_pc_sdkJNI.four_get();
  }

  public static double getMinusTwo() {
    return movelladot_pc_sdkJNI.minusTwo_get();
  }

  public static double getMinusHalfPi() {
    return movelladot_pc_sdkJNI.minusHalfPi_get();
  }

  public static double getHalfPi() {
    return movelladot_pc_sdkJNI.halfPi_get();
  }

  public static double getTwoPi() {
    return movelladot_pc_sdkJNI.twoPi_get();
  }

  public static double getSqrt2() {
    return movelladot_pc_sdkJNI.sqrt2_get();
  }

  public static double getSqrtHalf() {
    return movelladot_pc_sdkJNI.sqrtHalf_get();
  }

  public static double getInfinity() {
    return movelladot_pc_sdkJNI.infinity_get();
  }

  public static double asinClamped(double x) {
    return movelladot_pc_sdkJNI.asinClamped(x);
  }

  public static double rad2deg(double radians) {
    return movelladot_pc_sdkJNI.rad2deg(radians);
  }

  public static double deg2rad(double degrees) {
    return movelladot_pc_sdkJNI.deg2rad(degrees);
  }

  public static double pow2(double a) {
    return movelladot_pc_sdkJNI.pow2(a);
  }

  public static double pow3(double a) {
    return movelladot_pc_sdkJNI.pow3(a);
  }

  public static int doubleToLong(double d) {
    return movelladot_pc_sdkJNI.doubleToLong(d);
  }

  public static long doubleToInt64(double d) {
    return movelladot_pc_sdkJNI.doubleToInt64(d);
  }

  public static void swap(XsVector first, XsVector second) {
    movelladot_pc_sdkJNI.swap__SWIG_1(XsVector.getCPtr(first), first, XsVector.getCPtr(second), second);
  }

  public static void swap(XsMatrix first, XsMatrix second) {
    movelladot_pc_sdkJNI.swap__SWIG_2(XsMatrix.getCPtr(first), first, XsMatrix.getCPtr(second), second);
  }

  public static XsBaudRate codeToRate(XsBaudCode baudcode) {
    return XsBaudRate.swigToEnum(movelladot_pc_sdkJNI.codeToRate(baudcode.swigValue()));
  }

  public static XsBaudCode rateToCode(XsBaudRate baudrate) {
    return XsBaudCode.swigToEnum(movelladot_pc_sdkJNI.rateToCode(baudrate.swigValue()));
  }

  public static int rateToNumeric(XsBaudRate baudrate) {
    return movelladot_pc_sdkJNI.rateToNumeric(baudrate.swigValue());
  }

  public static XsBaudRate numericToRate(int numeric) {
    return XsBaudRate.swigToEnum(movelladot_pc_sdkJNI.numericToRate(numeric));
  }

  public static XsArrayDescriptor getG_xsByteArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsByteArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static void swap(XsQuaternion first, XsQuaternion second) {
    movelladot_pc_sdkJNI.swap__SWIG_3(XsQuaternion.getCPtr(first), first, XsQuaternion.getCPtr(second), second);
  }

  public static void swap(XsFingerData first, XsFingerData second) {
    movelladot_pc_sdkJNI.swap__SWIG_4(XsFingerData.getCPtr(first), first, XsFingerData.getCPtr(second), second);
  }

  public static void swap(XsGloveData first, XsGloveData second) {
    movelladot_pc_sdkJNI.swap__SWIG_5(XsGloveData.getCPtr(first), first, XsGloveData.getCPtr(second), second);
  }

  public static void swap(XsFilterProfile first, XsFilterProfile second) {
    movelladot_pc_sdkJNI.swap__SWIG_6(XsFilterProfile.getCPtr(first), first, XsFilterProfile.getCPtr(second), second);
  }

  public static XsArrayDescriptor getG_xsStringArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsStringArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static XsArrayDescriptor getG_xsIntArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsIntArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static XsArrayDescriptor getG_xsDeviceIdArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsDeviceIdArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static XsArrayDescriptor getG_xsPortInfoArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsPortInfoArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static XsArrayDescriptor getG_xsDataPacketPtrArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsDataPacketPtrArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static XsArrayDescriptor getG_xsFilterProfileArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsFilterProfileArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static void setGJournal(SWIGTYPE_p_Journaller value) {
    movelladot_pc_sdkJNI.gJournal_set(SWIGTYPE_p_Journaller.getCPtr(value));
  }

  public static SWIGTYPE_p_Journaller getGJournal() {
    long cPtr = movelladot_pc_sdkJNI.gJournal_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Journaller(cPtr, false);
  }

  public static void xsdotsdkDllVersion(XsVersion version) {
    movelladot_pc_sdkJNI.xsdotsdkDllVersion(XsVersion.getCPtr(version), version);
  }

  public static void xsdotsdkDllPath(XsString path) {
    movelladot_pc_sdkJNI.xsdotsdkDllPath(XsString.getCPtr(path), path);
  }

  public static String XsDotFirmwareUpdateResultToString(XsDotFirmwareUpdateResult result) {
    return movelladot_pc_sdkJNI.XsDotFirmwareUpdateResultToString(result.swigValue());
  }

  public static XsArrayDescriptor getG_xsDotDevicePtrArrayDescriptor() {
    long cPtr = movelladot_pc_sdkJNI.g_xsDotDevicePtrArrayDescriptor_get();
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public static String XsPayloadModeToString(XsPayloadMode mode) {
    return movelladot_pc_sdkJNI.XsPayloadModeToString(mode.swigValue());
  }

  public static String XsRecordingAcknowledgeResultToString(XsRecordingAcknowledgeResult res) {
    return movelladot_pc_sdkJNI.XsRecordingAcknowledgeResultToString(res.swigValue());
  }

  public static boolean isValidXsRecordingAcknowledgeResult(XsRecordingAcknowledgeResult ackRes) {
    return movelladot_pc_sdkJNI.isValidXsRecordingAcknowledgeResult(ackRes.swigValue());
  }

  public static boolean isValidXsRecordingExportDataField(XsRecordingExportDataField dataField) {
    return movelladot_pc_sdkJNI.isValidXsRecordingExportDataField(dataField.swigValue());
  }

  public static String XsSyncAcknowledgeResultToString(XsSyncAcknowledgeResult res) {
    return movelladot_pc_sdkJNI.XsSyncAcknowledgeResultToString(res.swigValue());
  }

  public static boolean isValidXsSyncAcknowledgeResult(XsSyncAcknowledgeResult ackRes) {
    return movelladot_pc_sdkJNI.isValidXsSyncAcknowledgeResult(ackRes.swigValue());
  }

}
