
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsBaudCode {
  public final static XsBaudCode XBC_4k8 = new XsBaudCode("XBC_4k8", movelladot_pc_sdkJNI.XBC_4k8_get());
  public final static XsBaudCode XBC_9k6 = new XsBaudCode("XBC_9k6", movelladot_pc_sdkJNI.XBC_9k6_get());
  public final static XsBaudCode XBC_14k4 = new XsBaudCode("XBC_14k4", movelladot_pc_sdkJNI.XBC_14k4_get());
  public final static XsBaudCode XBC_19k2 = new XsBaudCode("XBC_19k2", movelladot_pc_sdkJNI.XBC_19k2_get());
  public final static XsBaudCode XBC_28k8 = new XsBaudCode("XBC_28k8", movelladot_pc_sdkJNI.XBC_28k8_get());
  public final static XsBaudCode XBC_38k4 = new XsBaudCode("XBC_38k4", movelladot_pc_sdkJNI.XBC_38k4_get());
  public final static XsBaudCode XBC_57k6 = new XsBaudCode("XBC_57k6", movelladot_pc_sdkJNI.XBC_57k6_get());
  public final static XsBaudCode XBC_76k8 = new XsBaudCode("XBC_76k8", movelladot_pc_sdkJNI.XBC_76k8_get());
  public final static XsBaudCode XBC_115k2 = new XsBaudCode("XBC_115k2", movelladot_pc_sdkJNI.XBC_115k2_get());
  public final static XsBaudCode XBC_230k4 = new XsBaudCode("XBC_230k4", movelladot_pc_sdkJNI.XBC_230k4_get());
  public final static XsBaudCode XBC_460k8 = new XsBaudCode("XBC_460k8", movelladot_pc_sdkJNI.XBC_460k8_get());
  public final static XsBaudCode XBC_921k6 = new XsBaudCode("XBC_921k6", movelladot_pc_sdkJNI.XBC_921k6_get());
  public final static XsBaudCode XBC_921k6Legacy = new XsBaudCode("XBC_921k6Legacy", movelladot_pc_sdkJNI.XBC_921k6Legacy_get());
  public final static XsBaudCode XBC_2MegaBaud = new XsBaudCode("XBC_2MegaBaud", movelladot_pc_sdkJNI.XBC_2MegaBaud_get());
  public final static XsBaudCode XBC_3_5MegaBaud = new XsBaudCode("XBC_3_5MegaBaud", movelladot_pc_sdkJNI.XBC_3_5MegaBaud_get());
  public final static XsBaudCode XBC_4MegaBaud = new XsBaudCode("XBC_4MegaBaud", movelladot_pc_sdkJNI.XBC_4MegaBaud_get());
  public final static XsBaudCode XBC_Invalid = new XsBaudCode("XBC_Invalid", movelladot_pc_sdkJNI.XBC_Invalid_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsBaudCode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsBaudCode.class + " with value " + swigValue);
  }

  private XsBaudCode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsBaudCode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsBaudCode(String swigName, XsBaudCode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsBaudCode[] swigValues = { XBC_4k8, XBC_9k6, XBC_14k4, XBC_19k2, XBC_28k8, XBC_38k4, XBC_57k6, XBC_76k8, XBC_115k2, XBC_230k4, XBC_460k8, XBC_921k6, XBC_921k6Legacy, XBC_2MegaBaud, XBC_3_5MegaBaud, XBC_4MegaBaud, XBC_Invalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

