
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsByteArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsByteArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsByteArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsByteArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsByteArray(long sz, SWIGTYPE_p_unsigned_char src) {
    this(movelladot_pc_sdkJNI.new_XsByteArray__SWIG_0(sz, SWIGTYPE_p_unsigned_char.getCPtr(src)), true);
  }

  public XsByteArray(long sz) {
    this(movelladot_pc_sdkJNI.new_XsByteArray__SWIG_1(sz), true);
  }

  public XsByteArray() {
    this(movelladot_pc_sdkJNI.new_XsByteArray__SWIG_2(), true);
  }

  public XsByteArray(XsByteArray other) {
    this(movelladot_pc_sdkJNI.new_XsByteArray__SWIG_3(XsByteArray.getCPtr(other), other), true);
  }

  public XsByteArray(SWIGTYPE_p_unsigned_char ref, long sz, XsDataFlags flags) {
    this(movelladot_pc_sdkJNI.new_XsByteArray__SWIG_4(SWIGTYPE_p_unsigned_char.getCPtr(ref), sz, flags.swigValue()), true);
  }

  public XsByteArray(XsString src) {
    this(movelladot_pc_sdkJNI.new_XsByteArray__SWIG_5(XsString.getCPtr(src), src), true);
  }

  public SWIGTYPE_p_unsigned_char data() {
    long cPtr = movelladot_pc_sdkJNI.XsByteArray_data__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public XsString toXsString() {
    return new XsString(movelladot_pc_sdkJNI.XsByteArray_toXsString(swigCPtr, this), true);
  }

  public XsByteArray mid(long start, long count) {
    return new XsByteArray(movelladot_pc_sdkJNI.XsByteArray_mid(swigCPtr, this, start, count), true);
  }

}
