
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsDataPacket {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsDataPacket(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsDataPacket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsDataPacket(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsDataPacket(XsMessage msg) {
    this(movelladot_pc_sdkJNI.new_XsDataPacket__SWIG_0(XsMessage.getCPtr(msg), msg), true);
  }

  public XsDataPacket() {
    this(movelladot_pc_sdkJNI.new_XsDataPacket__SWIG_1(), true);
  }

  public XsDataPacket(XsDataPacket pack) {
    this(movelladot_pc_sdkJNI.new_XsDataPacket__SWIG_2(XsDataPacket.getCPtr(pack), pack), true);
  }

  public void swap(XsDataPacket other) {
    movelladot_pc_sdkJNI.XsDataPacket_swap(swigCPtr, this, XsDataPacket.getCPtr(other), other);
  }

  public void clear(XsDataIdentifier id) {
    movelladot_pc_sdkJNI.XsDataPacket_clear__SWIG_0(swigCPtr, this, id.swigValue());
  }

  public void clear() {
    movelladot_pc_sdkJNI.XsDataPacket_clear__SWIG_1(swigCPtr, this);
  }

  public boolean empty() {
    return movelladot_pc_sdkJNI.XsDataPacket_empty(swigCPtr, this);
  }

  public XsDeviceId deviceId() {
    return new XsDeviceId(movelladot_pc_sdkJNI.XsDataPacket_deviceId(swigCPtr, this), true);
  }

  public int itemCount() {
    return movelladot_pc_sdkJNI.XsDataPacket_itemCount(swigCPtr, this);
  }

  public void setMessage(XsMessage msg) {
    movelladot_pc_sdkJNI.XsDataPacket_setMessage(swigCPtr, this, XsMessage.getCPtr(msg), msg);
  }

  public XsMessage toMessage() {
    return new XsMessage(movelladot_pc_sdkJNI.XsDataPacket_toMessage(swigCPtr, this), true);
  }

  public void setDeviceId(XsDeviceId id) {
    movelladot_pc_sdkJNI.XsDataPacket_setDeviceId(swigCPtr, this, XsDeviceId.getCPtr(id), id);
  }

  public XsDataIdentifier dataFormat(XsDataIdentifier id) {
    return XsDataIdentifier.swigToEnum(movelladot_pc_sdkJNI.XsDataPacket_dataFormat(swigCPtr, this, id.swigValue()));
  }

  public XsUShortVector rawAcceleration() {
    return new XsUShortVector(movelladot_pc_sdkJNI.XsDataPacket_rawAcceleration(swigCPtr, this), true);
  }

  public XsVector rawAccelerationConverted() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_rawAccelerationConverted(swigCPtr, this), true);
  }

  public boolean containsRawAcceleration() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawAcceleration(swigCPtr, this);
  }

  public void setRawAcceleration(XsUShortVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawAcceleration(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public XsUShortVector rawGyroscopeData() {
    return new XsUShortVector(movelladot_pc_sdkJNI.XsDataPacket_rawGyroscopeData(swigCPtr, this), true);
  }

  public XsVector rawGyroscopeDataConverted() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_rawGyroscopeDataConverted(swigCPtr, this), true);
  }

  public boolean containsRawGyroscopeData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawGyroscopeData(swigCPtr, this);
  }

  public void setRawGyroscopeData(XsUShortVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawGyroscopeData(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public XsUShortVector rawGyroscopeTemperatureData() {
    return new XsUShortVector(movelladot_pc_sdkJNI.XsDataPacket_rawGyroscopeTemperatureData(swigCPtr, this), true);
  }

  public XsVector rawGyroscopeTemperatureDataConverted() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_rawGyroscopeTemperatureDataConverted(swigCPtr, this), true);
  }

  public boolean containsRawGyroscopeTemperatureData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawGyroscopeTemperatureData(swigCPtr, this);
  }

  public void setRawGyroscopeTemperatureData(XsUShortVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawGyroscopeTemperatureData(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public XsUShortVector rawMagneticField() {
    return new XsUShortVector(movelladot_pc_sdkJNI.XsDataPacket_rawMagneticField(swigCPtr, this), true);
  }

  public XsVector rawMagneticFieldConverted() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_rawMagneticFieldConverted(swigCPtr, this), true);
  }

  public boolean containsRawMagneticField() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawMagneticField(swigCPtr, this);
  }

  public void setRawMagneticField(XsUShortVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawMagneticField(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public int rawTemperature() {
    return movelladot_pc_sdkJNI.XsDataPacket_rawTemperature(swigCPtr, this);
  }

  public boolean containsRawTemperature() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawTemperature(swigCPtr, this);
  }

  public void setRawTemperature(int temp) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawTemperature(swigCPtr, this, temp);
  }

  public XsScrData rawData() {
    return new XsScrData(movelladot_pc_sdkJNI.XsDataPacket_rawData(swigCPtr, this), true);
  }

  public boolean containsRawData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawData(swigCPtr, this);
  }

  public void setRawData(XsScrData data) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawData(swigCPtr, this, XsScrData.getCPtr(data), data);
  }

  public XsVector velocityIncrement() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_velocityIncrement(swigCPtr, this), true);
  }

  public boolean containsVelocityIncrement() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsVelocityIncrement(swigCPtr, this);
  }

  public void setVelocityIncrement(XsVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setVelocityIncrement(swigCPtr, this, XsVector.getCPtr(vec), vec);
  }

  public XsVector calibratedAcceleration() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_calibratedAcceleration(swigCPtr, this), true);
  }

  public boolean containsCalibratedAcceleration() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsCalibratedAcceleration(swigCPtr, this);
  }

  public void setCalibratedAcceleration(XsVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setCalibratedAcceleration(swigCPtr, this, XsVector.getCPtr(vec), vec);
  }

  public XsQuaternion orientationIncrement() {
    return new XsQuaternion(movelladot_pc_sdkJNI.XsDataPacket_orientationIncrement(swigCPtr, this), true);
  }

  public boolean containsOrientationIncrement() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsOrientationIncrement(swigCPtr, this);
  }

  public void setOrientationIncrement(XsQuaternion quat) {
    movelladot_pc_sdkJNI.XsDataPacket_setOrientationIncrement(swigCPtr, this, XsQuaternion.getCPtr(quat), quat);
  }

  public XsVector calibratedGyroscopeData() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_calibratedGyroscopeData(swigCPtr, this), true);
  }

  public boolean containsCalibratedGyroscopeData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsCalibratedGyroscopeData(swigCPtr, this);
  }

  public void setCalibratedGyroscopeData(XsVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setCalibratedGyroscopeData(swigCPtr, this, XsVector.getCPtr(vec), vec);
  }

  public XsVector calibratedMagneticField() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_calibratedMagneticField(swigCPtr, this), true);
  }

  public boolean containsCalibratedMagneticField() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsCalibratedMagneticField(swigCPtr, this);
  }

  public void setCalibratedMagneticField(XsVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setCalibratedMagneticField(swigCPtr, this, XsVector.getCPtr(vec), vec);
  }

  public XsVector correctedMagneticField() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_correctedMagneticField(swigCPtr, this), true);
  }

  public boolean containsCorrectedMagneticField() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsCorrectedMagneticField(swigCPtr, this);
  }

  public void setCorrectedMagneticField(XsVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setCorrectedMagneticField(swigCPtr, this, XsVector.getCPtr(vec), vec);
  }

  public XsCalibratedData calibratedData() {
    return new XsCalibratedData(movelladot_pc_sdkJNI.XsDataPacket_calibratedData(swigCPtr, this), true);
  }

  public boolean containsCalibratedData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsCalibratedData(swigCPtr, this);
  }

  public void setCalibratedData(XsCalibratedData data) {
    movelladot_pc_sdkJNI.XsDataPacket_setCalibratedData(swigCPtr, this, XsCalibratedData.getCPtr(data), data);
  }

  public XsQuaternion orientationQuaternion(XsDataIdentifier coordinateSystem) {
    return new XsQuaternion(movelladot_pc_sdkJNI.XsDataPacket_orientationQuaternion__SWIG_0(swigCPtr, this, coordinateSystem.swigValue()), true);
  }

  public XsQuaternion orientationQuaternion() {
    return new XsQuaternion(movelladot_pc_sdkJNI.XsDataPacket_orientationQuaternion__SWIG_1(swigCPtr, this), true);
  }

  public void setOrientationQuaternion(XsQuaternion data, XsDataIdentifier coordinateSystem) {
    movelladot_pc_sdkJNI.XsDataPacket_setOrientationQuaternion(swigCPtr, this, XsQuaternion.getCPtr(data), data, coordinateSystem.swigValue());
  }

  public XsEuler orientationEuler(XsDataIdentifier coordinateSystem) {
    return new XsEuler(movelladot_pc_sdkJNI.XsDataPacket_orientationEuler__SWIG_0(swigCPtr, this, coordinateSystem.swigValue()), true);
  }

  public XsEuler orientationEuler() {
    return new XsEuler(movelladot_pc_sdkJNI.XsDataPacket_orientationEuler__SWIG_1(swigCPtr, this), true);
  }

  public void setOrientationEuler(XsEuler data, XsDataIdentifier coordinateSystem) {
    movelladot_pc_sdkJNI.XsDataPacket_setOrientationEuler(swigCPtr, this, XsEuler.getCPtr(data), data, coordinateSystem.swigValue());
  }

  public XsMatrix orientationMatrix(XsDataIdentifier coordinateSystem) {
    return new XsMatrix(movelladot_pc_sdkJNI.XsDataPacket_orientationMatrix__SWIG_0(swigCPtr, this, coordinateSystem.swigValue()), true);
  }

  public XsMatrix orientationMatrix() {
    return new XsMatrix(movelladot_pc_sdkJNI.XsDataPacket_orientationMatrix__SWIG_1(swigCPtr, this), true);
  }

  public void setOrientationMatrix(XsMatrix data, XsDataIdentifier coordinateSystem) {
    movelladot_pc_sdkJNI.XsDataPacket_setOrientationMatrix(swigCPtr, this, XsMatrix.getCPtr(data), data, coordinateSystem.swigValue());
  }

  public boolean containsOrientation() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsOrientation(swigCPtr, this);
  }

  public XsDataIdentifier orientationIdentifier() {
    return XsDataIdentifier.swigToEnum(movelladot_pc_sdkJNI.XsDataPacket_orientationIdentifier(swigCPtr, this));
  }

  public XsDataIdentifier coordinateSystemOrientation() {
    return XsDataIdentifier.swigToEnum(movelladot_pc_sdkJNI.XsDataPacket_coordinateSystemOrientation(swigCPtr, this));
  }

  public XsSdiData sdiData() {
    return new XsSdiData(movelladot_pc_sdkJNI.XsDataPacket_sdiData(swigCPtr, this), true);
  }

  public boolean containsSdiData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsSdiData(swigCPtr, this);
  }

  public void setSdiData(XsSdiData data) {
    movelladot_pc_sdkJNI.XsDataPacket_setSdiData(swigCPtr, this, XsSdiData.getCPtr(data), data);
  }

  public XsGloveData gloveData(XsHandId hand) {
    return new XsGloveData(movelladot_pc_sdkJNI.XsDataPacket_gloveData(swigCPtr, this, hand.swigValue()), true);
  }

  public boolean containsGloveData(XsHandId hand) {
    return movelladot_pc_sdkJNI.XsDataPacket_containsGloveData__SWIG_0(swigCPtr, this, hand.swigValue());
  }

  public boolean containsGloveData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsGloveData__SWIG_1(swigCPtr, this);
  }

  public void setGloveData(XsGloveData data, XsHandId hand) {
    movelladot_pc_sdkJNI.XsDataPacket_setGloveData(swigCPtr, this, XsGloveData.getCPtr(data), data, hand.swigValue());
  }

  public XsDeviceId storedDeviceId() {
    return new XsDeviceId(movelladot_pc_sdkJNI.XsDataPacket_storedDeviceId(swigCPtr, this), true);
  }

  public boolean containsStoredDeviceId() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsStoredDeviceId(swigCPtr, this);
  }

  public void setStoredDeviceId(XsDeviceId data) {
    movelladot_pc_sdkJNI.XsDataPacket_setStoredDeviceId(swigCPtr, this, XsDeviceId.getCPtr(data), data);
  }

  public int storedLocationId() {
    return movelladot_pc_sdkJNI.XsDataPacket_storedLocationId(swigCPtr, this);
  }

  public boolean containsStoredLocationId() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsStoredLocationId(swigCPtr, this);
  }

  public void setStoredLocationId(int data) {
    movelladot_pc_sdkJNI.XsDataPacket_setStoredLocationId(swigCPtr, this, data);
  }

  public long status() {
    return movelladot_pc_sdkJNI.XsDataPacket_status(swigCPtr, this);
  }

  public boolean containsStatus() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsStatus(swigCPtr, this);
  }

  public boolean containsDetailedStatus() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsDetailedStatus(swigCPtr, this);
  }

  public void setStatus(long data) {
    movelladot_pc_sdkJNI.XsDataPacket_setStatus(swigCPtr, this, data);
  }

  public void setStatusByte(short data) {
    movelladot_pc_sdkJNI.XsDataPacket_setStatusByte(swigCPtr, this, data);
  }

  public short packetCounter8() {
    return movelladot_pc_sdkJNI.XsDataPacket_packetCounter8(swigCPtr, this);
  }

  public boolean containsPacketCounter8() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsPacketCounter8(swigCPtr, this);
  }

  public void setPacketCounter8(short counter) {
    movelladot_pc_sdkJNI.XsDataPacket_setPacketCounter8(swigCPtr, this, counter);
  }

  public int packetCounter() {
    return movelladot_pc_sdkJNI.XsDataPacket_packetCounter(swigCPtr, this);
  }

  public boolean containsPacketCounter() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsPacketCounter(swigCPtr, this);
  }

  public void setPacketCounter(int counter) {
    movelladot_pc_sdkJNI.XsDataPacket_setPacketCounter(swigCPtr, this, counter);
  }

  public long packetCounter32() {
    return movelladot_pc_sdkJNI.XsDataPacket_packetCounter32(swigCPtr, this);
  }

  public boolean containsPacketCounter32() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsPacketCounter32(swigCPtr, this);
  }

  public void setPacketCounter32(long counter) {
    movelladot_pc_sdkJNI.XsDataPacket_setPacketCounter32(swigCPtr, this, counter);
  }

  public long sampleTimeFine() {
    return movelladot_pc_sdkJNI.XsDataPacket_sampleTimeFine(swigCPtr, this);
  }

  public boolean containsSampleTimeFine() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsSampleTimeFine(swigCPtr, this);
  }

  public void setSampleTimeFine(long counter) {
    movelladot_pc_sdkJNI.XsDataPacket_setSampleTimeFine(swigCPtr, this, counter);
  }

  public long sampleTimeCoarse() {
    return movelladot_pc_sdkJNI.XsDataPacket_sampleTimeCoarse(swigCPtr, this);
  }

  public boolean containsSampleTimeCoarse() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsSampleTimeCoarse(swigCPtr, this);
  }

  public void setSampleTimeCoarse(long counter) {
    movelladot_pc_sdkJNI.XsDataPacket_setSampleTimeCoarse(swigCPtr, this, counter);
  }

  public java.math.BigInteger sampleTime64() {
    return movelladot_pc_sdkJNI.XsDataPacket_sampleTime64(swigCPtr, this);
  }

  public boolean containsSampleTime64() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsSampleTime64(swigCPtr, this);
  }

  public void setSampleTime64(java.math.BigInteger counter) {
    movelladot_pc_sdkJNI.XsDataPacket_setSampleTime64(swigCPtr, this, counter);
  }

  public XsVector freeAcceleration() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_freeAcceleration(swigCPtr, this), true);
  }

  public boolean containsFreeAcceleration() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsFreeAcceleration(swigCPtr, this);
  }

  public void setFreeAcceleration(XsVector g) {
    movelladot_pc_sdkJNI.XsDataPacket_setFreeAcceleration(swigCPtr, this, XsVector.getCPtr(g), g);
  }

  public double temperature() {
    return movelladot_pc_sdkJNI.XsDataPacket_temperature(swigCPtr, this);
  }

  public boolean containsTemperature() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsTemperature(swigCPtr, this);
  }

  public void setTemperature(double temperature) {
    movelladot_pc_sdkJNI.XsDataPacket_setTemperature(swigCPtr, this, temperature);
  }

  public XsPressure pressure() {
    return new XsPressure(movelladot_pc_sdkJNI.XsDataPacket_pressure(swigCPtr, this), true);
  }

  public boolean containsPressure() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsPressure(swigCPtr, this);
  }

  public boolean containsPressureAge() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsPressureAge(swigCPtr, this);
  }

  public void setPressure(XsPressure data) {
    movelladot_pc_sdkJNI.XsDataPacket_setPressure(swigCPtr, this, XsPressure.getCPtr(data), data);
  }

  public XsAnalogInData analogIn1Data() {
    return new XsAnalogInData(movelladot_pc_sdkJNI.XsDataPacket_analogIn1Data(swigCPtr, this), true);
  }

  public boolean containsAnalogIn1Data() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsAnalogIn1Data(swigCPtr, this);
  }

  public void setAnalogIn1Data(XsAnalogInData data) {
    movelladot_pc_sdkJNI.XsDataPacket_setAnalogIn1Data(swigCPtr, this, XsAnalogInData.getCPtr(data), data);
  }

  public XsAnalogInData analogIn2Data() {
    return new XsAnalogInData(movelladot_pc_sdkJNI.XsDataPacket_analogIn2Data(swigCPtr, this), true);
  }

  public boolean containsAnalogIn2Data() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsAnalogIn2Data(swigCPtr, this);
  }

  public void setAnalogIn2Data(XsAnalogInData data) {
    movelladot_pc_sdkJNI.XsDataPacket_setAnalogIn2Data(swigCPtr, this, XsAnalogInData.getCPtr(data), data);
  }

  public XsVector positionLLA() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_positionLLA(swigCPtr, this), true);
  }

  public boolean containsPositionLLA() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsPositionLLA(swigCPtr, this);
  }

  public void setPositionLLA(XsVector data) {
    movelladot_pc_sdkJNI.XsDataPacket_setPositionLLA(swigCPtr, this, XsVector.getCPtr(data), data);
  }

  public XsVector latitudeLongitude() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_latitudeLongitude(swigCPtr, this), true);
  }

  public boolean containsLatitudeLongitude() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsLatitudeLongitude(swigCPtr, this);
  }

  public void setLatitudeLongitude(XsVector data) {
    movelladot_pc_sdkJNI.XsDataPacket_setLatitudeLongitude(swigCPtr, this, XsVector.getCPtr(data), data);
  }

  public double altitude() {
    return movelladot_pc_sdkJNI.XsDataPacket_altitude(swigCPtr, this);
  }

  public boolean containsAltitude() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsAltitude(swigCPtr, this);
  }

  public void setAltitude(double data) {
    movelladot_pc_sdkJNI.XsDataPacket_setAltitude(swigCPtr, this, data);
  }

  public double altitudeMsl() {
    return movelladot_pc_sdkJNI.XsDataPacket_altitudeMsl(swigCPtr, this);
  }

  public boolean containsAltitudeMsl() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsAltitudeMsl(swigCPtr, this);
  }

  public void setAltitudeMsl(double data) {
    movelladot_pc_sdkJNI.XsDataPacket_setAltitudeMsl(swigCPtr, this, data);
  }

  public XsVector velocity(XsDataIdentifier coordinateSystem) {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_velocity__SWIG_0(swigCPtr, this, coordinateSystem.swigValue()), true);
  }

  public XsVector velocity() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_velocity__SWIG_1(swigCPtr, this), true);
  }

  public boolean containsVelocity() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsVelocity(swigCPtr, this);
  }

  public void setVelocity(XsVector data, XsDataIdentifier coordinateSystem) {
    movelladot_pc_sdkJNI.XsDataPacket_setVelocity(swigCPtr, this, XsVector.getCPtr(data), data, coordinateSystem.swigValue());
  }

  public XsDataIdentifier velocityIdentifier() {
    return XsDataIdentifier.swigToEnum(movelladot_pc_sdkJNI.XsDataPacket_velocityIdentifier(swigCPtr, this));
  }

  public XsDataIdentifier coordinateSystemVelocity() {
    return XsDataIdentifier.swigToEnum(movelladot_pc_sdkJNI.XsDataPacket_coordinateSystemVelocity(swigCPtr, this));
  }

  public XsTimeInfo utcTime() {
    return new XsTimeInfo(movelladot_pc_sdkJNI.XsDataPacket_utcTime(swigCPtr, this), true);
  }

  public boolean containsUtcTime() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsUtcTime(swigCPtr, this);
  }

  public void setUtcTime(XsTimeInfo data) {
    movelladot_pc_sdkJNI.XsDataPacket_setUtcTime(swigCPtr, this, XsTimeInfo.getCPtr(data), data);
  }

  public XsRange frameRange() {
    return new XsRange(movelladot_pc_sdkJNI.XsDataPacket_frameRange(swigCPtr, this), true);
  }

  public boolean containsFrameRange() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsFrameRange(swigCPtr, this);
  }

  public void setFrameRange(XsRange r) {
    movelladot_pc_sdkJNI.XsDataPacket_setFrameRange(swigCPtr, this, XsRange.getCPtr(r), r);
  }

  public int rssi() {
    return movelladot_pc_sdkJNI.XsDataPacket_rssi(swigCPtr, this);
  }

  public boolean containsRssi() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRssi(swigCPtr, this);
  }

  public void setRssi(int r) {
    movelladot_pc_sdkJNI.XsDataPacket_setRssi(swigCPtr, this, r);
  }

  public XsRawGnssPvtData rawGnssPvtData() {
    return new XsRawGnssPvtData(movelladot_pc_sdkJNI.XsDataPacket_rawGnssPvtData(swigCPtr, this), true);
  }

  public boolean containsRawGnssPvtData() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawGnssPvtData(swigCPtr, this);
  }

  public void setRawGnssPvtData(XsRawGnssPvtData raw) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawGnssPvtData(swigCPtr, this, XsRawGnssPvtData.getCPtr(raw), raw);
  }

  public short gnssAge() {
    return movelladot_pc_sdkJNI.XsDataPacket_gnssAge(swigCPtr, this);
  }

  public boolean containsGnssAge() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsGnssAge(swigCPtr, this);
  }

  public void setGnssAge(short age) {
    movelladot_pc_sdkJNI.XsDataPacket_setGnssAge(swigCPtr, this, age);
  }

  public XsRawGnssSatInfo rawGnssSatInfo() {
    return new XsRawGnssSatInfo(movelladot_pc_sdkJNI.XsDataPacket_rawGnssSatInfo(swigCPtr, this), true);
  }

  public boolean containsRawGnssSatInfo() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawGnssSatInfo(swigCPtr, this);
  }

  public void setRawGnssSatInfo(XsRawGnssSatInfo data) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawGnssSatInfo(swigCPtr, this, XsRawGnssSatInfo.getCPtr(data), data);
  }

  public long gnssPvtPulse() {
    return movelladot_pc_sdkJNI.XsDataPacket_gnssPvtPulse(swigCPtr, this);
  }

  public boolean containsGnssPvtPulse() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsGnssPvtPulse(swigCPtr, this);
  }

  public void setGnssPvtPulse(long counter) {
    movelladot_pc_sdkJNI.XsDataPacket_setGnssPvtPulse(swigCPtr, this, counter);
  }

  public XsSnapshot fullSnapshot() {
    return new XsSnapshot(movelladot_pc_sdkJNI.XsDataPacket_fullSnapshot(swigCPtr, this), true);
  }

  public boolean containsFullSnapshot() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsFullSnapshot(swigCPtr, this);
  }

  public void setFullSnapshot(XsSnapshot data, boolean retransmission) {
    movelladot_pc_sdkJNI.XsDataPacket_setFullSnapshot(swigCPtr, this, XsSnapshot.getCPtr(data), data, retransmission);
  }

  public XsSnapshot awindaSnapshot() {
    return new XsSnapshot(movelladot_pc_sdkJNI.XsDataPacket_awindaSnapshot(swigCPtr, this), true);
  }

  public boolean containsAwindaSnapshot() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsAwindaSnapshot(swigCPtr, this);
  }

  public void setAwindaSnapshot(XsSnapshot raw, boolean retransmission) {
    movelladot_pc_sdkJNI.XsDataPacket_setAwindaSnapshot(swigCPtr, this, XsSnapshot.getCPtr(raw), raw, retransmission);
  }

  public boolean isAwindaSnapshotARetransmission() {
    return movelladot_pc_sdkJNI.XsDataPacket_isAwindaSnapshotARetransmission(swigCPtr, this);
  }

  public XsGloveSnapshot gloveSnapshot(XsHandId hand) {
    return new XsGloveSnapshot(movelladot_pc_sdkJNI.XsDataPacket_gloveSnapshot(swigCPtr, this, hand.swigValue()), true);
  }

  public boolean containsGloveSnapshot(XsHandId hand) {
    return movelladot_pc_sdkJNI.XsDataPacket_containsGloveSnapshot__SWIG_0(swigCPtr, this, hand.swigValue());
  }

  public boolean containsGloveSnapshot() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsGloveSnapshot__SWIG_1(swigCPtr, this);
  }

  public void setGloveSnapshot(XsGloveSnapshot data, boolean retransmission, XsHandId hand) {
    movelladot_pc_sdkJNI.XsDataPacket_setGloveSnapshot(swigCPtr, this, XsGloveSnapshot.getCPtr(data), data, retransmission, hand.swigValue());
  }

  public XsDataPacket merge(XsDataPacket other, boolean overwrite) {
    return new XsDataPacket(movelladot_pc_sdkJNI.XsDataPacket_merge__SWIG_0(swigCPtr, this, XsDataPacket.getCPtr(other), other, overwrite), false);
  }

  public XsDataPacket merge(XsDataPacket other) {
    return new XsDataPacket(movelladot_pc_sdkJNI.XsDataPacket_merge__SWIG_1(swigCPtr, this, XsDataPacket.getCPtr(other), other), false);
  }

  public void setTimeOfArrival(XsTimeStamp t) {
    movelladot_pc_sdkJNI.XsDataPacket_setTimeOfArrival(swigCPtr, this, XsTimeStamp.getCPtr(t), t);
  }

  public XsTimeStamp timeOfArrival() {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsDataPacket_timeOfArrival(swigCPtr, this), true);
  }

  public void setEstimatedTimeOfSampling(XsTimeStamp t) {
    movelladot_pc_sdkJNI.XsDataPacket_setEstimatedTimeOfSampling(swigCPtr, this, XsTimeStamp.getCPtr(t), t);
  }

  public XsTimeStamp estimatedTimeOfSampling() {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsDataPacket_estimatedTimeOfSampling(swigCPtr, this), true);
  }

  public void setPacketId(long t) {
    movelladot_pc_sdkJNI.XsDataPacket_setPacketId(swigCPtr, this, t);
  }

  public long packetId() {
    return movelladot_pc_sdkJNI.XsDataPacket_packetId(swigCPtr, this);
  }

  public void setTriggerIndication(XsDataIdentifier triggerId, XsTriggerIndicationData triggerIndicationData) {
    movelladot_pc_sdkJNI.XsDataPacket_setTriggerIndication(swigCPtr, this, triggerId.swigValue(), XsTriggerIndicationData.getCPtr(triggerIndicationData), triggerIndicationData);
  }

  public boolean containsTriggerIndication(XsDataIdentifier triggerId) {
    return movelladot_pc_sdkJNI.XsDataPacket_containsTriggerIndication(swigCPtr, this, triggerId.swigValue());
  }

  public XsTriggerIndicationData triggerIndication(XsDataIdentifier triggerId) {
    return new XsTriggerIndicationData(movelladot_pc_sdkJNI.XsDataPacket_triggerIndication(swigCPtr, this, triggerId.swigValue()), true);
  }

  public XsByteArray rawBlob() {
    return new XsByteArray(movelladot_pc_sdkJNI.XsDataPacket_rawBlob(swigCPtr, this), true);
  }

  public boolean containsRawBlob() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRawBlob(swigCPtr, this);
  }

  public void setRawBlob(XsByteArray data) {
    movelladot_pc_sdkJNI.XsDataPacket_setRawBlob(swigCPtr, this, XsByteArray.getCPtr(data), data);
  }

  public XsVector accelerationHR() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_accelerationHR(swigCPtr, this), true);
  }

  public boolean containsAccelerationHR() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsAccelerationHR(swigCPtr, this);
  }

  public void setAccelerationHR(XsVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setAccelerationHR(swigCPtr, this, XsVector.getCPtr(vec), vec);
  }

  public XsVector rateOfTurnHR() {
    return new XsVector(movelladot_pc_sdkJNI.XsDataPacket_rateOfTurnHR(swigCPtr, this), true);
  }

  public boolean containsRateOfTurnHR() {
    return movelladot_pc_sdkJNI.XsDataPacket_containsRateOfTurnHR(swigCPtr, this);
  }

  public void setRateOfTurnHR(XsVector vec) {
    movelladot_pc_sdkJNI.XsDataPacket_setRateOfTurnHR(swigCPtr, this, XsVector.getCPtr(vec), vec);
  }

  public void setM_deviceId(XsDeviceId value) {
    movelladot_pc_sdkJNI.XsDataPacket_m_deviceId_set(swigCPtr, this, XsDeviceId.getCPtr(value), value);
  }

  public XsDeviceId getM_deviceId() {
    long cPtr = movelladot_pc_sdkJNI.XsDataPacket_m_deviceId_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsDeviceId(cPtr, false);
  }

  public void setM_toa(XsTimeStamp value) {
    movelladot_pc_sdkJNI.XsDataPacket_m_toa_set(swigCPtr, this, XsTimeStamp.getCPtr(value), value);
  }

  public XsTimeStamp getM_toa() {
    long cPtr = movelladot_pc_sdkJNI.XsDataPacket_m_toa_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsTimeStamp(cPtr, false);
  }

  public void setM_packetId(long value) {
    movelladot_pc_sdkJNI.XsDataPacket_m_packetId_set(swigCPtr, this, value);
  }

  public long getM_packetId() {
    return movelladot_pc_sdkJNI.XsDataPacket_m_packetId_get(swigCPtr, this);
  }

  public void setM_etos(XsTimeStamp value) {
    movelladot_pc_sdkJNI.XsDataPacket_m_etos_set(swigCPtr, this, XsTimeStamp.getCPtr(value), value);
  }

  public XsTimeStamp getM_etos() {
    long cPtr = movelladot_pc_sdkJNI.XsDataPacket_m_etos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsTimeStamp(cPtr, false);
  }

}
