
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsDataIdentifier {
  public final static XsDataIdentifier XDI_None = new XsDataIdentifier("XDI_None", movelladot_pc_sdkJNI.XDI_None_get());
  public final static XsDataIdentifier XDI_TypeMask = new XsDataIdentifier("XDI_TypeMask", movelladot_pc_sdkJNI.XDI_TypeMask_get());
  public final static XsDataIdentifier XDI_FullTypeMask = new XsDataIdentifier("XDI_FullTypeMask", movelladot_pc_sdkJNI.XDI_FullTypeMask_get());
  public final static XsDataIdentifier XDI_FullMask = new XsDataIdentifier("XDI_FullMask", movelladot_pc_sdkJNI.XDI_FullMask_get());
  public final static XsDataIdentifier XDI_FormatMask = new XsDataIdentifier("XDI_FormatMask", movelladot_pc_sdkJNI.XDI_FormatMask_get());
  public final static XsDataIdentifier XDI_DataFormatMask = new XsDataIdentifier("XDI_DataFormatMask", movelladot_pc_sdkJNI.XDI_DataFormatMask_get());
  public final static XsDataIdentifier XDI_SubFormatMask = new XsDataIdentifier("XDI_SubFormatMask", movelladot_pc_sdkJNI.XDI_SubFormatMask_get());
  public final static XsDataIdentifier XDI_SubFormatFloat = new XsDataIdentifier("XDI_SubFormatFloat", movelladot_pc_sdkJNI.XDI_SubFormatFloat_get());
  public final static XsDataIdentifier XDI_SubFormatFp1220 = new XsDataIdentifier("XDI_SubFormatFp1220", movelladot_pc_sdkJNI.XDI_SubFormatFp1220_get());
  public final static XsDataIdentifier XDI_SubFormatFp1632 = new XsDataIdentifier("XDI_SubFormatFp1632", movelladot_pc_sdkJNI.XDI_SubFormatFp1632_get());
  public final static XsDataIdentifier XDI_SubFormatDouble = new XsDataIdentifier("XDI_SubFormatDouble", movelladot_pc_sdkJNI.XDI_SubFormatDouble_get());
  public final static XsDataIdentifier XDI_SubFormatLeft = new XsDataIdentifier("XDI_SubFormatLeft", movelladot_pc_sdkJNI.XDI_SubFormatLeft_get());
  public final static XsDataIdentifier XDI_SubFormatRight = new XsDataIdentifier("XDI_SubFormatRight", movelladot_pc_sdkJNI.XDI_SubFormatRight_get());
  public final static XsDataIdentifier XDI_TemperatureGroup = new XsDataIdentifier("XDI_TemperatureGroup", movelladot_pc_sdkJNI.XDI_TemperatureGroup_get());
  public final static XsDataIdentifier XDI_Temperature = new XsDataIdentifier("XDI_Temperature", movelladot_pc_sdkJNI.XDI_Temperature_get());
  public final static XsDataIdentifier XDI_TimestampGroup = new XsDataIdentifier("XDI_TimestampGroup", movelladot_pc_sdkJNI.XDI_TimestampGroup_get());
  public final static XsDataIdentifier XDI_UtcTime = new XsDataIdentifier("XDI_UtcTime", movelladot_pc_sdkJNI.XDI_UtcTime_get());
  public final static XsDataIdentifier XDI_PacketCounter = new XsDataIdentifier("XDI_PacketCounter", movelladot_pc_sdkJNI.XDI_PacketCounter_get());
  public final static XsDataIdentifier XDI_Itow = new XsDataIdentifier("XDI_Itow", movelladot_pc_sdkJNI.XDI_Itow_get());
  public final static XsDataIdentifier XDI_GnssAge = new XsDataIdentifier("XDI_GnssAge", movelladot_pc_sdkJNI.XDI_GnssAge_get());
  public final static XsDataIdentifier XDI_PressureAge = new XsDataIdentifier("XDI_PressureAge", movelladot_pc_sdkJNI.XDI_PressureAge_get());
  public final static XsDataIdentifier XDI_SampleTimeFine = new XsDataIdentifier("XDI_SampleTimeFine", movelladot_pc_sdkJNI.XDI_SampleTimeFine_get());
  public final static XsDataIdentifier XDI_SampleTimeCoarse = new XsDataIdentifier("XDI_SampleTimeCoarse", movelladot_pc_sdkJNI.XDI_SampleTimeCoarse_get());
  public final static XsDataIdentifier XDI_FrameRange = new XsDataIdentifier("XDI_FrameRange", movelladot_pc_sdkJNI.XDI_FrameRange_get());
  public final static XsDataIdentifier XDI_PacketCounter8 = new XsDataIdentifier("XDI_PacketCounter8", movelladot_pc_sdkJNI.XDI_PacketCounter8_get());
  public final static XsDataIdentifier XDI_SampleTime64 = new XsDataIdentifier("XDI_SampleTime64", movelladot_pc_sdkJNI.XDI_SampleTime64_get());
  public final static XsDataIdentifier XDI_PacketCounter32 = new XsDataIdentifier("XDI_PacketCounter32", movelladot_pc_sdkJNI.XDI_PacketCounter32_get());
  public final static XsDataIdentifier XDI_OrientationGroup = new XsDataIdentifier("XDI_OrientationGroup", movelladot_pc_sdkJNI.XDI_OrientationGroup_get());
  public final static XsDataIdentifier XDI_CoordSysMask = new XsDataIdentifier("XDI_CoordSysMask", movelladot_pc_sdkJNI.XDI_CoordSysMask_get());
  public final static XsDataIdentifier XDI_CoordSysEnu = new XsDataIdentifier("XDI_CoordSysEnu", movelladot_pc_sdkJNI.XDI_CoordSysEnu_get());
  public final static XsDataIdentifier XDI_CoordSysNed = new XsDataIdentifier("XDI_CoordSysNed", movelladot_pc_sdkJNI.XDI_CoordSysNed_get());
  public final static XsDataIdentifier XDI_CoordSysNwu = new XsDataIdentifier("XDI_CoordSysNwu", movelladot_pc_sdkJNI.XDI_CoordSysNwu_get());
  public final static XsDataIdentifier XDI_Quaternion = new XsDataIdentifier("XDI_Quaternion", movelladot_pc_sdkJNI.XDI_Quaternion_get());
  public final static XsDataIdentifier XDI_RotationMatrix = new XsDataIdentifier("XDI_RotationMatrix", movelladot_pc_sdkJNI.XDI_RotationMatrix_get());
  public final static XsDataIdentifier XDI_EulerAngles = new XsDataIdentifier("XDI_EulerAngles", movelladot_pc_sdkJNI.XDI_EulerAngles_get());
  public final static XsDataIdentifier XDI_PressureGroup = new XsDataIdentifier("XDI_PressureGroup", movelladot_pc_sdkJNI.XDI_PressureGroup_get());
  public final static XsDataIdentifier XDI_BaroPressure = new XsDataIdentifier("XDI_BaroPressure", movelladot_pc_sdkJNI.XDI_BaroPressure_get());
  public final static XsDataIdentifier XDI_AccelerationGroup = new XsDataIdentifier("XDI_AccelerationGroup", movelladot_pc_sdkJNI.XDI_AccelerationGroup_get());
  public final static XsDataIdentifier XDI_DeltaV = new XsDataIdentifier("XDI_DeltaV", movelladot_pc_sdkJNI.XDI_DeltaV_get());
  public final static XsDataIdentifier XDI_Acceleration = new XsDataIdentifier("XDI_Acceleration", movelladot_pc_sdkJNI.XDI_Acceleration_get());
  public final static XsDataIdentifier XDI_FreeAcceleration = new XsDataIdentifier("XDI_FreeAcceleration", movelladot_pc_sdkJNI.XDI_FreeAcceleration_get());
  public final static XsDataIdentifier XDI_AccelerationHR = new XsDataIdentifier("XDI_AccelerationHR", movelladot_pc_sdkJNI.XDI_AccelerationHR_get());
  public final static XsDataIdentifier XDI_IndicationGroup = new XsDataIdentifier("XDI_IndicationGroup", movelladot_pc_sdkJNI.XDI_IndicationGroup_get());
  public final static XsDataIdentifier XDI_TriggerIn1 = new XsDataIdentifier("XDI_TriggerIn1", movelladot_pc_sdkJNI.XDI_TriggerIn1_get());
  public final static XsDataIdentifier XDI_TriggerIn2 = new XsDataIdentifier("XDI_TriggerIn2", movelladot_pc_sdkJNI.XDI_TriggerIn2_get());
  public final static XsDataIdentifier XDI_TriggerIn3 = new XsDataIdentifier("XDI_TriggerIn3", movelladot_pc_sdkJNI.XDI_TriggerIn3_get());
  public final static XsDataIdentifier XDI_PositionGroup = new XsDataIdentifier("XDI_PositionGroup", movelladot_pc_sdkJNI.XDI_PositionGroup_get());
  public final static XsDataIdentifier XDI_AltitudeMsl = new XsDataIdentifier("XDI_AltitudeMsl", movelladot_pc_sdkJNI.XDI_AltitudeMsl_get());
  public final static XsDataIdentifier XDI_AltitudeEllipsoid = new XsDataIdentifier("XDI_AltitudeEllipsoid", movelladot_pc_sdkJNI.XDI_AltitudeEllipsoid_get());
  public final static XsDataIdentifier XDI_PositionEcef = new XsDataIdentifier("XDI_PositionEcef", movelladot_pc_sdkJNI.XDI_PositionEcef_get());
  public final static XsDataIdentifier XDI_LatLon = new XsDataIdentifier("XDI_LatLon", movelladot_pc_sdkJNI.XDI_LatLon_get());
  public final static XsDataIdentifier XDI_GnssGroup = new XsDataIdentifier("XDI_GnssGroup", movelladot_pc_sdkJNI.XDI_GnssGroup_get());
  public final static XsDataIdentifier XDI_GnssPvtData = new XsDataIdentifier("XDI_GnssPvtData", movelladot_pc_sdkJNI.XDI_GnssPvtData_get());
  public final static XsDataIdentifier XDI_GnssSatInfo = new XsDataIdentifier("XDI_GnssSatInfo", movelladot_pc_sdkJNI.XDI_GnssSatInfo_get());
  public final static XsDataIdentifier XDI_GnssPvtPulse = new XsDataIdentifier("XDI_GnssPvtPulse", movelladot_pc_sdkJNI.XDI_GnssPvtPulse_get());
  public final static XsDataIdentifier XDI_AngularVelocityGroup = new XsDataIdentifier("XDI_AngularVelocityGroup", movelladot_pc_sdkJNI.XDI_AngularVelocityGroup_get());
  public final static XsDataIdentifier XDI_RateOfTurn = new XsDataIdentifier("XDI_RateOfTurn", movelladot_pc_sdkJNI.XDI_RateOfTurn_get());
  public final static XsDataIdentifier XDI_DeltaQ = new XsDataIdentifier("XDI_DeltaQ", movelladot_pc_sdkJNI.XDI_DeltaQ_get());
  public final static XsDataIdentifier XDI_RateOfTurnHR = new XsDataIdentifier("XDI_RateOfTurnHR", movelladot_pc_sdkJNI.XDI_RateOfTurnHR_get());
  public final static XsDataIdentifier XDI_RawSensorGroup = new XsDataIdentifier("XDI_RawSensorGroup", movelladot_pc_sdkJNI.XDI_RawSensorGroup_get());
  public final static XsDataIdentifier XDI_RawUnsigned = new XsDataIdentifier("XDI_RawUnsigned", movelladot_pc_sdkJNI.XDI_RawUnsigned_get());
  public final static XsDataIdentifier XDI_RawSigned = new XsDataIdentifier("XDI_RawSigned", movelladot_pc_sdkJNI.XDI_RawSigned_get());
  public final static XsDataIdentifier XDI_RawAccGyrMagTemp = new XsDataIdentifier("XDI_RawAccGyrMagTemp", movelladot_pc_sdkJNI.XDI_RawAccGyrMagTemp_get());
  public final static XsDataIdentifier XDI_RawGyroTemp = new XsDataIdentifier("XDI_RawGyroTemp", movelladot_pc_sdkJNI.XDI_RawGyroTemp_get());
  public final static XsDataIdentifier XDI_RawAcc = new XsDataIdentifier("XDI_RawAcc", movelladot_pc_sdkJNI.XDI_RawAcc_get());
  public final static XsDataIdentifier XDI_RawGyr = new XsDataIdentifier("XDI_RawGyr", movelladot_pc_sdkJNI.XDI_RawGyr_get());
  public final static XsDataIdentifier XDI_RawMag = new XsDataIdentifier("XDI_RawMag", movelladot_pc_sdkJNI.XDI_RawMag_get());
  public final static XsDataIdentifier XDI_RawDeltaQ = new XsDataIdentifier("XDI_RawDeltaQ", movelladot_pc_sdkJNI.XDI_RawDeltaQ_get());
  public final static XsDataIdentifier XDI_RawDeltaV = new XsDataIdentifier("XDI_RawDeltaV", movelladot_pc_sdkJNI.XDI_RawDeltaV_get());
  public final static XsDataIdentifier XDI_RawBlob = new XsDataIdentifier("XDI_RawBlob", movelladot_pc_sdkJNI.XDI_RawBlob_get());
  public final static XsDataIdentifier XDI_AnalogInGroup = new XsDataIdentifier("XDI_AnalogInGroup", movelladot_pc_sdkJNI.XDI_AnalogInGroup_get());
  public final static XsDataIdentifier XDI_AnalogIn1 = new XsDataIdentifier("XDI_AnalogIn1", movelladot_pc_sdkJNI.XDI_AnalogIn1_get());
  public final static XsDataIdentifier XDI_AnalogIn2 = new XsDataIdentifier("XDI_AnalogIn2", movelladot_pc_sdkJNI.XDI_AnalogIn2_get());
  public final static XsDataIdentifier XDI_MagneticGroup = new XsDataIdentifier("XDI_MagneticGroup", movelladot_pc_sdkJNI.XDI_MagneticGroup_get());
  public final static XsDataIdentifier XDI_MagneticField = new XsDataIdentifier("XDI_MagneticField", movelladot_pc_sdkJNI.XDI_MagneticField_get());
  public final static XsDataIdentifier XDI_MagneticFieldCorrected = new XsDataIdentifier("XDI_MagneticFieldCorrected", movelladot_pc_sdkJNI.XDI_MagneticFieldCorrected_get());
  public final static XsDataIdentifier XDI_SnapshotGroup = new XsDataIdentifier("XDI_SnapshotGroup", movelladot_pc_sdkJNI.XDI_SnapshotGroup_get());
  public final static XsDataIdentifier XDI_RetransmissionMask = new XsDataIdentifier("XDI_RetransmissionMask", movelladot_pc_sdkJNI.XDI_RetransmissionMask_get());
  public final static XsDataIdentifier XDI_RetransmissionFlag = new XsDataIdentifier("XDI_RetransmissionFlag", movelladot_pc_sdkJNI.XDI_RetransmissionFlag_get());
  public final static XsDataIdentifier XDI_AwindaSnapshot = new XsDataIdentifier("XDI_AwindaSnapshot", movelladot_pc_sdkJNI.XDI_AwindaSnapshot_get());
  public final static XsDataIdentifier XDI_FullSnapshot = new XsDataIdentifier("XDI_FullSnapshot", movelladot_pc_sdkJNI.XDI_FullSnapshot_get());
  public final static XsDataIdentifier XDI_GloveSnapshotLeft = new XsDataIdentifier("XDI_GloveSnapshotLeft", movelladot_pc_sdkJNI.XDI_GloveSnapshotLeft_get());
  public final static XsDataIdentifier XDI_GloveSnapshotRight = new XsDataIdentifier("XDI_GloveSnapshotRight", movelladot_pc_sdkJNI.XDI_GloveSnapshotRight_get());
  public final static XsDataIdentifier XDI_GloveDataGroup = new XsDataIdentifier("XDI_GloveDataGroup", movelladot_pc_sdkJNI.XDI_GloveDataGroup_get());
  public final static XsDataIdentifier XDI_GloveDataLeft = new XsDataIdentifier("XDI_GloveDataLeft", movelladot_pc_sdkJNI.XDI_GloveDataLeft_get());
  public final static XsDataIdentifier XDI_GloveDataRight = new XsDataIdentifier("XDI_GloveDataRight", movelladot_pc_sdkJNI.XDI_GloveDataRight_get());
  public final static XsDataIdentifier XDI_VelocityGroup = new XsDataIdentifier("XDI_VelocityGroup", movelladot_pc_sdkJNI.XDI_VelocityGroup_get());
  public final static XsDataIdentifier XDI_VelocityXYZ = new XsDataIdentifier("XDI_VelocityXYZ", movelladot_pc_sdkJNI.XDI_VelocityXYZ_get());
  public final static XsDataIdentifier XDI_StatusGroup = new XsDataIdentifier("XDI_StatusGroup", movelladot_pc_sdkJNI.XDI_StatusGroup_get());
  public final static XsDataIdentifier XDI_StatusByte = new XsDataIdentifier("XDI_StatusByte", movelladot_pc_sdkJNI.XDI_StatusByte_get());
  public final static XsDataIdentifier XDI_StatusWord = new XsDataIdentifier("XDI_StatusWord", movelladot_pc_sdkJNI.XDI_StatusWord_get());
  public final static XsDataIdentifier XDI_Rssi = new XsDataIdentifier("XDI_Rssi", movelladot_pc_sdkJNI.XDI_Rssi_get());
  public final static XsDataIdentifier XDI_DeviceId = new XsDataIdentifier("XDI_DeviceId", movelladot_pc_sdkJNI.XDI_DeviceId_get());
  public final static XsDataIdentifier XDI_LocationId = new XsDataIdentifier("XDI_LocationId", movelladot_pc_sdkJNI.XDI_LocationId_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsDataIdentifier swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsDataIdentifier.class + " with value " + swigValue);
  }

  private XsDataIdentifier(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsDataIdentifier(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsDataIdentifier(String swigName, XsDataIdentifier swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsDataIdentifier[] swigValues = { XDI_None, XDI_TypeMask, XDI_FullTypeMask, XDI_FullMask, XDI_FormatMask, XDI_DataFormatMask, XDI_SubFormatMask, XDI_SubFormatFloat, XDI_SubFormatFp1220, XDI_SubFormatFp1632, XDI_SubFormatDouble, XDI_SubFormatLeft, XDI_SubFormatRight, XDI_TemperatureGroup, XDI_Temperature, XDI_TimestampGroup, XDI_UtcTime, XDI_PacketCounter, XDI_Itow, XDI_GnssAge, XDI_PressureAge, XDI_SampleTimeFine, XDI_SampleTimeCoarse, XDI_FrameRange, XDI_PacketCounter8, XDI_SampleTime64, XDI_PacketCounter32, XDI_OrientationGroup, XDI_CoordSysMask, XDI_CoordSysEnu, XDI_CoordSysNed, XDI_CoordSysNwu, XDI_Quaternion, XDI_RotationMatrix, XDI_EulerAngles, XDI_PressureGroup, XDI_BaroPressure, XDI_AccelerationGroup, XDI_DeltaV, XDI_Acceleration, XDI_FreeAcceleration, XDI_AccelerationHR, XDI_IndicationGroup, XDI_TriggerIn1, XDI_TriggerIn2, XDI_TriggerIn3, XDI_PositionGroup, XDI_AltitudeMsl, XDI_AltitudeEllipsoid, XDI_PositionEcef, XDI_LatLon, XDI_GnssGroup, XDI_GnssPvtData, XDI_GnssSatInfo, XDI_GnssPvtPulse, XDI_AngularVelocityGroup, XDI_RateOfTurn, XDI_DeltaQ, XDI_RateOfTurnHR, XDI_RawSensorGroup, XDI_RawUnsigned, XDI_RawSigned, XDI_RawAccGyrMagTemp, XDI_RawGyroTemp, XDI_RawAcc, XDI_RawGyr, XDI_RawMag, XDI_RawDeltaQ, XDI_RawDeltaV, XDI_RawBlob, XDI_AnalogInGroup, XDI_AnalogIn1, XDI_AnalogIn2, XDI_MagneticGroup, XDI_MagneticField, XDI_MagneticFieldCorrected, XDI_SnapshotGroup, XDI_RetransmissionMask, XDI_RetransmissionFlag, XDI_AwindaSnapshot, XDI_FullSnapshot, XDI_GloveSnapshotLeft, XDI_GloveSnapshotRight, XDI_GloveDataGroup, XDI_GloveDataLeft, XDI_GloveDataRight, XDI_VelocityGroup, XDI_VelocityXYZ, XDI_StatusGroup, XDI_StatusByte, XDI_StatusWord, XDI_Rssi, XDI_DeviceId, XDI_LocationId };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

