
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsDeviceErrorType {
  public final static XsDeviceErrorType XERR_Unknown = new XsDeviceErrorType("XERR_Unknown", movelladot_pc_sdkJNI.XERR_Unknown_get());
  public final static XsDeviceErrorType XERR_ImcuTimeout = new XsDeviceErrorType("XERR_ImcuTimeout", movelladot_pc_sdkJNI.XERR_ImcuTimeout_get());
  public final static XsDeviceErrorType XERR_ImcuSettingsInvalid = new XsDeviceErrorType("XERR_ImcuSettingsInvalid", movelladot_pc_sdkJNI.XERR_ImcuSettingsInvalid_get());
  public final static XsDeviceErrorType XERR_ImcuSettingsFailure = new XsDeviceErrorType("XERR_ImcuSettingsFailure", movelladot_pc_sdkJNI.XERR_ImcuSettingsFailure_get());
  public final static XsDeviceErrorType XERR_ImcuEmtsWriteFailure = new XsDeviceErrorType("XERR_ImcuEmtsWriteFailure", movelladot_pc_sdkJNI.XERR_ImcuEmtsWriteFailure_get());
  public final static XsDeviceErrorType XERR_ImcuEmtsReadFailure = new XsDeviceErrorType("XERR_ImcuEmtsReadFailure", movelladot_pc_sdkJNI.XERR_ImcuEmtsReadFailure_get());
  public final static XsDeviceErrorType XERR_DspCrashed = new XsDeviceErrorType("XERR_DspCrashed", movelladot_pc_sdkJNI.XERR_DspCrashed_get());
  public final static XsDeviceErrorType XERR_DspBootingTimeout = new XsDeviceErrorType("XERR_DspBootingTimeout", movelladot_pc_sdkJNI.XERR_DspBootingTimeout_get());
  public final static XsDeviceErrorType XERR_DspSettingsInvalid = new XsDeviceErrorType("XERR_DspSettingsInvalid", movelladot_pc_sdkJNI.XERR_DspSettingsInvalid_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsDeviceErrorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsDeviceErrorType.class + " with value " + swigValue);
  }

  private XsDeviceErrorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsDeviceErrorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsDeviceErrorType(String swigName, XsDeviceErrorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsDeviceErrorType[] swigValues = { XERR_Unknown, XERR_ImcuTimeout, XERR_ImcuSettingsInvalid, XERR_ImcuSettingsFailure, XERR_ImcuEmtsWriteFailure, XERR_ImcuEmtsReadFailure, XERR_DspCrashed, XERR_DspBootingTimeout, XERR_DspSettingsInvalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

