
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsDeviceIdArrayImpl {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsDeviceIdArrayImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsDeviceIdArrayImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsDeviceIdArrayImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsDeviceIdArrayImpl(long count, XsDeviceId src) {
    this(movelladot_pc_sdkJNI.new_XsDeviceIdArrayImpl__SWIG_0(count, XsDeviceId.getCPtr(src), src), true);
  }

  public XsDeviceIdArrayImpl(long count) {
    this(movelladot_pc_sdkJNI.new_XsDeviceIdArrayImpl__SWIG_1(count), true);
  }

  public XsDeviceIdArrayImpl() {
    this(movelladot_pc_sdkJNI.new_XsDeviceIdArrayImpl__SWIG_2(), true);
  }

  public XsDeviceIdArrayImpl(XsDeviceIdArrayImpl other) {
    this(movelladot_pc_sdkJNI.new_XsDeviceIdArrayImpl__SWIG_3(XsDeviceIdArrayImpl.getCPtr(other), other), true);
  }

  public XsDeviceIdArrayImpl(XsDeviceId ref, long sz, XsDataFlags flags) {
    this(movelladot_pc_sdkJNI.new_XsDeviceIdArrayImpl__SWIG_4(XsDeviceId.getCPtr(ref), ref, sz, flags.swigValue()), true);
  }

  public void clear() {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_clear(swigCPtr, this);
  }

  public void reserve(long count) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_reserve(swigCPtr, this, count);
  }

  public long reserved() {
    return movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_reserved(swigCPtr, this);
  }

  public XsArrayDescriptor descriptor() {
    return new XsArrayDescriptor(movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_descriptor(swigCPtr, this), false);
  }

  public XsDeviceId value(long index) {
    return new XsDeviceId(movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_value(swigCPtr, this, index), true);
  }

  public XsDeviceId first() {
    return new XsDeviceId(movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_first(swigCPtr, this), true);
  }

  public XsDeviceId last() {
    return new XsDeviceId(movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_last(swigCPtr, this), true);
  }

  public XsDeviceId at(long index) {
    return new XsDeviceId(movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_at__SWIG_0(swigCPtr, this, index), false);
  }

  public void insert(XsDeviceId item, long index) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_insert__SWIG_0(swigCPtr, this, XsDeviceId.getCPtr(item), item, index);
  }

  public void insert(XsDeviceId items, long index, long count) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_insert__SWIG_1(swigCPtr, this, XsDeviceId.getCPtr(items), items, index, count);
  }

  public void push_back(XsDeviceId item) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_push_back(swigCPtr, this, XsDeviceId.getCPtr(item), item);
  }

  public void pop_back(long count) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_pop_back__SWIG_0(swigCPtr, this, count);
  }

  public void pop_back() {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_pop_back__SWIG_1(swigCPtr, this);
  }

  public void push_front(XsDeviceId item) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_push_front(swigCPtr, this, XsDeviceId.getCPtr(item), item);
  }

  public void pop_front(long count) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_pop_front__SWIG_0(swigCPtr, this, count);
  }

  public void pop_front() {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_pop_front__SWIG_1(swigCPtr, this);
  }

  public long size() {
    return movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_size(swigCPtr, this);
  }

  public void erase(long index, long count) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_erase__SWIG_0(swigCPtr, this, index, count);
  }

  public void erase(long index) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_erase__SWIG_1(swigCPtr, this, index);
  }

  public void assign(long count, XsDeviceId src) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_assign(swigCPtr, this, count, XsDeviceId.getCPtr(src), src);
  }

  public void resize(long count) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_resize(swigCPtr, this, count);
  }

  public void setSize(long count) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_setSize(swigCPtr, this, count);
  }

  public void append(XsDeviceIdArrayImpl other) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_append(swigCPtr, this, XsDeviceIdArrayImpl.getCPtr(other), other);
  }

  public boolean empty() {
    return movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_empty(swigCPtr, this);
  }

  public boolean badAlloc() {
    return movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_badAlloc(swigCPtr, this);
  }

  public void swap(XsDeviceIdArrayImpl other) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_swap__SWIG_0(swigCPtr, this, XsDeviceIdArrayImpl.getCPtr(other), other);
  }

  public void swap(long a, long b) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_swap__SWIG_1(swigCPtr, this, a, b);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsDeviceId needle) {
    return new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_find(swigCPtr, this, XsDeviceId.getCPtr(needle), needle), true);
  }

  public boolean contains(XsDeviceId needle) {
    return movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_contains(swigCPtr, this, XsDeviceId.getCPtr(needle), needle);
  }

  public void removeDuplicates() {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_removeDuplicates(swigCPtr, this);
  }

  public void removeDuplicatesPredicate(SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int predicate) {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_removeDuplicatesPredicate(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int.getCPtr(predicate));
  }

  public void sort() {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_sort(swigCPtr, this);
  }

  public void reverse() {
    movelladot_pc_sdkJNI.XsDeviceIdArrayImpl_reverse(swigCPtr, this);
  }

}
