
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsDeviceState {
  public final static XsDeviceState XDS_Initial = new XsDeviceState("XDS_Initial");
  public final static XsDeviceState XDS_Config = new XsDeviceState("XDS_Config", movelladot_pc_sdkJNI.XDS_Config_get());
  public final static XsDeviceState XDS_Idle = new XsDeviceState("XDS_Idle", movelladot_pc_sdkJNI.XDS_Idle_get());
  public final static XsDeviceState XDS_Measurement = new XsDeviceState("XDS_Measurement");
  public final static XsDeviceState XDS_WaitingForRecordingStart = new XsDeviceState("XDS_WaitingForRecordingStart");
  public final static XsDeviceState XDS_Recording = new XsDeviceState("XDS_Recording");
  public final static XsDeviceState XDS_FlushingData = new XsDeviceState("XDS_FlushingData");
  public final static XsDeviceState XDS_Destructing = new XsDeviceState("XDS_Destructing");
  public final static XsDeviceState XDS_Exporting = new XsDeviceState("XDS_Exporting");
  public final static XsDeviceState XDS_Synchronizing = new XsDeviceState("XDS_Synchronizing");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsDeviceState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsDeviceState.class + " with value " + swigValue);
  }

  private XsDeviceState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsDeviceState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsDeviceState(String swigName, XsDeviceState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsDeviceState[] swigValues = { XDS_Initial, XDS_Config, XDS_Idle, XDS_Measurement, XDS_WaitingForRecordingStart, XDS_Recording, XDS_FlushingData, XDS_Destructing, XDS_Exporting, XDS_Synchronizing };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

