
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsErrorMode {
  public final static XsErrorMode XEM_Ignore = new XsErrorMode("XEM_Ignore", movelladot_pc_sdkJNI.XEM_Ignore_get());
  public final static XsErrorMode XEM_IncreasePacketCounter = new XsErrorMode("XEM_IncreasePacketCounter", movelladot_pc_sdkJNI.XEM_IncreasePacketCounter_get());
  public final static XsErrorMode XEM_IncreasePacketCounterAndSendError = new XsErrorMode("XEM_IncreasePacketCounterAndSendError", movelladot_pc_sdkJNI.XEM_IncreasePacketCounterAndSendError_get());
  public final static XsErrorMode XEM_SendErrorAndGoToConfig = new XsErrorMode("XEM_SendErrorAndGoToConfig", movelladot_pc_sdkJNI.XEM_SendErrorAndGoToConfig_get());
  public final static XsErrorMode XEM_Invalid = new XsErrorMode("XEM_Invalid");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsErrorMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsErrorMode.class + " with value " + swigValue);
  }

  private XsErrorMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsErrorMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsErrorMode(String swigName, XsErrorMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsErrorMode[] swigValues = { XEM_Ignore, XEM_IncreasePacketCounter, XEM_IncreasePacketCounterAndSendError, XEM_SendErrorAndGoToConfig, XEM_Invalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

