
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsFilterProfile {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsFilterProfile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsFilterProfile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsFilterProfile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsFilterProfile(short type_, short version_, String kind_, String label_, char filterType_, short filterMajor_, short filterMinor_) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_0(type_, version_, kind_, label_, filterType_, filterMajor_, filterMinor_), true);
  }

  public XsFilterProfile(short type_, short version_, String kind_, String label_, char filterType_, short filterMajor_) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_1(type_, version_, kind_, label_, filterType_, filterMajor_), true);
  }

  public XsFilterProfile(short type_, short version_, String kind_, String label_, char filterType_) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_2(type_, version_, kind_, label_, filterType_), true);
  }

  public XsFilterProfile(short type_, short version_, String kind_, String label_) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_3(type_, version_, kind_, label_), true);
  }

  public XsFilterProfile(short type_, short version_, String kind_) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_4(type_, version_, kind_), true);
  }

  public XsFilterProfile(short type_, short version_) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_5(type_, version_), true);
  }

  public XsFilterProfile(short type_) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_6(type_), true);
  }

  public XsFilterProfile() {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_7(), true);
  }

  public XsFilterProfile(XsFilterProfile other) {
    this(movelladot_pc_sdkJNI.new_XsFilterProfile__SWIG_8(XsFilterProfile.getCPtr(other), other), true);
  }

  public boolean empty() {
    return movelladot_pc_sdkJNI.XsFilterProfile_empty(swigCPtr, this);
  }

  public XsString toXsString() {
    return new XsString(movelladot_pc_sdkJNI.XsFilterProfile_toXsString(swigCPtr, this), true);
  }

  public short type() {
    return movelladot_pc_sdkJNI.XsFilterProfile_type(swigCPtr, this);
  }

  public short version() {
    return movelladot_pc_sdkJNI.XsFilterProfile_version(swigCPtr, this);
  }

  public String label() {
    return movelladot_pc_sdkJNI.XsFilterProfile_label(swigCPtr, this);
  }

  public String kind() {
    return movelladot_pc_sdkJNI.XsFilterProfile_kind(swigCPtr, this);
  }

  public char filterType() {
    return movelladot_pc_sdkJNI.XsFilterProfile_filterType(swigCPtr, this);
  }

  public short filterMajor() {
    return movelladot_pc_sdkJNI.XsFilterProfile_filterMajor(swigCPtr, this);
  }

  public short filterMinor() {
    return movelladot_pc_sdkJNI.XsFilterProfile_filterMinor(swigCPtr, this);
  }

  public void setType(short type_) {
    movelladot_pc_sdkJNI.XsFilterProfile_setType(swigCPtr, this, type_);
  }

  public void setVersion(short version_) {
    movelladot_pc_sdkJNI.XsFilterProfile_setVersion(swigCPtr, this, version_);
  }

  public void setLabel(String label_) {
    movelladot_pc_sdkJNI.XsFilterProfile_setLabel(swigCPtr, this, label_);
  }

  public void setKind(String kind_) {
    movelladot_pc_sdkJNI.XsFilterProfile_setKind(swigCPtr, this, kind_);
  }

  public void setFilterType(char filterType_) {
    movelladot_pc_sdkJNI.XsFilterProfile_setFilterType(swigCPtr, this, filterType_);
  }

  public void setFilterVersion(short major_, short minor_) {
    movelladot_pc_sdkJNI.XsFilterProfile_setFilterVersion(swigCPtr, this, major_, minor_);
  }

  public void swap(XsFilterProfile other) {
    movelladot_pc_sdkJNI.XsFilterProfile_swap(swigCPtr, this, XsFilterProfile.getCPtr(other), other);
  }

}
