
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsMessageHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsMessageHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsMessageHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsMessageHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_preamble(short value) {
    movelladot_pc_sdkJNI.XsMessageHeader_m_preamble_set(swigCPtr, this, value);
  }

  public short getM_preamble() {
    return movelladot_pc_sdkJNI.XsMessageHeader_m_preamble_get(swigCPtr, this);
  }

  public void setM_busId(short value) {
    movelladot_pc_sdkJNI.XsMessageHeader_m_busId_set(swigCPtr, this, value);
  }

  public short getM_busId() {
    return movelladot_pc_sdkJNI.XsMessageHeader_m_busId_get(swigCPtr, this);
  }

  public void setM_messageId(short value) {
    movelladot_pc_sdkJNI.XsMessageHeader_m_messageId_set(swigCPtr, this, value);
  }

  public short getM_messageId() {
    return movelladot_pc_sdkJNI.XsMessageHeader_m_messageId_get(swigCPtr, this);
  }

  public void setM_length(short value) {
    movelladot_pc_sdkJNI.XsMessageHeader_m_length_set(swigCPtr, this, value);
  }

  public short getM_length() {
    return movelladot_pc_sdkJNI.XsMessageHeader_m_length_get(swigCPtr, this);
  }

  static public class LengthData {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected LengthData(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(LengthData obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkJNI.delete_XsMessageHeader_LengthData(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
      static public class ExtendedLength {
        private transient long swigCPtr;
        protected transient boolean swigCMemOwn;
      
        protected ExtendedLength(long cPtr, boolean cMemoryOwn) {
          swigCMemOwn = cMemoryOwn;
          swigCPtr = cPtr;
        }
      
        protected static long getCPtr(ExtendedLength obj) {
          return (obj == null) ? 0 : obj.swigCPtr;
        }
      
        @SuppressWarnings("deprecation")
        protected void finalize() {
          delete();
        }
      
        public synchronized void delete() {
          if (swigCPtr != 0) {
            if (swigCMemOwn) {
              swigCMemOwn = false;
              movelladot_pc_sdkJNI.delete_XsMessageHeader_LengthData_ExtendedLength(swigCPtr);
            }
            swigCPtr = 0;
          }
        }
      
            static public class ExtendedParts {
              private transient long swigCPtr;
              protected transient boolean swigCMemOwn;
            
              protected ExtendedParts(long cPtr, boolean cMemoryOwn) {
                swigCMemOwn = cMemoryOwn;
                swigCPtr = cPtr;
              }
            
              protected static long getCPtr(ExtendedParts obj) {
                return (obj == null) ? 0 : obj.swigCPtr;
              }
            
              @SuppressWarnings("deprecation")
              protected void finalize() {
                delete();
              }
            
              public synchronized void delete() {
                if (swigCPtr != 0) {
                  if (swigCMemOwn) {
                    swigCMemOwn = false;
                    movelladot_pc_sdkJNI.delete_XsMessageHeader_LengthData_ExtendedLength_ExtendedParts(swigCPtr);
                  }
                  swigCPtr = 0;
                }
              }
            
              public void setM_high(short value) {
                movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_high_set(swigCPtr, this, value);
              }
            
              public short getM_high() {
                return movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_high_get(swigCPtr, this);
              }
            
              public void setM_low(short value) {
                movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_low_set(swigCPtr, this, value);
              }
            
              public short getM_low() {
                return movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_low_get(swigCPtr, this);
              }
            
              public ExtendedParts() {
                this(movelladot_pc_sdkJNI.new_XsMessageHeader_LengthData_ExtendedLength_ExtendedParts(), true);
              }
            
            }
      
        public void setM_length(XsMessageHeader.LengthData.ExtendedLength.ExtendedParts value) {
          movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_m_length_set(swigCPtr, this, XsMessageHeader.LengthData.ExtendedLength.ExtendedParts.getCPtr(value), value);
        }
      
        public XsMessageHeader.LengthData.ExtendedLength.ExtendedParts getM_length() {
          long cPtr = movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_m_length_get(swigCPtr, this);
          return (cPtr == 0) ? null : new XsMessageHeader.LengthData.ExtendedLength.ExtendedParts(cPtr, false);
        }
      
        public void setM_data(SWIGTYPE_p_unsigned_char value) {
          movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_m_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
        }
      
        public SWIGTYPE_p_unsigned_char getM_data() {
          long cPtr = movelladot_pc_sdkJNI.XsMessageHeader_LengthData_ExtendedLength_m_data_get(swigCPtr, this);
          return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
        }
      
        public ExtendedLength() {
          this(movelladot_pc_sdkJNI.new_XsMessageHeader_LengthData_ExtendedLength(), true);
        }
      
      }
  
    public void setM_extended(XsMessageHeader.LengthData.ExtendedLength value) {
      movelladot_pc_sdkJNI.XsMessageHeader_LengthData_m_extended_set(swigCPtr, this, XsMessageHeader.LengthData.ExtendedLength.getCPtr(value), value);
    }
  
    public XsMessageHeader.LengthData.ExtendedLength getM_extended() {
      long cPtr = movelladot_pc_sdkJNI.XsMessageHeader_LengthData_m_extended_get(swigCPtr, this);
      return (cPtr == 0) ? null : new XsMessageHeader.LengthData.ExtendedLength(cPtr, false);
    }
  
    public void setM_data(SWIGTYPE_p_unsigned_char value) {
      movelladot_pc_sdkJNI.XsMessageHeader_LengthData_m_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
    }
  
    public SWIGTYPE_p_unsigned_char getM_data() {
      long cPtr = movelladot_pc_sdkJNI.XsMessageHeader_LengthData_m_data_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    }
  
    public LengthData() {
      this(movelladot_pc_sdkJNI.new_XsMessageHeader_LengthData(), true);
    }
  
  }

  public void setM_datlen(XsMessageHeader.LengthData value) {
    movelladot_pc_sdkJNI.XsMessageHeader_m_datlen_set(swigCPtr, this, XsMessageHeader.LengthData.getCPtr(value), value);
  }

  public XsMessageHeader.LengthData getM_datlen() {
    long cPtr = movelladot_pc_sdkJNI.XsMessageHeader_m_datlen_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsMessageHeader.LengthData(cPtr, false);
  }

  public XsMessageHeader() {
    this(movelladot_pc_sdkJNI.new_XsMessageHeader(), true);
  }

}
