
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsMessage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsMessage(XsXbusMessageId msgId, long dataLength) {
    this(movelladot_pc_sdkJNI.new_XsMessage__SWIG_0(msgId.swigValue(), dataLength), true);
  }

  public XsMessage(XsXbusMessageId msgId) {
    this(movelladot_pc_sdkJNI.new_XsMessage__SWIG_1(msgId.swigValue()), true);
  }

  public XsMessage() {
    this(movelladot_pc_sdkJNI.new_XsMessage__SWIG_2(), true);
  }

  public XsMessage(SWIGTYPE_p_unsigned_char source, long size) {
    this(movelladot_pc_sdkJNI.new_XsMessage__SWIG_3(SWIGTYPE_p_unsigned_char.getCPtr(source), size), true);
  }

  public XsMessage(XsString source, boolean computeChecksum) {
    this(movelladot_pc_sdkJNI.new_XsMessage__SWIG_4(XsString.getCPtr(source), source, computeChecksum), true);
  }

  public XsMessage(XsString source) {
    this(movelladot_pc_sdkJNI.new_XsMessage__SWIG_5(XsString.getCPtr(source), source), true);
  }

  public XsMessage(XsMessage src) {
    this(movelladot_pc_sdkJNI.new_XsMessage__SWIG_6(XsMessage.getCPtr(src), src), true);
  }

  public void clear() {
    movelladot_pc_sdkJNI.XsMessage_clear(swigCPtr, this);
  }

  public boolean empty() {
    return movelladot_pc_sdkJNI.XsMessage_empty(swigCPtr, this);
  }

  public short getBusId() {
    return movelladot_pc_sdkJNI.XsMessage_getBusId(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_char getDataBuffer(long offset) {
    long cPtr = movelladot_pc_sdkJNI.XsMessage_getDataBuffer__SWIG_0(swigCPtr, this, offset);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char getDataBuffer() {
    long cPtr = movelladot_pc_sdkJNI.XsMessage_getDataBuffer__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public short getDataByte(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataByte__SWIG_0(swigCPtr, this, offset);
  }

  public short getDataByte() {
    return movelladot_pc_sdkJNI.XsMessage_getDataByte__SWIG_1(swigCPtr, this);
  }

  public double getDataDouble(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataDouble__SWIG_0(swigCPtr, this, offset);
  }

  public double getDataDouble() {
    return movelladot_pc_sdkJNI.XsMessage_getDataDouble__SWIG_1(swigCPtr, this);
  }

  public float getDataFloat(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataFloat__SWIG_0(swigCPtr, this, offset);
  }

  public float getDataFloat() {
    return movelladot_pc_sdkJNI.XsMessage_getDataFloat__SWIG_1(swigCPtr, this);
  }

  public double getDataF1220(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataF1220__SWIG_0(swigCPtr, this, offset);
  }

  public double getDataF1220() {
    return movelladot_pc_sdkJNI.XsMessage_getDataF1220__SWIG_1(swigCPtr, this);
  }

  public double getDataFP1632(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataFP1632__SWIG_0(swigCPtr, this, offset);
  }

  public double getDataFP1632() {
    return movelladot_pc_sdkJNI.XsMessage_getDataFP1632__SWIG_1(swigCPtr, this);
  }

  public long getDataLong(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataLong__SWIG_0(swigCPtr, this, offset);
  }

  public long getDataLong() {
    return movelladot_pc_sdkJNI.XsMessage_getDataLong__SWIG_1(swigCPtr, this);
  }

  public java.math.BigInteger getDataLongLong(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataLongLong__SWIG_0(swigCPtr, this, offset);
  }

  public java.math.BigInteger getDataLongLong() {
    return movelladot_pc_sdkJNI.XsMessage_getDataLongLong__SWIG_1(swigCPtr, this);
  }

  public int getDataShort(long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataShort__SWIG_0(swigCPtr, this, offset);
  }

  public int getDataShort() {
    return movelladot_pc_sdkJNI.XsMessage_getDataShort__SWIG_1(swigCPtr, this);
  }

  public long getDataSize() {
    return movelladot_pc_sdkJNI.XsMessage_getDataSize(swigCPtr, this);
  }

  public XsXbusMessageId getMessageId() {
    return XsXbusMessageId.swigToEnum(movelladot_pc_sdkJNI.XsMessage_getMessageId(swigCPtr, this));
  }

  public XsResultValue toResultValue() {
    return XsResultValue.swigToEnum(movelladot_pc_sdkJNI.XsMessage_toResultValue(swigCPtr, this));
  }

  public SWIGTYPE_p_unsigned_char getMessageStart() {
    long cPtr = movelladot_pc_sdkJNI.XsMessage_getMessageStart(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public long getTotalMessageSize() {
    return movelladot_pc_sdkJNI.XsMessage_getTotalMessageSize(swigCPtr, this);
  }

  public boolean isChecksumOk() {
    return movelladot_pc_sdkJNI.XsMessage_isChecksumOk(swigCPtr, this);
  }

  public boolean loadFromString(SWIGTYPE_p_unsigned_char src, long msgSize) {
    return movelladot_pc_sdkJNI.XsMessage_loadFromString(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(src), msgSize);
  }

  public void recomputeChecksum() {
    movelladot_pc_sdkJNI.XsMessage_recomputeChecksum(swigCPtr, this);
  }

  public void resizeData(long newSize) {
    movelladot_pc_sdkJNI.XsMessage_resizeData(swigCPtr, this, newSize);
  }

  public void setBusId(short busId) {
    movelladot_pc_sdkJNI.XsMessage_setBusId__SWIG_0(swigCPtr, this, busId);
  }

  public void setBusId(int busId) {
    movelladot_pc_sdkJNI.XsMessage_setBusId__SWIG_1(swigCPtr, this, busId);
  }

  public void setDataBuffer(SWIGTYPE_p_unsigned_char buffer, long size, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataBuffer__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(buffer), size, offset);
  }

  public void setDataBuffer(SWIGTYPE_p_unsigned_char buffer, long size) {
    movelladot_pc_sdkJNI.XsMessage_setDataBuffer__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(buffer), size);
  }

  public void setDataByte(short value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataByte__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataByte(short value) {
    movelladot_pc_sdkJNI.XsMessage_setDataByte__SWIG_1(swigCPtr, this, value);
  }

  public void setDataDouble(double value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataDouble__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataDouble(double value) {
    movelladot_pc_sdkJNI.XsMessage_setDataDouble__SWIG_1(swigCPtr, this, value);
  }

  public void setDataFloat(float value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataFloat__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataFloat(float value) {
    movelladot_pc_sdkJNI.XsMessage_setDataFloat__SWIG_1(swigCPtr, this, value);
  }

  public void setDataF1220(double value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataF1220__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataF1220(double value) {
    movelladot_pc_sdkJNI.XsMessage_setDataF1220__SWIG_1(swigCPtr, this, value);
  }

  public void setDataFP1632(double value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataFP1632__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataFP1632(double value) {
    movelladot_pc_sdkJNI.XsMessage_setDataFP1632__SWIG_1(swigCPtr, this, value);
  }

  public void setDataLong(long value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataLong__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataLong(long value) {
    movelladot_pc_sdkJNI.XsMessage_setDataLong__SWIG_1(swigCPtr, this, value);
  }

  public void setDataLongLong(java.math.BigInteger value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataLongLong__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataLongLong(java.math.BigInteger value) {
    movelladot_pc_sdkJNI.XsMessage_setDataLongLong__SWIG_1(swigCPtr, this, value);
  }

  public void setDataShort(int value, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataShort__SWIG_0(swigCPtr, this, value, offset);
  }

  public void setDataShort(int value) {
    movelladot_pc_sdkJNI.XsMessage_setDataShort__SWIG_1(swigCPtr, this, value);
  }

  public void setMessageId(XsXbusMessageId msgId) {
    movelladot_pc_sdkJNI.XsMessage_setMessageId(swigCPtr, this, msgId.swigValue());
  }

  public void deleteData(long count, long offset) {
    movelladot_pc_sdkJNI.XsMessage_deleteData__SWIG_0(swigCPtr, this, count, offset);
  }

  public void deleteData(long count) {
    movelladot_pc_sdkJNI.XsMessage_deleteData__SWIG_1(swigCPtr, this, count);
  }

  public void insertData(long count, long offset) {
    movelladot_pc_sdkJNI.XsMessage_insertData__SWIG_0(swigCPtr, this, count, offset);
  }

  public void insertData(long count) {
    movelladot_pc_sdkJNI.XsMessage_insertData__SWIG_1(swigCPtr, this, count);
  }

  public static short getFPValueSize(XsDataIdentifier id) {
    return movelladot_pc_sdkJNI.XsMessage_getFPValueSize(id.swigValue());
  }

  public void getDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double dest, long offset, long numValues) {
    movelladot_pc_sdkJNI.XsMessage_getDataFPValue__SWIG_0(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(dest), offset, numValues);
  }

  public void getDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double dest, long offset) {
    movelladot_pc_sdkJNI.XsMessage_getDataFPValue__SWIG_1(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(dest), offset);
  }

  public void getDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double dest) {
    movelladot_pc_sdkJNI.XsMessage_getDataFPValue__SWIG_2(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(dest));
  }

  public double getDataFPValue(XsDataIdentifier dataIdentifier, long offset) {
    return movelladot_pc_sdkJNI.XsMessage_getDataFPValue__SWIG_3(swigCPtr, this, dataIdentifier.swigValue(), offset);
  }

  public double getDataFPValue(XsDataIdentifier dataIdentifier) {
    return movelladot_pc_sdkJNI.XsMessage_getDataFPValue__SWIG_4(swigCPtr, this, dataIdentifier.swigValue());
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double data, long offset, long numValues) {
    movelladot_pc_sdkJNI.XsMessage_setDataFPValue__SWIG_0(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(data), offset, numValues);
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double data, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataFPValue__SWIG_1(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(data), offset);
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double data) {
    movelladot_pc_sdkJNI.XsMessage_setDataFPValue__SWIG_2(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(data));
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, double data, long offset) {
    movelladot_pc_sdkJNI.XsMessage_setDataFPValue__SWIG_3(swigCPtr, this, dataIdentifier.swigValue(), data, offset);
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, double data) {
    movelladot_pc_sdkJNI.XsMessage_setDataFPValue__SWIG_4(swigCPtr, this, dataIdentifier.swigValue(), data);
  }

  public XsByteArray rawMessage() {
    return new XsByteArray(movelladot_pc_sdkJNI.XsMessage_rawMessage(swigCPtr, this), false);
  }

  public XsString toHexString(long maxBytes) {
    return new XsString(movelladot_pc_sdkJNI.XsMessage_toHexString__SWIG_0(swigCPtr, this, maxBytes), true);
  }

  public XsString toHexString() {
    return new XsString(movelladot_pc_sdkJNI.XsMessage_toHexString__SWIG_1(swigCPtr, this), true);
  }

}
