
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsPayloadMode {
  public final static XsPayloadMode Undefined = new XsPayloadMode("Undefined", movelladot_pc_sdkJNI.XsPayloadMode_Undefined_get());
  public final static XsPayloadMode HighFidelitywMag = new XsPayloadMode("HighFidelitywMag", movelladot_pc_sdkJNI.XsPayloadMode_HighFidelitywMag_get());
  public final static XsPayloadMode ExtendedQuaternion = new XsPayloadMode("ExtendedQuaternion", movelladot_pc_sdkJNI.XsPayloadMode_ExtendedQuaternion_get());
  public final static XsPayloadMode CompleteQuaternion = new XsPayloadMode("CompleteQuaternion", movelladot_pc_sdkJNI.XsPayloadMode_CompleteQuaternion_get());
  public final static XsPayloadMode OrientationEuler = new XsPayloadMode("OrientationEuler", movelladot_pc_sdkJNI.XsPayloadMode_OrientationEuler_get());
  public final static XsPayloadMode OrientationQuaternion = new XsPayloadMode("OrientationQuaternion", movelladot_pc_sdkJNI.XsPayloadMode_OrientationQuaternion_get());
  public final static XsPayloadMode FreeAcceleration = new XsPayloadMode("FreeAcceleration", movelladot_pc_sdkJNI.XsPayloadMode_FreeAcceleration_get());
  public final static XsPayloadMode ExtendedEuler = new XsPayloadMode("ExtendedEuler", movelladot_pc_sdkJNI.XsPayloadMode_ExtendedEuler_get());
  public final static XsPayloadMode MFM = new XsPayloadMode("MFM", movelladot_pc_sdkJNI.XsPayloadMode_MFM_get());
  public final static XsPayloadMode CompleteEuler = new XsPayloadMode("CompleteEuler", movelladot_pc_sdkJNI.XsPayloadMode_CompleteEuler_get());
  public final static XsPayloadMode HighFidelity = new XsPayloadMode("HighFidelity", movelladot_pc_sdkJNI.XsPayloadMode_HighFidelity_get());
  public final static XsPayloadMode DeltaQuantitieswMag = new XsPayloadMode("DeltaQuantitieswMag", movelladot_pc_sdkJNI.XsPayloadMode_DeltaQuantitieswMag_get());
  public final static XsPayloadMode DeltaQuantities = new XsPayloadMode("DeltaQuantities", movelladot_pc_sdkJNI.XsPayloadMode_DeltaQuantities_get());
  public final static XsPayloadMode RateQuantitieswMag = new XsPayloadMode("RateQuantitieswMag", movelladot_pc_sdkJNI.XsPayloadMode_RateQuantitieswMag_get());
  public final static XsPayloadMode RateQuantities = new XsPayloadMode("RateQuantities", movelladot_pc_sdkJNI.XsPayloadMode_RateQuantities_get());
  public final static XsPayloadMode CustomMode1 = new XsPayloadMode("CustomMode1", movelladot_pc_sdkJNI.XsPayloadMode_CustomMode1_get());
  public final static XsPayloadMode CustomMode2 = new XsPayloadMode("CustomMode2", movelladot_pc_sdkJNI.XsPayloadMode_CustomMode2_get());
  public final static XsPayloadMode CustomMode3 = new XsPayloadMode("CustomMode3", movelladot_pc_sdkJNI.XsPayloadMode_CustomMode3_get());
  public final static XsPayloadMode CustomMode4 = new XsPayloadMode("CustomMode4", movelladot_pc_sdkJNI.XsPayloadMode_CustomMode4_get());
  public final static XsPayloadMode CustomMode5 = new XsPayloadMode("CustomMode5", movelladot_pc_sdkJNI.XsPayloadMode_CustomMode5_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsPayloadMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsPayloadMode.class + " with value " + swigValue);
  }

  private XsPayloadMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsPayloadMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsPayloadMode(String swigName, XsPayloadMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsPayloadMode[] swigValues = { Undefined, HighFidelitywMag, ExtendedQuaternion, CompleteQuaternion, OrientationEuler, OrientationQuaternion, FreeAcceleration, ExtendedEuler, MFM, CompleteEuler, HighFidelity, DeltaQuantitieswMag, DeltaQuantities, RateQuantitieswMag, RateQuantities, CustomMode1, CustomMode2, CustomMode3, CustomMode4, CustomMode5 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

