
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsRawGnssPvtData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsRawGnssPvtData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsRawGnssPvtData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsRawGnssPvtData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_itow(long value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_itow_set(swigCPtr, this, value);
  }

  public long getM_itow() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_itow_get(swigCPtr, this);
  }

  public void setM_year(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_year_set(swigCPtr, this, value);
  }

  public int getM_year() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_year_get(swigCPtr, this);
  }

  public void setM_month(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_month_set(swigCPtr, this, value);
  }

  public short getM_month() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_month_get(swigCPtr, this);
  }

  public void setM_day(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_day_set(swigCPtr, this, value);
  }

  public short getM_day() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_day_get(swigCPtr, this);
  }

  public void setM_hour(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hour_set(swigCPtr, this, value);
  }

  public short getM_hour() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hour_get(swigCPtr, this);
  }

  public void setM_min(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_min_set(swigCPtr, this, value);
  }

  public short getM_min() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_min_get(swigCPtr, this);
  }

  public void setM_sec(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_sec_set(swigCPtr, this, value);
  }

  public short getM_sec() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_sec_get(swigCPtr, this);
  }

  public void setM_valid(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_valid_set(swigCPtr, this, value);
  }

  public short getM_valid() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_valid_get(swigCPtr, this);
  }

  public void setM_tAcc(long value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_tAcc_set(swigCPtr, this, value);
  }

  public long getM_tAcc() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_tAcc_get(swigCPtr, this);
  }

  public void setM_nano(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_nano_set(swigCPtr, this, value);
  }

  public int getM_nano() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_nano_get(swigCPtr, this);
  }

  public void setM_fixType(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_fixType_set(swigCPtr, this, value);
  }

  public short getM_fixType() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_fixType_get(swigCPtr, this);
  }

  public void setM_flags(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_flags_set(swigCPtr, this, value);
  }

  public short getM_flags() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_flags_get(swigCPtr, this);
  }

  public void setM_numSv(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_numSv_set(swigCPtr, this, value);
  }

  public short getM_numSv() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_numSv_get(swigCPtr, this);
  }

  public void setM_res1(short value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_res1_set(swigCPtr, this, value);
  }

  public short getM_res1() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_res1_get(swigCPtr, this);
  }

  public void setM_lon(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_lon_set(swigCPtr, this, value);
  }

  public int getM_lon() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_lon_get(swigCPtr, this);
  }

  public void setM_lat(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_lat_set(swigCPtr, this, value);
  }

  public int getM_lat() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_lat_get(swigCPtr, this);
  }

  public void setM_height(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_height_set(swigCPtr, this, value);
  }

  public int getM_height() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_height_get(swigCPtr, this);
  }

  public void setM_hMsl(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hMsl_set(swigCPtr, this, value);
  }

  public int getM_hMsl() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hMsl_get(swigCPtr, this);
  }

  public void setM_hAcc(long value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hAcc_set(swigCPtr, this, value);
  }

  public long getM_hAcc() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hAcc_get(swigCPtr, this);
  }

  public void setM_vAcc(long value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_vAcc_set(swigCPtr, this, value);
  }

  public long getM_vAcc() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_vAcc_get(swigCPtr, this);
  }

  public void setM_velN(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_velN_set(swigCPtr, this, value);
  }

  public int getM_velN() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_velN_get(swigCPtr, this);
  }

  public void setM_velE(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_velE_set(swigCPtr, this, value);
  }

  public int getM_velE() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_velE_get(swigCPtr, this);
  }

  public void setM_velD(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_velD_set(swigCPtr, this, value);
  }

  public int getM_velD() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_velD_get(swigCPtr, this);
  }

  public void setM_gSpeed(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_gSpeed_set(swigCPtr, this, value);
  }

  public int getM_gSpeed() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_gSpeed_get(swigCPtr, this);
  }

  public void setM_headMot(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_headMot_set(swigCPtr, this, value);
  }

  public int getM_headMot() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_headMot_get(swigCPtr, this);
  }

  public void setM_sAcc(long value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_sAcc_set(swigCPtr, this, value);
  }

  public long getM_sAcc() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_sAcc_get(swigCPtr, this);
  }

  public void setM_headAcc(long value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_headAcc_set(swigCPtr, this, value);
  }

  public long getM_headAcc() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_headAcc_get(swigCPtr, this);
  }

  public void setM_headVeh(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_headVeh_set(swigCPtr, this, value);
  }

  public int getM_headVeh() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_headVeh_get(swigCPtr, this);
  }

  public void setM_gdop(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_gdop_set(swigCPtr, this, value);
  }

  public int getM_gdop() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_gdop_get(swigCPtr, this);
  }

  public void setM_pdop(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_pdop_set(swigCPtr, this, value);
  }

  public int getM_pdop() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_pdop_get(swigCPtr, this);
  }

  public void setM_tdop(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_tdop_set(swigCPtr, this, value);
  }

  public int getM_tdop() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_tdop_get(swigCPtr, this);
  }

  public void setM_vdop(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_vdop_set(swigCPtr, this, value);
  }

  public int getM_vdop() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_vdop_get(swigCPtr, this);
  }

  public void setM_hdop(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hdop_set(swigCPtr, this, value);
  }

  public int getM_hdop() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_hdop_get(swigCPtr, this);
  }

  public void setM_ndop(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_ndop_set(swigCPtr, this, value);
  }

  public int getM_ndop() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_ndop_get(swigCPtr, this);
  }

  public void setM_edop(int value) {
    movelladot_pc_sdkJNI.XsRawGnssPvtData_m_edop_set(swigCPtr, this, value);
  }

  public int getM_edop() {
    return movelladot_pc_sdkJNI.XsRawGnssPvtData_m_edop_get(swigCPtr, this);
  }

  public XsRawGnssPvtData() {
    this(movelladot_pc_sdkJNI.new_XsRawGnssPvtData(), true);
  }

}
