
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsResultValue {
  public final static XsResultValue XRV_OK = new XsResultValue("XRV_OK", movelladot_pc_sdkJNI.XRV_OK_get());
  public final static XsResultValue XRV_NOBUS = new XsResultValue("XRV_NOBUS", movelladot_pc_sdkJNI.XRV_NOBUS_get());
  public final static XsResultValue XRV_BUSNOTREADY = new XsResultValue("XRV_BUSNOTREADY", movelladot_pc_sdkJNI.XRV_BUSNOTREADY_get());
  public final static XsResultValue XRV_INVALIDPERIOD = new XsResultValue("XRV_INVALIDPERIOD", movelladot_pc_sdkJNI.XRV_INVALIDPERIOD_get());
  public final static XsResultValue XRV_INVALIDMSG = new XsResultValue("XRV_INVALIDMSG", movelladot_pc_sdkJNI.XRV_INVALIDMSG_get());
  public final static XsResultValue XRV_INITBUSFAIL1 = new XsResultValue("XRV_INITBUSFAIL1", movelladot_pc_sdkJNI.XRV_INITBUSFAIL1_get());
  public final static XsResultValue XRV_INITBUSFAIL2 = new XsResultValue("XRV_INITBUSFAIL2", movelladot_pc_sdkJNI.XRV_INITBUSFAIL2_get());
  public final static XsResultValue XRV_INITBUSFAIL3 = new XsResultValue("XRV_INITBUSFAIL3", movelladot_pc_sdkJNI.XRV_INITBUSFAIL3_get());
  public final static XsResultValue XRV_SETBIDFAIL1 = new XsResultValue("XRV_SETBIDFAIL1", movelladot_pc_sdkJNI.XRV_SETBIDFAIL1_get());
  public final static XsResultValue XRV_SETBIDFAIL2 = new XsResultValue("XRV_SETBIDFAIL2", movelladot_pc_sdkJNI.XRV_SETBIDFAIL2_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL1 = new XsResultValue("XRV_MEASUREMENTFAIL1", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL1_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL2 = new XsResultValue("XRV_MEASUREMENTFAIL2", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL2_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL3 = new XsResultValue("XRV_MEASUREMENTFAIL3", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL3_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL4 = new XsResultValue("XRV_MEASUREMENTFAIL4", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL4_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL5 = new XsResultValue("XRV_MEASUREMENTFAIL5", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL5_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL6 = new XsResultValue("XRV_MEASUREMENTFAIL6", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL6_get());
  public final static XsResultValue XRV_TIMEROVERFLOW = new XsResultValue("XRV_TIMEROVERFLOW", movelladot_pc_sdkJNI.XRV_TIMEROVERFLOW_get());
  public final static XsResultValue XRV_BAUDRATEINVALID = new XsResultValue("XRV_BAUDRATEINVALID", movelladot_pc_sdkJNI.XRV_BAUDRATEINVALID_get());
  public final static XsResultValue XRV_INVALIDPARAM = new XsResultValue("XRV_INVALIDPARAM", movelladot_pc_sdkJNI.XRV_INVALIDPARAM_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL7 = new XsResultValue("XRV_MEASUREMENTFAIL7", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL7_get());
  public final static XsResultValue XRV_MEASUREMENTFAIL8 = new XsResultValue("XRV_MEASUREMENTFAIL8", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAIL8_get());
  public final static XsResultValue XRV_WIRELESSFAIL = new XsResultValue("XRV_WIRELESSFAIL", movelladot_pc_sdkJNI.XRV_WIRELESSFAIL_get());
  public final static XsResultValue XRV_DEVICEERROR = new XsResultValue("XRV_DEVICEERROR", movelladot_pc_sdkJNI.XRV_DEVICEERROR_get());
  public final static XsResultValue XRV_DATAOVERFLOW = new XsResultValue("XRV_DATAOVERFLOW", movelladot_pc_sdkJNI.XRV_DATAOVERFLOW_get());
  public final static XsResultValue XRV_BUFFEROVERFLOW = new XsResultValue("XRV_BUFFEROVERFLOW", movelladot_pc_sdkJNI.XRV_BUFFEROVERFLOW_get());
  public final static XsResultValue XRV_EXTTRIGGERERROR = new XsResultValue("XRV_EXTTRIGGERERROR", movelladot_pc_sdkJNI.XRV_EXTTRIGGERERROR_get());
  public final static XsResultValue XRV_SAMPLESTREAMERROR = new XsResultValue("XRV_SAMPLESTREAMERROR", movelladot_pc_sdkJNI.XRV_SAMPLESTREAMERROR_get());
  public final static XsResultValue XRV_POWER_DIP = new XsResultValue("XRV_POWER_DIP", movelladot_pc_sdkJNI.XRV_POWER_DIP_get());
  public final static XsResultValue XRV_POWER_OVERCURRENT = new XsResultValue("XRV_POWER_OVERCURRENT", movelladot_pc_sdkJNI.XRV_POWER_OVERCURRENT_get());
  public final static XsResultValue XRV_OVERHEATING = new XsResultValue("XRV_OVERHEATING", movelladot_pc_sdkJNI.XRV_OVERHEATING_get());
  public final static XsResultValue XRV_BATTERYLOW = new XsResultValue("XRV_BATTERYLOW", movelladot_pc_sdkJNI.XRV_BATTERYLOW_get());
  public final static XsResultValue XRV_INVALIDFILTERPROFILE = new XsResultValue("XRV_INVALIDFILTERPROFILE", movelladot_pc_sdkJNI.XRV_INVALIDFILTERPROFILE_get());
  public final static XsResultValue XRV_INVALIDSTOREDSETTINGS = new XsResultValue("XRV_INVALIDSTOREDSETTINGS", movelladot_pc_sdkJNI.XRV_INVALIDSTOREDSETTINGS_get());
  public final static XsResultValue XRV_ACCESSDENIED = new XsResultValue("XRV_ACCESSDENIED", movelladot_pc_sdkJNI.XRV_ACCESSDENIED_get());
  public final static XsResultValue XRV_FILEERROR = new XsResultValue("XRV_FILEERROR", movelladot_pc_sdkJNI.XRV_FILEERROR_get());
  public final static XsResultValue XRV_OUTPUTCONFIGERROR = new XsResultValue("XRV_OUTPUTCONFIGERROR", movelladot_pc_sdkJNI.XRV_OUTPUTCONFIGERROR_get());
  public final static XsResultValue XRV_FILE_SYSTEM_CORRUPT = new XsResultValue("XRV_FILE_SYSTEM_CORRUPT", movelladot_pc_sdkJNI.XRV_FILE_SYSTEM_CORRUPT_get());
  public final static XsResultValue XRV_BATTERY_SYSTEM_ERROR = new XsResultValue("XRV_BATTERY_SYSTEM_ERROR", movelladot_pc_sdkJNI.XRV_BATTERY_SYSTEM_ERROR_get());
  public final static XsResultValue XRV_ERROR = new XsResultValue("XRV_ERROR", movelladot_pc_sdkJNI.XRV_ERROR_get());
  public final static XsResultValue XRV_NOTIMPLEMENTED = new XsResultValue("XRV_NOTIMPLEMENTED", movelladot_pc_sdkJNI.XRV_NOTIMPLEMENTED_get());
  public final static XsResultValue XRV_TIMEOUT = new XsResultValue("XRV_TIMEOUT", movelladot_pc_sdkJNI.XRV_TIMEOUT_get());
  public final static XsResultValue XRV_TIMEOUTNODATA = new XsResultValue("XRV_TIMEOUTNODATA", movelladot_pc_sdkJNI.XRV_TIMEOUTNODATA_get());
  public final static XsResultValue XRV_CHECKSUMFAULT = new XsResultValue("XRV_CHECKSUMFAULT", movelladot_pc_sdkJNI.XRV_CHECKSUMFAULT_get());
  public final static XsResultValue XRV_OUTOFMEMORY = new XsResultValue("XRV_OUTOFMEMORY", movelladot_pc_sdkJNI.XRV_OUTOFMEMORY_get());
  public final static XsResultValue XRV_NOTFOUND = new XsResultValue("XRV_NOTFOUND", movelladot_pc_sdkJNI.XRV_NOTFOUND_get());
  public final static XsResultValue XRV_UNEXPECTEDMSG = new XsResultValue("XRV_UNEXPECTEDMSG", movelladot_pc_sdkJNI.XRV_UNEXPECTEDMSG_get());
  public final static XsResultValue XRV_INVALIDID = new XsResultValue("XRV_INVALIDID", movelladot_pc_sdkJNI.XRV_INVALIDID_get());
  public final static XsResultValue XRV_INVALIDOPERATION = new XsResultValue("XRV_INVALIDOPERATION", movelladot_pc_sdkJNI.XRV_INVALIDOPERATION_get());
  public final static XsResultValue XRV_INSUFFICIENTSPACE = new XsResultValue("XRV_INSUFFICIENTSPACE", movelladot_pc_sdkJNI.XRV_INSUFFICIENTSPACE_get());
  public final static XsResultValue XRV_INPUTCANNOTBEOPENED = new XsResultValue("XRV_INPUTCANNOTBEOPENED", movelladot_pc_sdkJNI.XRV_INPUTCANNOTBEOPENED_get());
  public final static XsResultValue XRV_OUTPUTCANNOTBEOPENED = new XsResultValue("XRV_OUTPUTCANNOTBEOPENED", movelladot_pc_sdkJNI.XRV_OUTPUTCANNOTBEOPENED_get());
  public final static XsResultValue XRV_ALREADYOPEN = new XsResultValue("XRV_ALREADYOPEN", movelladot_pc_sdkJNI.XRV_ALREADYOPEN_get());
  public final static XsResultValue XRV_ENDOFFILE = new XsResultValue("XRV_ENDOFFILE", movelladot_pc_sdkJNI.XRV_ENDOFFILE_get());
  public final static XsResultValue XRV_COULDNOTREADSETTINGS = new XsResultValue("XRV_COULDNOTREADSETTINGS", movelladot_pc_sdkJNI.XRV_COULDNOTREADSETTINGS_get());
  public final static XsResultValue XRV_NODATA = new XsResultValue("XRV_NODATA", movelladot_pc_sdkJNI.XRV_NODATA_get());
  public final static XsResultValue XRV_READONLY = new XsResultValue("XRV_READONLY", movelladot_pc_sdkJNI.XRV_READONLY_get());
  public final static XsResultValue XRV_NULLPTR = new XsResultValue("XRV_NULLPTR", movelladot_pc_sdkJNI.XRV_NULLPTR_get());
  public final static XsResultValue XRV_INSUFFICIENTDATA = new XsResultValue("XRV_INSUFFICIENTDATA", movelladot_pc_sdkJNI.XRV_INSUFFICIENTDATA_get());
  public final static XsResultValue XRV_BUSY = new XsResultValue("XRV_BUSY", movelladot_pc_sdkJNI.XRV_BUSY_get());
  public final static XsResultValue XRV_INVALIDINSTANCE = new XsResultValue("XRV_INVALIDINSTANCE", movelladot_pc_sdkJNI.XRV_INVALIDINSTANCE_get());
  public final static XsResultValue XRV_DATACORRUPT = new XsResultValue("XRV_DATACORRUPT", movelladot_pc_sdkJNI.XRV_DATACORRUPT_get());
  public final static XsResultValue XRV_READINITFAILED = new XsResultValue("XRV_READINITFAILED", movelladot_pc_sdkJNI.XRV_READINITFAILED_get());
  public final static XsResultValue XRV_NOXMFOUND = new XsResultValue("XRV_NOXMFOUND", movelladot_pc_sdkJNI.XRV_NOXMFOUND_get());
  public final static XsResultValue XRV_DEVICECOUNTZERO = new XsResultValue("XRV_DEVICECOUNTZERO", movelladot_pc_sdkJNI.XRV_DEVICECOUNTZERO_get());
  public final static XsResultValue XRV_MTLOCATIONINVALID = new XsResultValue("XRV_MTLOCATIONINVALID", movelladot_pc_sdkJNI.XRV_MTLOCATIONINVALID_get());
  public final static XsResultValue XRV_INSUFFICIENTMTS = new XsResultValue("XRV_INSUFFICIENTMTS", movelladot_pc_sdkJNI.XRV_INSUFFICIENTMTS_get());
  public final static XsResultValue XRV_INITFUSIONFAILED = new XsResultValue("XRV_INITFUSIONFAILED", movelladot_pc_sdkJNI.XRV_INITFUSIONFAILED_get());
  public final static XsResultValue XRV_OTHER = new XsResultValue("XRV_OTHER", movelladot_pc_sdkJNI.XRV_OTHER_get());
  public final static XsResultValue XRV_NOFILEOPEN = new XsResultValue("XRV_NOFILEOPEN", movelladot_pc_sdkJNI.XRV_NOFILEOPEN_get());
  public final static XsResultValue XRV_NOPORTOPEN = new XsResultValue("XRV_NOPORTOPEN", movelladot_pc_sdkJNI.XRV_NOPORTOPEN_get());
  public final static XsResultValue XRV_NOFILEORPORTOPEN = new XsResultValue("XRV_NOFILEORPORTOPEN", movelladot_pc_sdkJNI.XRV_NOFILEORPORTOPEN_get());
  public final static XsResultValue XRV_PORTNOTFOUND = new XsResultValue("XRV_PORTNOTFOUND", movelladot_pc_sdkJNI.XRV_PORTNOTFOUND_get());
  public final static XsResultValue XRV_INITPORTFAILED = new XsResultValue("XRV_INITPORTFAILED", movelladot_pc_sdkJNI.XRV_INITPORTFAILED_get());
  public final static XsResultValue XRV_CALIBRATIONFAILED = new XsResultValue("XRV_CALIBRATIONFAILED", movelladot_pc_sdkJNI.XRV_CALIBRATIONFAILED_get());
  public final static XsResultValue XRV_CONFIGCHECKFAIL = new XsResultValue("XRV_CONFIGCHECKFAIL", movelladot_pc_sdkJNI.XRV_CONFIGCHECKFAIL_get());
  public final static XsResultValue XRV_ALREADYDONE = new XsResultValue("XRV_ALREADYDONE", movelladot_pc_sdkJNI.XRV_ALREADYDONE_get());
  public final static XsResultValue XRV_SYNC_SINGLE_SLAVE = new XsResultValue("XRV_SYNC_SINGLE_SLAVE", movelladot_pc_sdkJNI.XRV_SYNC_SINGLE_SLAVE_get());
  public final static XsResultValue XRV_SYNC_SECOND_MASTER = new XsResultValue("XRV_SYNC_SECOND_MASTER", movelladot_pc_sdkJNI.XRV_SYNC_SECOND_MASTER_get());
  public final static XsResultValue XRV_SYNC_NO_SYNC = new XsResultValue("XRV_SYNC_NO_SYNC", movelladot_pc_sdkJNI.XRV_SYNC_NO_SYNC_get());
  public final static XsResultValue XRV_SYNC_NO_MASTER = new XsResultValue("XRV_SYNC_NO_MASTER", movelladot_pc_sdkJNI.XRV_SYNC_NO_MASTER_get());
  public final static XsResultValue XRV_SYNC_DATA_MISSING = new XsResultValue("XRV_SYNC_DATA_MISSING", movelladot_pc_sdkJNI.XRV_SYNC_DATA_MISSING_get());
  public final static XsResultValue XRV_VERSION_TOO_LOW = new XsResultValue("XRV_VERSION_TOO_LOW", movelladot_pc_sdkJNI.XRV_VERSION_TOO_LOW_get());
  public final static XsResultValue XRV_VERSION_PROBLEM = new XsResultValue("XRV_VERSION_PROBLEM", movelladot_pc_sdkJNI.XRV_VERSION_PROBLEM_get());
  public final static XsResultValue XRV_ABORTED = new XsResultValue("XRV_ABORTED", movelladot_pc_sdkJNI.XRV_ABORTED_get());
  public final static XsResultValue XRV_UNSUPPORTED = new XsResultValue("XRV_UNSUPPORTED", movelladot_pc_sdkJNI.XRV_UNSUPPORTED_get());
  public final static XsResultValue XRV_PACKETCOUNTERMISSED = new XsResultValue("XRV_PACKETCOUNTERMISSED", movelladot_pc_sdkJNI.XRV_PACKETCOUNTERMISSED_get());
  public final static XsResultValue XRV_MEASUREMENTFAILED = new XsResultValue("XRV_MEASUREMENTFAILED", movelladot_pc_sdkJNI.XRV_MEASUREMENTFAILED_get());
  public final static XsResultValue XRV_STARTRECORDINGFAILED = new XsResultValue("XRV_STARTRECORDINGFAILED", movelladot_pc_sdkJNI.XRV_STARTRECORDINGFAILED_get());
  public final static XsResultValue XRV_STOPRECORDINGFAILED = new XsResultValue("XRV_STOPRECORDINGFAILED", movelladot_pc_sdkJNI.XRV_STOPRECORDINGFAILED_get());
  public final static XsResultValue XRV_RADIO_CHANNEL_IN_USE = new XsResultValue("XRV_RADIO_CHANNEL_IN_USE", movelladot_pc_sdkJNI.XRV_RADIO_CHANNEL_IN_USE_get());
  public final static XsResultValue XRV_UNEXPECTED_DISCONNECT = new XsResultValue("XRV_UNEXPECTED_DISCONNECT", movelladot_pc_sdkJNI.XRV_UNEXPECTED_DISCONNECT_get());
  public final static XsResultValue XRV_TOO_MANY_CONNECTED_TRACKERS = new XsResultValue("XRV_TOO_MANY_CONNECTED_TRACKERS", movelladot_pc_sdkJNI.XRV_TOO_MANY_CONNECTED_TRACKERS_get());
  public final static XsResultValue XRV_GOTOCONFIGFAILED = new XsResultValue("XRV_GOTOCONFIGFAILED", movelladot_pc_sdkJNI.XRV_GOTOCONFIGFAILED_get());
  public final static XsResultValue XRV_OUTOFRANGE = new XsResultValue("XRV_OUTOFRANGE", movelladot_pc_sdkJNI.XRV_OUTOFRANGE_get());
  public final static XsResultValue XRV_BACKINRANGE = new XsResultValue("XRV_BACKINRANGE", movelladot_pc_sdkJNI.XRV_BACKINRANGE_get());
  public final static XsResultValue XRV_EXPECTED_DISCONNECT = new XsResultValue("XRV_EXPECTED_DISCONNECT", movelladot_pc_sdkJNI.XRV_EXPECTED_DISCONNECT_get());
  public final static XsResultValue XRV_RESTORE_COMMUNICATION_FAILED = new XsResultValue("XRV_RESTORE_COMMUNICATION_FAILED", movelladot_pc_sdkJNI.XRV_RESTORE_COMMUNICATION_FAILED_get());
  public final static XsResultValue XRV_RESTORE_COMMUNICATION_STOPPED = new XsResultValue("XRV_RESTORE_COMMUNICATION_STOPPED", movelladot_pc_sdkJNI.XRV_RESTORE_COMMUNICATION_STOPPED_get());
  public final static XsResultValue XRV_EXPECTED_CONNECT = new XsResultValue("XRV_EXPECTED_CONNECT", movelladot_pc_sdkJNI.XRV_EXPECTED_CONNECT_get());
  public final static XsResultValue XRV_IN_USE = new XsResultValue("XRV_IN_USE", movelladot_pc_sdkJNI.XRV_IN_USE_get());
  public final static XsResultValue XRV_PERFORMANCE_WARNING = new XsResultValue("XRV_PERFORMANCE_WARNING", movelladot_pc_sdkJNI.XRV_PERFORMANCE_WARNING_get());
  public final static XsResultValue XRV_PERFORMANCE_OK = new XsResultValue("XRV_PERFORMANCE_OK", movelladot_pc_sdkJNI.XRV_PERFORMANCE_OK_get());
  public final static XsResultValue XRV_DEVICEID_COLLISION = new XsResultValue("XRV_DEVICEID_COLLISION", movelladot_pc_sdkJNI.XRV_DEVICEID_COLLISION_get());
  public final static XsResultValue XRV_SHUTTINGDOWN = new XsResultValue("XRV_SHUTTINGDOWN", movelladot_pc_sdkJNI.XRV_SHUTTINGDOWN_get());
  public final static XsResultValue XRV_GNSSCONFIGURATIONERROR = new XsResultValue("XRV_GNSSCONFIGURATIONERROR", movelladot_pc_sdkJNI.XRV_GNSSCONFIGURATIONERROR_get());
  public final static XsResultValue XRV_GNSSCOMMTIMEOUT = new XsResultValue("XRV_GNSSCOMMTIMEOUT", movelladot_pc_sdkJNI.XRV_GNSSCOMMTIMEOUT_get());
  public final static XsResultValue XRV_GNSSERROR = new XsResultValue("XRV_GNSSERROR", movelladot_pc_sdkJNI.XRV_GNSSERROR_get());
  public final static XsResultValue XRV_DEVICE_NOT_CALIBRATED = new XsResultValue("XRV_DEVICE_NOT_CALIBRATED", movelladot_pc_sdkJNI.XRV_DEVICE_NOT_CALIBRATED_get());
  public final static XsResultValue XRV_GNSSCONNECTIONLOST = new XsResultValue("XRV_GNSSCONNECTIONLOST", movelladot_pc_sdkJNI.XRV_GNSSCONNECTIONLOST_get());
  public final static XsResultValue XRV_GNSSLOWINPUTRATE = new XsResultValue("XRV_GNSSLOWINPUTRATE", movelladot_pc_sdkJNI.XRV_GNSSLOWINPUTRATE_get());
  public final static XsResultValue XRV_GNSSINCOMPLETEDATASET = new XsResultValue("XRV_GNSSINCOMPLETEDATASET", movelladot_pc_sdkJNI.XRV_GNSSINCOMPLETEDATASET_get());
  public final static XsResultValue XRV_BLUETOOTH_SCANNING_ERROR = new XsResultValue("XRV_BLUETOOTH_SCANNING_ERROR", movelladot_pc_sdkJNI.XRV_BLUETOOTH_SCANNING_ERROR_get());
  public final static XsResultValue XRV_FLASH_PROCESS_BUSY = new XsResultValue("XRV_FLASH_PROCESS_BUSY", movelladot_pc_sdkJNI.XRV_FLASH_PROCESS_BUSY_get());
  public final static XsResultValue XRV_FLASH_FULL = new XsResultValue("XRV_FLASH_FULL", movelladot_pc_sdkJNI.XRV_FLASH_FULL_get());
  public final static XsResultValue XRV_INVALID_FLASHFORMAT = new XsResultValue("XRV_INVALID_FLASHFORMAT", movelladot_pc_sdkJNI.XRV_INVALID_FLASHFORMAT_get());
  public final static XsResultValue XRV_SYNC_TOO_FEW_DEVICES = new XsResultValue("XRV_SYNC_TOO_FEW_DEVICES", movelladot_pc_sdkJNI.XRV_SYNC_TOO_FEW_DEVICES_get());
  public final static XsResultValue XRV_SYNC_COULD_NOT_START = new XsResultValue("XRV_SYNC_COULD_NOT_START", movelladot_pc_sdkJNI.XRV_SYNC_COULD_NOT_START_get());
  public final static XsResultValue XRV_SYNC_SETTINGS_MISMATCH = new XsResultValue("XRV_SYNC_SETTINGS_MISMATCH", movelladot_pc_sdkJNI.XRV_SYNC_SETTINGS_MISMATCH_get());
  public final static XsResultValue XRV_SYNC_NO_START_ROOT = new XsResultValue("XRV_SYNC_NO_START_ROOT", movelladot_pc_sdkJNI.XRV_SYNC_NO_START_ROOT_get());
  public final static XsResultValue XRV_SYNC_NO_START_SCANNER = new XsResultValue("XRV_SYNC_NO_START_SCANNER", movelladot_pc_sdkJNI.XRV_SYNC_NO_START_SCANNER_get());
  public final static XsResultValue XRV_SYNC_NO_RECONNECT = new XsResultValue("XRV_SYNC_NO_RECONNECT", movelladot_pc_sdkJNI.XRV_SYNC_NO_RECONNECT_get());
  public final static XsResultValue XRV_SYNC_FAILED = new XsResultValue("XRV_SYNC_FAILED", movelladot_pc_sdkJNI.XRV_SYNC_FAILED_get());
  public final static XsResultValue XRV_SYNC_ROOT_NOT_FOUND = new XsResultValue("XRV_SYNC_ROOT_NOT_FOUND", movelladot_pc_sdkJNI.XRV_SYNC_ROOT_NOT_FOUND_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsResultValue swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsResultValue.class + " with value " + swigValue);
  }

  private XsResultValue(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsResultValue(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsResultValue(String swigName, XsResultValue swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsResultValue[] swigValues = { XRV_OK, XRV_NOBUS, XRV_BUSNOTREADY, XRV_INVALIDPERIOD, XRV_INVALIDMSG, XRV_INITBUSFAIL1, XRV_INITBUSFAIL2, XRV_INITBUSFAIL3, XRV_SETBIDFAIL1, XRV_SETBIDFAIL2, XRV_MEASUREMENTFAIL1, XRV_MEASUREMENTFAIL2, XRV_MEASUREMENTFAIL3, XRV_MEASUREMENTFAIL4, XRV_MEASUREMENTFAIL5, XRV_MEASUREMENTFAIL6, XRV_TIMEROVERFLOW, XRV_BAUDRATEINVALID, XRV_INVALIDPARAM, XRV_MEASUREMENTFAIL7, XRV_MEASUREMENTFAIL8, XRV_WIRELESSFAIL, XRV_DEVICEERROR, XRV_DATAOVERFLOW, XRV_BUFFEROVERFLOW, XRV_EXTTRIGGERERROR, XRV_SAMPLESTREAMERROR, XRV_POWER_DIP, XRV_POWER_OVERCURRENT, XRV_OVERHEATING, XRV_BATTERYLOW, XRV_INVALIDFILTERPROFILE, XRV_INVALIDSTOREDSETTINGS, XRV_ACCESSDENIED, XRV_FILEERROR, XRV_OUTPUTCONFIGERROR, XRV_FILE_SYSTEM_CORRUPT, XRV_BATTERY_SYSTEM_ERROR, XRV_ERROR, XRV_NOTIMPLEMENTED, XRV_TIMEOUT, XRV_TIMEOUTNODATA, XRV_CHECKSUMFAULT, XRV_OUTOFMEMORY, XRV_NOTFOUND, XRV_UNEXPECTEDMSG, XRV_INVALIDID, XRV_INVALIDOPERATION, XRV_INSUFFICIENTSPACE, XRV_INPUTCANNOTBEOPENED, XRV_OUTPUTCANNOTBEOPENED, XRV_ALREADYOPEN, XRV_ENDOFFILE, XRV_COULDNOTREADSETTINGS, XRV_NODATA, XRV_READONLY, XRV_NULLPTR, XRV_INSUFFICIENTDATA, XRV_BUSY, XRV_INVALIDINSTANCE, XRV_DATACORRUPT, XRV_READINITFAILED, XRV_NOXMFOUND, XRV_DEVICECOUNTZERO, XRV_MTLOCATIONINVALID, XRV_INSUFFICIENTMTS, XRV_INITFUSIONFAILED, XRV_OTHER, XRV_NOFILEOPEN, XRV_NOPORTOPEN, XRV_NOFILEORPORTOPEN, XRV_PORTNOTFOUND, XRV_INITPORTFAILED, XRV_CALIBRATIONFAILED, XRV_CONFIGCHECKFAIL, XRV_ALREADYDONE, XRV_SYNC_SINGLE_SLAVE, XRV_SYNC_SECOND_MASTER, XRV_SYNC_NO_SYNC, XRV_SYNC_NO_MASTER, XRV_SYNC_DATA_MISSING, XRV_VERSION_TOO_LOW, XRV_VERSION_PROBLEM, XRV_ABORTED, XRV_UNSUPPORTED, XRV_PACKETCOUNTERMISSED, XRV_MEASUREMENTFAILED, XRV_STARTRECORDINGFAILED, XRV_STOPRECORDINGFAILED, XRV_RADIO_CHANNEL_IN_USE, XRV_UNEXPECTED_DISCONNECT, XRV_TOO_MANY_CONNECTED_TRACKERS, XRV_GOTOCONFIGFAILED, XRV_OUTOFRANGE, XRV_BACKINRANGE, XRV_EXPECTED_DISCONNECT, XRV_RESTORE_COMMUNICATION_FAILED, XRV_RESTORE_COMMUNICATION_STOPPED, XRV_EXPECTED_CONNECT, XRV_IN_USE, XRV_PERFORMANCE_WARNING, XRV_PERFORMANCE_OK, XRV_DEVICEID_COLLISION, XRV_SHUTTINGDOWN, XRV_GNSSCONFIGURATIONERROR, XRV_GNSSCOMMTIMEOUT, XRV_GNSSERROR, XRV_DEVICE_NOT_CALIBRATED, XRV_GNSSCONNECTIONLOST, XRV_GNSSLOWINPUTRATE, XRV_GNSSINCOMPLETEDATASET, XRV_BLUETOOTH_SCANNING_ERROR, XRV_FLASH_PROCESS_BUSY, XRV_FLASH_FULL, XRV_INVALID_FLASHFORMAT, XRV_SYNC_TOO_FEW_DEVICES, XRV_SYNC_COULD_NOT_START, XRV_SYNC_SETTINGS_MISMATCH, XRV_SYNC_NO_START_ROOT, XRV_SYNC_NO_START_SCANNER, XRV_SYNC_NO_RECONNECT, XRV_SYNC_FAILED, XRV_SYNC_ROOT_NOT_FOUND };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

