
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsSatInfoFlags {
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_Mask = new XsSatInfoFlags("XSIF_SignalQualityIndicator_Mask", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_Mask_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_NoSignal = new XsSatInfoFlags("XSIF_SignalQualityIndicator_NoSignal", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_NoSignal_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_Searching = new XsSatInfoFlags("XSIF_SignalQualityIndicator_Searching", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_Searching_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_Acquired = new XsSatInfoFlags("XSIF_SignalQualityIndicator_Acquired", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_Acquired_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_Unusable = new XsSatInfoFlags("XSIF_SignalQualityIndicator_Unusable", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_Unusable_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_CodeTimeOk = new XsSatInfoFlags("XSIF_SignalQualityIndicator_CodeTimeOk", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_CodeTimeOk_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_CodeCarrierTimeOk1 = new XsSatInfoFlags("XSIF_SignalQualityIndicator_CodeCarrierTimeOk1", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_CodeCarrierTimeOk1_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_CodeCarrierTimeOk2 = new XsSatInfoFlags("XSIF_SignalQualityIndicator_CodeCarrierTimeOk2", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_CodeCarrierTimeOk2_get());
  public final static XsSatInfoFlags XSIF_SignalQualityIndicator_CodeCarrierTimeOk3 = new XsSatInfoFlags("XSIF_SignalQualityIndicator_CodeCarrierTimeOk3", movelladot_pc_sdkJNI.XSIF_SignalQualityIndicator_CodeCarrierTimeOk3_get());
  public final static XsSatInfoFlags XSIF_UsedForNavigation_Mask = new XsSatInfoFlags("XSIF_UsedForNavigation_Mask", movelladot_pc_sdkJNI.XSIF_UsedForNavigation_Mask_get());
  public final static XsSatInfoFlags XSIF_UsedForNavigation_Used = new XsSatInfoFlags("XSIF_UsedForNavigation_Used", movelladot_pc_sdkJNI.XSIF_UsedForNavigation_Used_get());
  public final static XsSatInfoFlags XSIF_HealthFlag_Mask = new XsSatInfoFlags("XSIF_HealthFlag_Mask", movelladot_pc_sdkJNI.XSIF_HealthFlag_Mask_get());
  public final static XsSatInfoFlags XSIF_HealthFlag_Unknown = new XsSatInfoFlags("XSIF_HealthFlag_Unknown", movelladot_pc_sdkJNI.XSIF_HealthFlag_Unknown_get());
  public final static XsSatInfoFlags XSIF_HealthFlag_Healthy = new XsSatInfoFlags("XSIF_HealthFlag_Healthy", movelladot_pc_sdkJNI.XSIF_HealthFlag_Healthy_get());
  public final static XsSatInfoFlags XSIF_HealthFlag_Unhealthy = new XsSatInfoFlags("XSIF_HealthFlag_Unhealthy", movelladot_pc_sdkJNI.XSIF_HealthFlag_Unhealthy_get());
  public final static XsSatInfoFlags XSIF_Differential_Mask = new XsSatInfoFlags("XSIF_Differential_Mask", movelladot_pc_sdkJNI.XSIF_Differential_Mask_get());
  public final static XsSatInfoFlags XSIF_Differential_Available = new XsSatInfoFlags("XSIF_Differential_Available", movelladot_pc_sdkJNI.XSIF_Differential_Available_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsSatInfoFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsSatInfoFlags.class + " with value " + swigValue);
  }

  private XsSatInfoFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsSatInfoFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsSatInfoFlags(String swigName, XsSatInfoFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsSatInfoFlags[] swigValues = { XSIF_SignalQualityIndicator_Mask, XSIF_SignalQualityIndicator_NoSignal, XSIF_SignalQualityIndicator_Searching, XSIF_SignalQualityIndicator_Acquired, XSIF_SignalQualityIndicator_Unusable, XSIF_SignalQualityIndicator_CodeTimeOk, XSIF_SignalQualityIndicator_CodeCarrierTimeOk1, XSIF_SignalQualityIndicator_CodeCarrierTimeOk2, XSIF_SignalQualityIndicator_CodeCarrierTimeOk3, XSIF_UsedForNavigation_Mask, XSIF_UsedForNavigation_Used, XSIF_HealthFlag_Mask, XSIF_HealthFlag_Unknown, XSIF_HealthFlag_Healthy, XSIF_HealthFlag_Unhealthy, XSIF_Differential_Mask, XSIF_Differential_Available };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

