
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsSdiData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsSdiData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsSdiData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsSdiData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsSdiData() {
    this(movelladot_pc_sdkJNI.new_XsSdiData__SWIG_0(), true);
  }

  public XsSdiData(XsQuaternion dq, XsVector dv) {
    this(movelladot_pc_sdkJNI.new_XsSdiData__SWIG_1(XsQuaternion.getCPtr(dq), dq, XsVector.getCPtr(dv), dv), true);
  }

  public XsSdiData(XsSdiData other) {
    this(movelladot_pc_sdkJNI.new_XsSdiData__SWIG_2(XsSdiData.getCPtr(other), other), true);
  }

  public void zero() {
    movelladot_pc_sdkJNI.XsSdiData_zero(swigCPtr, this);
  }

  public XsQuaternion orientationIncrement() {
    return new XsQuaternion(movelladot_pc_sdkJNI.XsSdiData_orientationIncrement(swigCPtr, this), false);
  }

  public void setOrientationIncrement(XsQuaternion dq) {
    movelladot_pc_sdkJNI.XsSdiData_setOrientationIncrement(swigCPtr, this, XsQuaternion.getCPtr(dq), dq);
  }

  public XsVector3 velocityIncrement() {
    return new XsVector3(movelladot_pc_sdkJNI.XsSdiData_velocityIncrement(swigCPtr, this), false);
  }

  public void setVelocityIncrement(XsVector dv) {
    movelladot_pc_sdkJNI.XsSdiData_setVelocityIncrement(swigCPtr, this, XsVector.getCPtr(dv), dv);
  }

}
