
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsSimpleVersion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsSimpleVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsSimpleVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsSimpleVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsSimpleVersion(int vmaj, int vmin, int vrev) {
    this(movelladot_pc_sdkJNI.new_XsSimpleVersion__SWIG_0(vmaj, vmin, vrev), true);
  }

  public XsSimpleVersion(int vmaj, int vmin) {
    this(movelladot_pc_sdkJNI.new_XsSimpleVersion__SWIG_1(vmaj, vmin), true);
  }

  public XsSimpleVersion(int vmaj) {
    this(movelladot_pc_sdkJNI.new_XsSimpleVersion__SWIG_2(vmaj), true);
  }

  public XsSimpleVersion() {
    this(movelladot_pc_sdkJNI.new_XsSimpleVersion__SWIG_3(), true);
  }

  public XsSimpleVersion(XsSimpleVersion other) {
    this(movelladot_pc_sdkJNI.new_XsSimpleVersion__SWIG_4(XsSimpleVersion.getCPtr(other), other), true);
  }

  public boolean empty() {
    return movelladot_pc_sdkJNI.XsSimpleVersion_empty(swigCPtr, this);
  }

  public int major() {
    return movelladot_pc_sdkJNI.XsSimpleVersion_major(swigCPtr, this);
  }

  public int minor() {
    return movelladot_pc_sdkJNI.XsSimpleVersion_minor(swigCPtr, this);
  }

  public int revision() {
    return movelladot_pc_sdkJNI.XsSimpleVersion_revision(swigCPtr, this);
  }

  public static XsSimpleVersion osVersion() {
    return new XsSimpleVersion(movelladot_pc_sdkJNI.XsSimpleVersion_osVersion(), true);
  }

}
