
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsString extends XsStringImpl {
  private transient long swigCPtr;

  protected XsString(long cPtr, boolean cMemoryOwn) {
    super(movelladot_pc_sdkJNI.XsString_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsString(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public XsString(long sz, String src) {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_0(sz, src), true);
  }

  public XsString(long sz) {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_1(sz), true);
  }

  public XsString() {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_2(), true);
  }

  public XsString(XsString other) {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_3(XsString.getCPtr(other), other), true);
  }

  public XsString(String ref, long sz, XsDataFlags flags) {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_4(ref, sz, flags.swigValue()), true);
  }

  public XsString(String src) {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_5(src), true);
  }

  public XsString(SWIGTYPE_p_wchar_t src) {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_6(SWIGTYPE_p_wchar_t.getCPtr(src)), true);
  }

  public XsString(SWIGTYPE_p_std__wstring src) {
    this(movelladot_pc_sdkJNI.new_XsString__SWIG_8(SWIGTYPE_p_std__wstring.getCPtr(src)), true);
  }

  public String c_str() {
    return movelladot_pc_sdkJNI.XsString_c_str__SWIG_0(swigCPtr, this);
  }

  public String toString() {
    return movelladot_pc_sdkJNI.XsString_toString(swigCPtr, this);
  }

  public SWIGTYPE_p_std__wstring toStdWString() {
    return new SWIGTYPE_p_std__wstring(movelladot_pc_sdkJNI.XsString_toStdWString(swigCPtr, this), true);
  }

  public boolean empty() {
    return movelladot_pc_sdkJNI.XsString_empty(swigCPtr, this);
  }

  public void append(XsString other) {
    movelladot_pc_sdkJNI.XsString_append__SWIG_0(swigCPtr, this, XsString.getCPtr(other), other);
  }

  public void append(String other) {
    movelladot_pc_sdkJNI.XsString_append__SWIG_1(swigCPtr, this, other);
  }

  public void append(SWIGTYPE_p_wchar_t other) {
    movelladot_pc_sdkJNI.XsString_append__SWIG_2(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(other));
  }

  public long utf8Len() {
    return movelladot_pc_sdkJNI.XsString_utf8Len(swigCPtr, this);
  }

  public boolean endsWith(XsString other, boolean caseSensitive) {
    return movelladot_pc_sdkJNI.XsString_endsWith__SWIG_0(swigCPtr, this, XsString.getCPtr(other), other, caseSensitive);
  }

  public boolean endsWith(XsString other) {
    return movelladot_pc_sdkJNI.XsString_endsWith__SWIG_1(swigCPtr, this, XsString.getCPtr(other), other);
  }

  public boolean startsWith(XsString other, boolean caseSensitive) {
    return movelladot_pc_sdkJNI.XsString_startsWith__SWIG_0(swigCPtr, this, XsString.getCPtr(other), other, caseSensitive);
  }

  public boolean startsWith(XsString other) {
    return movelladot_pc_sdkJNI.XsString_startsWith__SWIG_1(swigCPtr, this, XsString.getCPtr(other), other);
  }

  public boolean contains(XsString other, boolean caseSensitive, SWIGTYPE_p_size_t offset) {
    return movelladot_pc_sdkJNI.XsString_contains__SWIG_0(swigCPtr, this, XsString.getCPtr(other), other, caseSensitive, SWIGTYPE_p_size_t.getCPtr(offset));
  }

  public boolean contains(XsString other, boolean caseSensitive) {
    return movelladot_pc_sdkJNI.XsString_contains__SWIG_1(swigCPtr, this, XsString.getCPtr(other), other, caseSensitive);
  }

  public boolean contains(XsString other) {
    return movelladot_pc_sdkJNI.XsString_contains__SWIG_2(swigCPtr, this, XsString.getCPtr(other), other);
  }

  public SWIGTYPE_p_wchar_t utf8At(long index) {
    return new SWIGTYPE_p_wchar_t(movelladot_pc_sdkJNI.XsString_utf8At(swigCPtr, this, index), true);
  }

  public void sort() {
    movelladot_pc_sdkJNI.XsString_sort(swigCPtr, this);
  }

  public void reverse() {
    movelladot_pc_sdkJNI.XsString_reverse(swigCPtr, this);
  }

  public SWIGTYPE_p_ptrdiff_t findSubStr(XsString needle) {
    return new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkJNI.XsString_findSubStr(swigCPtr, this, XsString.getCPtr(needle), needle), true);
  }

  public XsString mid(long start, long count) {
    return new XsString(movelladot_pc_sdkJNI.XsString_mid(swigCPtr, this, start, count), true);
  }

  public void replaceAll(XsString src, XsString dst) {
    movelladot_pc_sdkJNI.XsString_replaceAll(swigCPtr, this, XsString.getCPtr(src), src, XsString.getCPtr(dst), dst);
  }

  public XsString replacedAll(XsString src, XsString dst) {
    return new XsString(movelladot_pc_sdkJNI.XsString_replacedAll(swigCPtr, this, XsString.getCPtr(src), src, XsString.getCPtr(dst), dst), true);
  }

  public void trim() {
    movelladot_pc_sdkJNI.XsString_trim(swigCPtr, this);
  }

  public XsString trimmed() {
    return new XsString(movelladot_pc_sdkJNI.XsString_trimmed(swigCPtr, this), true);
  }

  public char last() {
    return movelladot_pc_sdkJNI.XsString_last(swigCPtr, this);
  }

  public void toLower() {
    movelladot_pc_sdkJNI.XsString_toLower(swigCPtr, this);
  }

  public void toUpper() {
    movelladot_pc_sdkJNI.XsString_toUpper(swigCPtr, this);
  }

  public XsString lowered() {
    return new XsString(movelladot_pc_sdkJNI.XsString_lowered(swigCPtr, this), true);
  }

  public XsString uppered() {
    return new XsString(movelladot_pc_sdkJNI.XsString_uppered(swigCPtr, this), true);
  }

}
