
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsStringArray extends XsStringArrayImpl {
  private transient long swigCPtr;

  protected XsStringArray(long cPtr, boolean cMemoryOwn) {
    super(movelladot_pc_sdkJNI.XsStringArray_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsStringArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsStringArray(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public XsStringArray(long sz, XsString src) {
    this(movelladot_pc_sdkJNI.new_XsStringArray__SWIG_0(sz, XsString.getCPtr(src), src), true);
  }

  public XsStringArray(long sz) {
    this(movelladot_pc_sdkJNI.new_XsStringArray__SWIG_1(sz), true);
  }

  public XsStringArray() {
    this(movelladot_pc_sdkJNI.new_XsStringArray__SWIG_2(), true);
  }

  public XsStringArray(XsStringArray other) {
    this(movelladot_pc_sdkJNI.new_XsStringArray__SWIG_3(XsStringArray.getCPtr(other), other), true);
  }

  public XsStringArray(XsString ref, long sz, XsDataFlags flags) {
    this(movelladot_pc_sdkJNI.new_XsStringArray__SWIG_4(XsString.getCPtr(ref), ref, sz, flags.swigValue()), true);
  }

  public XsString join(XsString separator) {
    return new XsString(movelladot_pc_sdkJNI.XsStringArray_join(swigCPtr, this, XsString.getCPtr(separator), separator), true);
  }

  public void fromSplicedString(XsString src, XsString separators) {
    movelladot_pc_sdkJNI.XsStringArray_fromSplicedString(swigCPtr, this, XsString.getCPtr(src), src, XsString.getCPtr(separators), separators);
  }

  public XsStringArray(XsString src, XsString separators) {
    this(movelladot_pc_sdkJNI.new_XsStringArray__SWIG_5(XsString.getCPtr(src), src, XsString.getCPtr(separators), separators), true);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsString needle, boolean isCaseSensitive) {
    return new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkJNI.XsStringArray_find__SWIG_0(swigCPtr, this, XsString.getCPtr(needle), needle, isCaseSensitive), true);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsString needle) {
    return new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkJNI.XsStringArray_find__SWIG_1(swigCPtr, this, XsString.getCPtr(needle), needle), true);
  }

  public SWIGTYPE_p_ptrdiff_t findPrefix(XsString needle, boolean isCaseSensitive) {
    return new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkJNI.XsStringArray_findPrefix__SWIG_0(swigCPtr, this, XsString.getCPtr(needle), needle, isCaseSensitive), true);
  }

  public SWIGTYPE_p_ptrdiff_t findPrefix(XsString needle) {
    return new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkJNI.XsStringArray_findPrefix__SWIG_1(swigCPtr, this, XsString.getCPtr(needle), needle), true);
  }

}
