
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsTimeInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsTimeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsTimeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsTimeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_nano(long value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_nano_set(swigCPtr, this, value);
  }

  public long getM_nano() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_nano_get(swigCPtr, this);
  }

  public void setM_year(int value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_year_set(swigCPtr, this, value);
  }

  public int getM_year() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_year_get(swigCPtr, this);
  }

  public void setM_month(short value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_month_set(swigCPtr, this, value);
  }

  public short getM_month() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_month_get(swigCPtr, this);
  }

  public void setM_day(short value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_day_set(swigCPtr, this, value);
  }

  public short getM_day() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_day_get(swigCPtr, this);
  }

  public void setM_hour(short value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_hour_set(swigCPtr, this, value);
  }

  public short getM_hour() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_hour_get(swigCPtr, this);
  }

  public void setM_minute(short value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_minute_set(swigCPtr, this, value);
  }

  public short getM_minute() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_minute_get(swigCPtr, this);
  }

  public void setM_second(short value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_second_set(swigCPtr, this, value);
  }

  public short getM_second() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_second_get(swigCPtr, this);
  }

  public void setM_valid(short value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_valid_set(swigCPtr, this, value);
  }

  public short getM_valid() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_valid_get(swigCPtr, this);
  }

  public void setM_utcOffset(short value) {
    movelladot_pc_sdkJNI.XsTimeInfo_m_utcOffset_set(swigCPtr, this, value);
  }

  public short getM_utcOffset() {
    return movelladot_pc_sdkJNI.XsTimeInfo_m_utcOffset_get(swigCPtr, this);
  }

  public void clear() {
    movelladot_pc_sdkJNI.XsTimeInfo_clear(swigCPtr, this);
  }

  public static XsTimeInfo currentTime() {
    return new XsTimeInfo(movelladot_pc_sdkJNI.XsTimeInfo_currentTime(), true);
  }

  public static XsTimeInfo currentLocalTime() {
    return new XsTimeInfo(movelladot_pc_sdkJNI.XsTimeInfo_currentLocalTime(), true);
  }

  public void makeUtc() {
    movelladot_pc_sdkJNI.XsTimeInfo_makeUtc(swigCPtr, this);
  }

  public XsTimeInfo() {
    this(movelladot_pc_sdkJNI.new_XsTimeInfo(), true);
  }

}
