
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsTimeStamp {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsTimeStamp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsTimeStamp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsTimeStamp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsTimeStamp(long t) {
    this(movelladot_pc_sdkJNI.new_XsTimeStamp__SWIG_0(t), true);
  }

  public XsTimeStamp() {
    this(movelladot_pc_sdkJNI.new_XsTimeStamp__SWIG_1(), true);
  }

  public XsTimeStamp(int t) {
    this(movelladot_pc_sdkJNI.new_XsTimeStamp__SWIG_2(t), true);
  }

  public XsTimeStamp(double t) {
    this(movelladot_pc_sdkJNI.new_XsTimeStamp__SWIG_3(t), true);
  }

  public XsTimeStamp(XsTimeStamp other) {
    this(movelladot_pc_sdkJNI.new_XsTimeStamp__SWIG_4(XsTimeStamp.getCPtr(other), other), true);
  }

  public XsTimeStamp(XsTimeInfo info) {
    this(movelladot_pc_sdkJNI.new_XsTimeStamp__SWIG_5(XsTimeInfo.getCPtr(info), info), true);
  }

  public XsTimeInfo toTimeInfo() {
    return new XsTimeInfo(movelladot_pc_sdkJNI.XsTimeStamp_toTimeInfo__SWIG_0(swigCPtr, this), true);
  }

  public void toTimeInfo(XsTimeInfo info) {
    movelladot_pc_sdkJNI.XsTimeStamp_toTimeInfo__SWIG_1(swigCPtr, this, XsTimeInfo.getCPtr(info), info);
  }

  public XsString toXsString() {
    return new XsString(movelladot_pc_sdkJNI.XsTimeStamp_toXsString(swigCPtr, this), true);
  }

  public long msTime() {
    return movelladot_pc_sdkJNI.XsTimeStamp_msTime(swigCPtr, this);
  }

  public void setMsTime(long t) {
    movelladot_pc_sdkJNI.XsTimeStamp_setMsTime(swigCPtr, this, t);
  }

  public double timeOfDay() {
    return movelladot_pc_sdkJNI.XsTimeStamp_timeOfDay(swigCPtr, this);
  }

  public long msTimeOfDay() {
    return movelladot_pc_sdkJNI.XsTimeStamp_msTimeOfDay(swigCPtr, this);
  }

  public double secTime() {
    return movelladot_pc_sdkJNI.XsTimeStamp_secTime(swigCPtr, this);
  }

  public void setSecTime(double t) {
    movelladot_pc_sdkJNI.XsTimeStamp_setSecTime(swigCPtr, this, t);
  }

  public long secondTime() {
    return movelladot_pc_sdkJNI.XsTimeStamp_secondTime(swigCPtr, this);
  }

  public int milliSecondPart() {
    return movelladot_pc_sdkJNI.XsTimeStamp_milliSecondPart(swigCPtr, this);
  }

  public int secondPart() {
    return movelladot_pc_sdkJNI.XsTimeStamp_secondPart(swigCPtr, this);
  }

  public int minutePart() {
    return movelladot_pc_sdkJNI.XsTimeStamp_minutePart(swigCPtr, this);
  }

  public int hourPart() {
    return movelladot_pc_sdkJNI.XsTimeStamp_hourPart(swigCPtr, this);
  }

  public static XsTimeStamp now() {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_now(), true);
  }

  public static long nowMs() {
    return movelladot_pc_sdkJNI.XsTimeStamp_nowMs();
  }

  public long elapsedToNow() {
    return movelladot_pc_sdkJNI.XsTimeStamp_elapsedToNow(swigCPtr, this);
  }

  public static XsTimeStamp maxValue() {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_maxValue(), true);
  }

  public XsTimeStamp utcToLocalTime() {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_utcToLocalTime__SWIG_0(swigCPtr, this), true);
  }

  public XsTimeStamp localToUtcTime() {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_localToUtcTime__SWIG_0(swigCPtr, this), true);
  }

  public XsTimeStamp utcToLocalTime(XsTimeInfo info) {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_utcToLocalTime__SWIG_1(swigCPtr, this, XsTimeInfo.getCPtr(info), info), true);
  }

  public XsTimeStamp localToUtcTime(XsTimeInfo info) {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_localToUtcTime__SWIG_1(swigCPtr, this, XsTimeInfo.getCPtr(info), info), true);
  }

  public XsTimeStamp utcToLocalTime(long utcOffset) {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_utcToLocalTime__SWIG_2(swigCPtr, this, utcOffset), true);
  }

  public XsTimeStamp localToUtcTime(long utcOffset) {
    return new XsTimeStamp(movelladot_pc_sdkJNI.XsTimeStamp_localToUtcTime__SWIG_2(swigCPtr, this, utcOffset), true);
  }

}
