
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public class XsVersion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsVersion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsVersion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        movelladot_pc_sdkJNI.delete_XsVersion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsVersion(int maj, int min, int rev, int build, XsString extra) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_0(maj, min, rev, build, XsString.getCPtr(extra), extra), true);
  }

  public XsVersion(int maj, int min, int rev, int build, int reposVersion, XsString extra) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_1(maj, min, rev, build, reposVersion, XsString.getCPtr(extra), extra), true);
  }

  public XsVersion(int maj, int min, int rev, int build, int reposVersion) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_2(maj, min, rev, build, reposVersion), true);
  }

  public XsVersion(int maj, int min, int rev, int build) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_3(maj, min, rev, build), true);
  }

  public XsVersion(int maj, int min, int rev) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_4(maj, min, rev), true);
  }

  public XsVersion(int maj, int min) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_5(maj, min), true);
  }

  public XsVersion(int maj) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_6(maj), true);
  }

  public XsVersion() {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_7(), true);
  }

  public XsVersion(XsString vString) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_8(XsString.getCPtr(vString), vString), true);
  }

  public XsVersion(XsSimpleVersion simpleVersion) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_9(XsSimpleVersion.getCPtr(simpleVersion), simpleVersion), true);
  }

  public XsVersion(XsVersion other) {
    this(movelladot_pc_sdkJNI.new_XsVersion__SWIG_10(XsVersion.getCPtr(other), other), true);
  }

  public boolean isEqual(XsVersion other) {
    return movelladot_pc_sdkJNI.XsVersion_isEqual(swigCPtr, this, XsVersion.getCPtr(other), other);
  }

  public boolean empty() {
    return movelladot_pc_sdkJNI.XsVersion_empty(swigCPtr, this);
  }

  public XsString toXsString() {
    return new XsString(movelladot_pc_sdkJNI.XsVersion_toXsString(swigCPtr, this), true);
  }

  public XsString toSimpleString() {
    return new XsString(movelladot_pc_sdkJNI.XsVersion_toSimpleString(swigCPtr, this), true);
  }

  public XsSimpleVersion toSimpleVersion() {
    return new XsSimpleVersion(movelladot_pc_sdkJNI.XsVersion_toSimpleVersion(swigCPtr, this), true);
  }

  public int major() {
    return movelladot_pc_sdkJNI.XsVersion_major(swigCPtr, this);
  }

  public int minor() {
    return movelladot_pc_sdkJNI.XsVersion_minor(swigCPtr, this);
  }

  public int revision() {
    return movelladot_pc_sdkJNI.XsVersion_revision(swigCPtr, this);
  }

  public int build() {
    return movelladot_pc_sdkJNI.XsVersion_build(swigCPtr, this);
  }

  public int reposVersion() {
    return movelladot_pc_sdkJNI.XsVersion_reposVersion(swigCPtr, this);
  }

  public XsString extra() {
    return new XsString(movelladot_pc_sdkJNI.XsVersion_extra(swigCPtr, this), false);
  }

  public void setMajor(int major) {
    movelladot_pc_sdkJNI.XsVersion_setMajor(swigCPtr, this, major);
  }

  public void setMinor(int minor) {
    movelladot_pc_sdkJNI.XsVersion_setMinor(swigCPtr, this, minor);
  }

  public void setRevision(int revision) {
    movelladot_pc_sdkJNI.XsVersion_setRevision(swigCPtr, this, revision);
  }

  public void setBuild(int build) {
    movelladot_pc_sdkJNI.XsVersion_setBuild(swigCPtr, this, build);
  }

  public void setReposVersion(int reposVersion) {
    movelladot_pc_sdkJNI.XsVersion_setReposVersion(swigCPtr, this, reposVersion);
  }

  public void setExtra(XsString extra) {
    movelladot_pc_sdkJNI.XsVersion_setExtra(swigCPtr, this, XsString.getCPtr(extra), extra);
  }

}
