
//  Copyright (c) 2003-2023 Movella Technologies B.V. or subsidiaries worldwide.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//  
//  1.	Redistributions of source code must retain the above copyright notice,
//  	this list of conditions and the following disclaimer.
//  
//  2.	Redistributions in binary form must reproduce the above copyright notice,
//  	this list of conditions and the following disclaimer in the documentation
//  	and/or other materials provided with the distribution.
//  
//  3.	Neither the names of the copyright holders nor the names of their contributors
//  	may be used to endorse or promote products derived from this software without
//  	specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
//  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
//  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
//  THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
//  SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
//  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY OR
//  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//  

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.movella.movelladot_pc_sdk;

public final class XsXbusMessageId {
  public final static XsXbusMessageId XMID_InvalidMessage = new XsXbusMessageId("XMID_InvalidMessage", movelladot_pc_sdkJNI.XMID_InvalidMessage_get());
  public final static XsXbusMessageId XMID_ReqDid = new XsXbusMessageId("XMID_ReqDid", movelladot_pc_sdkJNI.XMID_ReqDid_get());
  public final static XsXbusMessageId XMID_DeviceId = new XsXbusMessageId("XMID_DeviceId", movelladot_pc_sdkJNI.XMID_DeviceId_get());
  public final static XsXbusMessageId XMID_Initbus = new XsXbusMessageId("XMID_Initbus", movelladot_pc_sdkJNI.XMID_Initbus_get());
  public final static XsXbusMessageId XMID_InitBusResults = new XsXbusMessageId("XMID_InitBusResults", movelladot_pc_sdkJNI.XMID_InitBusResults_get());
  public final static XsXbusMessageId XMID_ReqPeriod = new XsXbusMessageId("XMID_ReqPeriod", movelladot_pc_sdkJNI.XMID_ReqPeriod_get());
  public final static XsXbusMessageId XMID_ReqPeriodAck = new XsXbusMessageId("XMID_ReqPeriodAck", movelladot_pc_sdkJNI.XMID_ReqPeriodAck_get());
  public final static XsXbusMessageId XMID_SetPeriod = new XsXbusMessageId("XMID_SetPeriod", movelladot_pc_sdkJNI.XMID_SetPeriod_get());
  public final static XsXbusMessageId XMID_SetPeriodAck = new XsXbusMessageId("XMID_SetPeriodAck", movelladot_pc_sdkJNI.XMID_SetPeriodAck_get());
  public final static XsXbusMessageId XMID_SetBid = new XsXbusMessageId("XMID_SetBid", movelladot_pc_sdkJNI.XMID_SetBid_get());
  public final static XsXbusMessageId XMID_SetBidAck = new XsXbusMessageId("XMID_SetBidAck", movelladot_pc_sdkJNI.XMID_SetBidAck_get());
  public final static XsXbusMessageId XMID_AutoStart = new XsXbusMessageId("XMID_AutoStart", movelladot_pc_sdkJNI.XMID_AutoStart_get());
  public final static XsXbusMessageId XMID_AutoStartAck = new XsXbusMessageId("XMID_AutoStartAck", movelladot_pc_sdkJNI.XMID_AutoStartAck_get());
  public final static XsXbusMessageId XMID_BusPower = new XsXbusMessageId("XMID_BusPower", movelladot_pc_sdkJNI.XMID_BusPower_get());
  public final static XsXbusMessageId XMID_BusPowerAck = new XsXbusMessageId("XMID_BusPowerAck", movelladot_pc_sdkJNI.XMID_BusPowerAck_get());
  public final static XsXbusMessageId XMID_ReqDataLength = new XsXbusMessageId("XMID_ReqDataLength", movelladot_pc_sdkJNI.XMID_ReqDataLength_get());
  public final static XsXbusMessageId XMID_DataLength = new XsXbusMessageId("XMID_DataLength", movelladot_pc_sdkJNI.XMID_DataLength_get());
  public final static XsXbusMessageId XMID_ReqConfiguration = new XsXbusMessageId("XMID_ReqConfiguration", movelladot_pc_sdkJNI.XMID_ReqConfiguration_get());
  public final static XsXbusMessageId XMID_Configuration = new XsXbusMessageId("XMID_Configuration", movelladot_pc_sdkJNI.XMID_Configuration_get());
  public final static XsXbusMessageId XMID_RestoreFactoryDef = new XsXbusMessageId("XMID_RestoreFactoryDef", movelladot_pc_sdkJNI.XMID_RestoreFactoryDef_get());
  public final static XsXbusMessageId XMID_RestoreFactoryDefAck = new XsXbusMessageId("XMID_RestoreFactoryDefAck", movelladot_pc_sdkJNI.XMID_RestoreFactoryDefAck_get());
  public final static XsXbusMessageId XMID_GotoMeasurement = new XsXbusMessageId("XMID_GotoMeasurement", movelladot_pc_sdkJNI.XMID_GotoMeasurement_get());
  public final static XsXbusMessageId XMID_GotoMeasurementAck = new XsXbusMessageId("XMID_GotoMeasurementAck", movelladot_pc_sdkJNI.XMID_GotoMeasurementAck_get());
  public final static XsXbusMessageId XMID_ReqFirmwareRevision = new XsXbusMessageId("XMID_ReqFirmwareRevision", movelladot_pc_sdkJNI.XMID_ReqFirmwareRevision_get());
  public final static XsXbusMessageId XMID_FirmwareRevision = new XsXbusMessageId("XMID_FirmwareRevision", movelladot_pc_sdkJNI.XMID_FirmwareRevision_get());
  public final static XsXbusMessageId XMID_ReqUniqueId = new XsXbusMessageId("XMID_ReqUniqueId", movelladot_pc_sdkJNI.XMID_ReqUniqueId_get());
  public final static XsXbusMessageId XMID_UniqueId = new XsXbusMessageId("XMID_UniqueId", movelladot_pc_sdkJNI.XMID_UniqueId_get());
  public final static XsXbusMessageId XMID_ReqBodypackMode = new XsXbusMessageId("XMID_ReqBodypackMode", movelladot_pc_sdkJNI.XMID_ReqBodypackMode_get());
  public final static XsXbusMessageId XMID_ReqBodypackAck = new XsXbusMessageId("XMID_ReqBodypackAck", movelladot_pc_sdkJNI.XMID_ReqBodypackAck_get());
  public final static XsXbusMessageId XMID_SetBodypackMode = new XsXbusMessageId("XMID_SetBodypackMode", movelladot_pc_sdkJNI.XMID_SetBodypackMode_get());
  public final static XsXbusMessageId XMID_SetBodypackModeAck = new XsXbusMessageId("XMID_SetBodypackModeAck", movelladot_pc_sdkJNI.XMID_SetBodypackModeAck_get());
  public final static XsXbusMessageId XMID_ReqBaudrate = new XsXbusMessageId("XMID_ReqBaudrate", movelladot_pc_sdkJNI.XMID_ReqBaudrate_get());
  public final static XsXbusMessageId XMID_ReqBaudrateAck = new XsXbusMessageId("XMID_ReqBaudrateAck", movelladot_pc_sdkJNI.XMID_ReqBaudrateAck_get());
  public final static XsXbusMessageId XMID_SetBaudrate = new XsXbusMessageId("XMID_SetBaudrate", movelladot_pc_sdkJNI.XMID_SetBaudrate_get());
  public final static XsXbusMessageId XMID_SetBaudrateAck = new XsXbusMessageId("XMID_SetBaudrateAck", movelladot_pc_sdkJNI.XMID_SetBaudrateAck_get());
  public final static XsXbusMessageId XMID_ReqProductVariant = new XsXbusMessageId("XMID_ReqProductVariant", movelladot_pc_sdkJNI.XMID_ReqProductVariant_get());
  public final static XsXbusMessageId XMID_ProductVariant = new XsXbusMessageId("XMID_ProductVariant", movelladot_pc_sdkJNI.XMID_ProductVariant_get());
  public final static XsXbusMessageId XMID_ReqProductCode = new XsXbusMessageId("XMID_ReqProductCode", movelladot_pc_sdkJNI.XMID_ReqProductCode_get());
  public final static XsXbusMessageId XMID_ProductCode = new XsXbusMessageId("XMID_ProductCode", movelladot_pc_sdkJNI.XMID_ProductCode_get());
  public final static XsXbusMessageId XMID_ReqHardwareVersion = new XsXbusMessageId("XMID_ReqHardwareVersion", movelladot_pc_sdkJNI.XMID_ReqHardwareVersion_get());
  public final static XsXbusMessageId XMID_HardwareVersion = new XsXbusMessageId("XMID_HardwareVersion", movelladot_pc_sdkJNI.XMID_HardwareVersion_get());
  public final static XsXbusMessageId XMID_ReqProcessingFlags = new XsXbusMessageId("XMID_ReqProcessingFlags", movelladot_pc_sdkJNI.XMID_ReqProcessingFlags_get());
  public final static XsXbusMessageId XMID_ReqProcessingFlagsAck = new XsXbusMessageId("XMID_ReqProcessingFlagsAck", movelladot_pc_sdkJNI.XMID_ReqProcessingFlagsAck_get());
  public final static XsXbusMessageId XMID_SetProcessingFlags = new XsXbusMessageId("XMID_SetProcessingFlags", movelladot_pc_sdkJNI.XMID_SetProcessingFlags_get());
  public final static XsXbusMessageId XMID_SetProcessingFlagsAck = new XsXbusMessageId("XMID_SetProcessingFlagsAck", movelladot_pc_sdkJNI.XMID_SetProcessingFlagsAck_get());
  public final static XsXbusMessageId XMID_SetNoRotation = new XsXbusMessageId("XMID_SetNoRotation", movelladot_pc_sdkJNI.XMID_SetNoRotation_get());
  public final static XsXbusMessageId XMID_SetNoRotationAck = new XsXbusMessageId("XMID_SetNoRotationAck", movelladot_pc_sdkJNI.XMID_SetNoRotationAck_get());
  public final static XsXbusMessageId XMID_RunSelfTest = new XsXbusMessageId("XMID_RunSelfTest", movelladot_pc_sdkJNI.XMID_RunSelfTest_get());
  public final static XsXbusMessageId XMID_SelfTestResults = new XsXbusMessageId("XMID_SelfTestResults", movelladot_pc_sdkJNI.XMID_SelfTestResults_get());
  public final static XsXbusMessageId XMID_ReqInputTrigger = new XsXbusMessageId("XMID_ReqInputTrigger", movelladot_pc_sdkJNI.XMID_ReqInputTrigger_get());
  public final static XsXbusMessageId XMID_ReqInputTriggerAck = new XsXbusMessageId("XMID_ReqInputTriggerAck", movelladot_pc_sdkJNI.XMID_ReqInputTriggerAck_get());
  public final static XsXbusMessageId XMID_SetInputTrigger = new XsXbusMessageId("XMID_SetInputTrigger", movelladot_pc_sdkJNI.XMID_SetInputTrigger_get());
  public final static XsXbusMessageId XMID_SetInputTriggerAck = new XsXbusMessageId("XMID_SetInputTriggerAck", movelladot_pc_sdkJNI.XMID_SetInputTriggerAck_get());
  public final static XsXbusMessageId XMID_ReqOutputTrigger = new XsXbusMessageId("XMID_ReqOutputTrigger", movelladot_pc_sdkJNI.XMID_ReqOutputTrigger_get());
  public final static XsXbusMessageId XMID_ReqOutputTriggerAck = new XsXbusMessageId("XMID_ReqOutputTriggerAck", movelladot_pc_sdkJNI.XMID_ReqOutputTriggerAck_get());
  public final static XsXbusMessageId XMID_SetOutputTrigger = new XsXbusMessageId("XMID_SetOutputTrigger", movelladot_pc_sdkJNI.XMID_SetOutputTrigger_get());
  public final static XsXbusMessageId XMID_SetOutputTriggerAck = new XsXbusMessageId("XMID_SetOutputTriggerAck", movelladot_pc_sdkJNI.XMID_SetOutputTriggerAck_get());
  public final static XsXbusMessageId XMID_SetSyncStationMode = new XsXbusMessageId("XMID_SetSyncStationMode", movelladot_pc_sdkJNI.XMID_SetSyncStationMode_get());
  public final static XsXbusMessageId XMID_SetSyncStationModeAck = new XsXbusMessageId("XMID_SetSyncStationModeAck", movelladot_pc_sdkJNI.XMID_SetSyncStationModeAck_get());
  public final static XsXbusMessageId XMID_ReqSyncStationMode = new XsXbusMessageId("XMID_ReqSyncStationMode", movelladot_pc_sdkJNI.XMID_ReqSyncStationMode_get());
  public final static XsXbusMessageId XMID_ReqSyncStationModeAck = new XsXbusMessageId("XMID_ReqSyncStationModeAck", movelladot_pc_sdkJNI.XMID_ReqSyncStationModeAck_get());
  public final static XsXbusMessageId XMID_SetSyncConfiguration = new XsXbusMessageId("XMID_SetSyncConfiguration", movelladot_pc_sdkJNI.XMID_SetSyncConfiguration_get());
  public final static XsXbusMessageId XMID_SetSyncConfigurationAck = new XsXbusMessageId("XMID_SetSyncConfigurationAck", movelladot_pc_sdkJNI.XMID_SetSyncConfigurationAck_get());
  public final static XsXbusMessageId XMID_ReqSyncConfiguration = new XsXbusMessageId("XMID_ReqSyncConfiguration", movelladot_pc_sdkJNI.XMID_ReqSyncConfiguration_get());
  public final static XsXbusMessageId XMID_SyncConfiguration = new XsXbusMessageId("XMID_SyncConfiguration", movelladot_pc_sdkJNI.XMID_SyncConfiguration_get());
  public final static XsXbusMessageId XMID_DriverDisconnect = new XsXbusMessageId("XMID_DriverDisconnect", movelladot_pc_sdkJNI.XMID_DriverDisconnect_get());
  public final static XsXbusMessageId XMID_DriverDisconnectAck = new XsXbusMessageId("XMID_DriverDisconnectAck", movelladot_pc_sdkJNI.XMID_DriverDisconnectAck_get());
  public final static XsXbusMessageId XMID_GotoConfig = new XsXbusMessageId("XMID_GotoConfig", movelladot_pc_sdkJNI.XMID_GotoConfig_get());
  public final static XsXbusMessageId XMID_GotoConfigAck = new XsXbusMessageId("XMID_GotoConfigAck", movelladot_pc_sdkJNI.XMID_GotoConfigAck_get());
  public final static XsXbusMessageId XMID_MtData = new XsXbusMessageId("XMID_MtData", movelladot_pc_sdkJNI.XMID_MtData_get());
  public final static XsXbusMessageId XMID_BusData = new XsXbusMessageId("XMID_BusData", movelladot_pc_sdkJNI.XMID_BusData_get());
  public final static XsXbusMessageId XMID_PrepareData = new XsXbusMessageId("XMID_PrepareData", movelladot_pc_sdkJNI.XMID_PrepareData_get());
  public final static XsXbusMessageId XMID_ReqData = new XsXbusMessageId("XMID_ReqData", movelladot_pc_sdkJNI.XMID_ReqData_get());
  public final static XsXbusMessageId XMID_ReqDataAck = new XsXbusMessageId("XMID_ReqDataAck", movelladot_pc_sdkJNI.XMID_ReqDataAck_get());
  public final static XsXbusMessageId XMID_MtData2 = new XsXbusMessageId("XMID_MtData2", movelladot_pc_sdkJNI.XMID_MtData2_get());
  public final static XsXbusMessageId XMID_MtData2Ack = new XsXbusMessageId("XMID_MtData2Ack", movelladot_pc_sdkJNI.XMID_MtData2Ack_get());
  public final static XsXbusMessageId XMID_RequestControl = new XsXbusMessageId("XMID_RequestControl", movelladot_pc_sdkJNI.XMID_RequestControl_get());
  public final static XsXbusMessageId XMID_RequestControlAck = new XsXbusMessageId("XMID_RequestControlAck", movelladot_pc_sdkJNI.XMID_RequestControlAck_get());
  public final static XsXbusMessageId XMID_SetDataPort = new XsXbusMessageId("XMID_SetDataPort", movelladot_pc_sdkJNI.XMID_SetDataPort_get());
  public final static XsXbusMessageId XMID_SetDataPortAck = new XsXbusMessageId("XMID_SetDataPortAck", movelladot_pc_sdkJNI.XMID_SetDataPortAck_get());
  public final static XsXbusMessageId XMID_ReqRetransmission = new XsXbusMessageId("XMID_ReqRetransmission", movelladot_pc_sdkJNI.XMID_ReqRetransmission_get());
  public final static XsXbusMessageId XMID_ReqRetransmissionAck = new XsXbusMessageId("XMID_ReqRetransmissionAck", movelladot_pc_sdkJNI.XMID_ReqRetransmissionAck_get());
  public final static XsXbusMessageId XMID_Wakeup = new XsXbusMessageId("XMID_Wakeup", movelladot_pc_sdkJNI.XMID_Wakeup_get());
  public final static XsXbusMessageId XMID_WakeupAck = new XsXbusMessageId("XMID_WakeupAck", movelladot_pc_sdkJNI.XMID_WakeupAck_get());
  public final static XsXbusMessageId XMID_Reset = new XsXbusMessageId("XMID_Reset", movelladot_pc_sdkJNI.XMID_Reset_get());
  public final static XsXbusMessageId XMID_ResetAck = new XsXbusMessageId("XMID_ResetAck", movelladot_pc_sdkJNI.XMID_ResetAck_get());
  public final static XsXbusMessageId XMID_Error = new XsXbusMessageId("XMID_Error", movelladot_pc_sdkJNI.XMID_Error_get());
  public final static XsXbusMessageId XMID_Warning = new XsXbusMessageId("XMID_Warning", movelladot_pc_sdkJNI.XMID_Warning_get());
  public final static XsXbusMessageId XMID_XmPowerOff = new XsXbusMessageId("XMID_XmPowerOff", movelladot_pc_sdkJNI.XMID_XmPowerOff_get());
  public final static XsXbusMessageId XMID_MasterIndication = new XsXbusMessageId("XMID_MasterIndication", movelladot_pc_sdkJNI.XMID_MasterIndication_get());
  public final static XsXbusMessageId XMID_XsbData = new XsXbusMessageId("XMID_XsbData", movelladot_pc_sdkJNI.XMID_XsbData_get());
  public final static XsXbusMessageId XMID_ReqOptionFlags = new XsXbusMessageId("XMID_ReqOptionFlags", movelladot_pc_sdkJNI.XMID_ReqOptionFlags_get());
  public final static XsXbusMessageId XMID_ReqOptionFlagsAck = new XsXbusMessageId("XMID_ReqOptionFlagsAck", movelladot_pc_sdkJNI.XMID_ReqOptionFlagsAck_get());
  public final static XsXbusMessageId XMID_SetOptionFlags = new XsXbusMessageId("XMID_SetOptionFlags", movelladot_pc_sdkJNI.XMID_SetOptionFlags_get());
  public final static XsXbusMessageId XMID_SetOptionFlagsAck = new XsXbusMessageId("XMID_SetOptionFlagsAck", movelladot_pc_sdkJNI.XMID_SetOptionFlagsAck_get());
  public final static XsXbusMessageId XMID_ReqStealthMode = new XsXbusMessageId("XMID_ReqStealthMode", movelladot_pc_sdkJNI.XMID_ReqStealthMode_get());
  public final static XsXbusMessageId XMID_StealthMode = new XsXbusMessageId("XMID_StealthMode", movelladot_pc_sdkJNI.XMID_StealthMode_get());
  public final static XsXbusMessageId XMID_SetStealthMode = new XsXbusMessageId("XMID_SetStealthMode", movelladot_pc_sdkJNI.XMID_SetStealthMode_get());
  public final static XsXbusMessageId XMID_SetStealthModeAck = new XsXbusMessageId("XMID_SetStealthModeAck", movelladot_pc_sdkJNI.XMID_SetStealthModeAck_get());
  public final static XsXbusMessageId XMID_UserInterface = new XsXbusMessageId("XMID_UserInterface", movelladot_pc_sdkJNI.XMID_UserInterface_get());
  public final static XsXbusMessageId XMID_UserInterfaceAck = new XsXbusMessageId("XMID_UserInterfaceAck", movelladot_pc_sdkJNI.XMID_UserInterfaceAck_get());
  public final static XsXbusMessageId XMID_EndOfRecording = new XsXbusMessageId("XMID_EndOfRecording", movelladot_pc_sdkJNI.XMID_EndOfRecording_get());
  public final static XsXbusMessageId XMID_EndOfRecordingAck = new XsXbusMessageId("XMID_EndOfRecordingAck", movelladot_pc_sdkJNI.XMID_EndOfRecordingAck_get());
  public final static XsXbusMessageId XMID_GotoTransparentMode = new XsXbusMessageId("XMID_GotoTransparentMode", movelladot_pc_sdkJNI.XMID_GotoTransparentMode_get());
  public final static XsXbusMessageId XMID_GotoTransparentModeAck = new XsXbusMessageId("XMID_GotoTransparentModeAck", movelladot_pc_sdkJNI.XMID_GotoTransparentModeAck_get());
  public final static XsXbusMessageId XMID_ReqDeviceCapabilities = new XsXbusMessageId("XMID_ReqDeviceCapabilities", movelladot_pc_sdkJNI.XMID_ReqDeviceCapabilities_get());
  public final static XsXbusMessageId XMID_DeviceCapabilities = new XsXbusMessageId("XMID_DeviceCapabilities", movelladot_pc_sdkJNI.XMID_DeviceCapabilities_get());
  public final static XsXbusMessageId XMID_DiscardRetransmissions = new XsXbusMessageId("XMID_DiscardRetransmissions", movelladot_pc_sdkJNI.XMID_DiscardRetransmissions_get());
  public final static XsXbusMessageId XMID_DiscardRetransmissionsAck = new XsXbusMessageId("XMID_DiscardRetransmissionsAck", movelladot_pc_sdkJNI.XMID_DiscardRetransmissionsAck_get());
  public final static XsXbusMessageId XMID_RunFactoryTest = new XsXbusMessageId("XMID_RunFactoryTest", movelladot_pc_sdkJNI.XMID_RunFactoryTest_get());
  public final static XsXbusMessageId XMID_FactoryTestResults = new XsXbusMessageId("XMID_FactoryTestResults", movelladot_pc_sdkJNI.XMID_FactoryTestResults_get());
  public final static XsXbusMessageId XMID_FactoryTestConnect = new XsXbusMessageId("XMID_FactoryTestConnect", movelladot_pc_sdkJNI.XMID_FactoryTestConnect_get());
  public final static XsXbusMessageId XMID_FactoryTestConnectAck = new XsXbusMessageId("XMID_FactoryTestConnectAck", movelladot_pc_sdkJNI.XMID_FactoryTestConnectAck_get());
  public final static XsXbusMessageId XMID_SetDataOutputDelay = new XsXbusMessageId("XMID_SetDataOutputDelay", movelladot_pc_sdkJNI.XMID_SetDataOutputDelay_get());
  public final static XsXbusMessageId XMID_SetDataOutputDelayAck = new XsXbusMessageId("XMID_SetDataOutputDelayAck", movelladot_pc_sdkJNI.XMID_SetDataOutputDelayAck_get());
  public final static XsXbusMessageId XMID_SetBodypackConfigFile = new XsXbusMessageId("XMID_SetBodypackConfigFile", movelladot_pc_sdkJNI.XMID_SetBodypackConfigFile_get());
  public final static XsXbusMessageId XMID_SetBodypackConfigFileAck = new XsXbusMessageId("XMID_SetBodypackConfigFileAck", movelladot_pc_sdkJNI.XMID_SetBodypackConfigFileAck_get());
  public final static XsXbusMessageId XMID_ReqObrStatus = new XsXbusMessageId("XMID_ReqObrStatus", movelladot_pc_sdkJNI.XMID_ReqObrStatus_get());
  public final static XsXbusMessageId XMID_ObrStatus = new XsXbusMessageId("XMID_ObrStatus", movelladot_pc_sdkJNI.XMID_ObrStatus_get());
  public final static XsXbusMessageId XMID_SetUtcTime = new XsXbusMessageId("XMID_SetUtcTime", movelladot_pc_sdkJNI.XMID_SetUtcTime_get());
  public final static XsXbusMessageId XMID_ReqUtcTime = new XsXbusMessageId("XMID_ReqUtcTime", movelladot_pc_sdkJNI.XMID_ReqUtcTime_get());
  public final static XsXbusMessageId XMID_SetUtcTimeAck = new XsXbusMessageId("XMID_SetUtcTimeAck", movelladot_pc_sdkJNI.XMID_SetUtcTimeAck_get());
  public final static XsXbusMessageId XMID_UtcTime = new XsXbusMessageId("XMID_UtcTime", movelladot_pc_sdkJNI.XMID_UtcTime_get());
  public final static XsXbusMessageId XMID_FactoryTestSensorTiming = new XsXbusMessageId("XMID_FactoryTestSensorTiming", movelladot_pc_sdkJNI.XMID_FactoryTestSensorTiming_get());
  public final static XsXbusMessageId XMID_FactoryTestSensorTimingResults = new XsXbusMessageId("XMID_FactoryTestSensorTimingResults", movelladot_pc_sdkJNI.XMID_FactoryTestSensorTimingResults_get());
  public final static XsXbusMessageId XMID_ReqAvailableFilterProfiles = new XsXbusMessageId("XMID_ReqAvailableFilterProfiles", movelladot_pc_sdkJNI.XMID_ReqAvailableFilterProfiles_get());
  public final static XsXbusMessageId XMID_AvailableFilterProfiles = new XsXbusMessageId("XMID_AvailableFilterProfiles", movelladot_pc_sdkJNI.XMID_AvailableFilterProfiles_get());
  public final static XsXbusMessageId XMID_ReqFilterProfile = new XsXbusMessageId("XMID_ReqFilterProfile", movelladot_pc_sdkJNI.XMID_ReqFilterProfile_get());
  public final static XsXbusMessageId XMID_ReqFilterProfileAck = new XsXbusMessageId("XMID_ReqFilterProfileAck", movelladot_pc_sdkJNI.XMID_ReqFilterProfileAck_get());
  public final static XsXbusMessageId XMID_SetFilterProfile = new XsXbusMessageId("XMID_SetFilterProfile", movelladot_pc_sdkJNI.XMID_SetFilterProfile_get());
  public final static XsXbusMessageId XMID_SetFilterProfileAck = new XsXbusMessageId("XMID_SetFilterProfileAck", movelladot_pc_sdkJNI.XMID_SetFilterProfileAck_get());
  public final static XsXbusMessageId XMID_ReqGravityMagnitude = new XsXbusMessageId("XMID_ReqGravityMagnitude", movelladot_pc_sdkJNI.XMID_ReqGravityMagnitude_get());
  public final static XsXbusMessageId XMID_ReqGravityMagnitudeAck = new XsXbusMessageId("XMID_ReqGravityMagnitudeAck", movelladot_pc_sdkJNI.XMID_ReqGravityMagnitudeAck_get());
  public final static XsXbusMessageId XMID_SetGravityMagnitude = new XsXbusMessageId("XMID_SetGravityMagnitude", movelladot_pc_sdkJNI.XMID_SetGravityMagnitude_get());
  public final static XsXbusMessageId XMID_SetGravityMagnitudeAck = new XsXbusMessageId("XMID_SetGravityMagnitudeAck", movelladot_pc_sdkJNI.XMID_SetGravityMagnitudeAck_get());
  public final static XsXbusMessageId XMID_ReqGnssLeverArm = new XsXbusMessageId("XMID_ReqGnssLeverArm", movelladot_pc_sdkJNI.XMID_ReqGnssLeverArm_get());
  public final static XsXbusMessageId XMID_ReqGnssLeverArmAck = new XsXbusMessageId("XMID_ReqGnssLeverArmAck", movelladot_pc_sdkJNI.XMID_ReqGnssLeverArmAck_get());
  public final static XsXbusMessageId XMID_SetGnssLeverArm = new XsXbusMessageId("XMID_SetGnssLeverArm", movelladot_pc_sdkJNI.XMID_SetGnssLeverArm_get());
  public final static XsXbusMessageId XMID_SetGnssLeverArmAck = new XsXbusMessageId("XMID_SetGnssLeverArmAck", movelladot_pc_sdkJNI.XMID_SetGnssLeverArmAck_get());
  public final static XsXbusMessageId XMID_ReqMagneticField = new XsXbusMessageId("XMID_ReqMagneticField", movelladot_pc_sdkJNI.XMID_ReqMagneticField_get());
  public final static XsXbusMessageId XMID_ReqMagneticFieldAck = new XsXbusMessageId("XMID_ReqMagneticFieldAck", movelladot_pc_sdkJNI.XMID_ReqMagneticFieldAck_get());
  public final static XsXbusMessageId XMID_SetMagneticField = new XsXbusMessageId("XMID_SetMagneticField", movelladot_pc_sdkJNI.XMID_SetMagneticField_get());
  public final static XsXbusMessageId XMID_SetMagneticFieldAck = new XsXbusMessageId("XMID_SetMagneticFieldAck", movelladot_pc_sdkJNI.XMID_SetMagneticFieldAck_get());
  public final static XsXbusMessageId XMID_ReqReplayMode = new XsXbusMessageId("XMID_ReqReplayMode", movelladot_pc_sdkJNI.XMID_ReqReplayMode_get());
  public final static XsXbusMessageId XMID_ReqReplayModeAck = new XsXbusMessageId("XMID_ReqReplayModeAck", movelladot_pc_sdkJNI.XMID_ReqReplayModeAck_get());
  public final static XsXbusMessageId XMID_SetReplayMode = new XsXbusMessageId("XMID_SetReplayMode", movelladot_pc_sdkJNI.XMID_SetReplayMode_get());
  public final static XsXbusMessageId XMID_SetReplayModeAck = new XsXbusMessageId("XMID_SetReplayModeAck", movelladot_pc_sdkJNI.XMID_SetReplayModeAck_get());
  public final static XsXbusMessageId XMID_ReqLatLonAlt = new XsXbusMessageId("XMID_ReqLatLonAlt", movelladot_pc_sdkJNI.XMID_ReqLatLonAlt_get());
  public final static XsXbusMessageId XMID_ReqLatLonAltAck = new XsXbusMessageId("XMID_ReqLatLonAltAck", movelladot_pc_sdkJNI.XMID_ReqLatLonAltAck_get());
  public final static XsXbusMessageId XMID_SetLatLonAlt = new XsXbusMessageId("XMID_SetLatLonAlt", movelladot_pc_sdkJNI.XMID_SetLatLonAlt_get());
  public final static XsXbusMessageId XMID_SetLatLonAltAck = new XsXbusMessageId("XMID_SetLatLonAltAck", movelladot_pc_sdkJNI.XMID_SetLatLonAltAck_get());
  public final static XsXbusMessageId XMID_KeepAlive = new XsXbusMessageId("XMID_KeepAlive", movelladot_pc_sdkJNI.XMID_KeepAlive_get());
  public final static XsXbusMessageId XMID_KeepAliveAck = new XsXbusMessageId("XMID_KeepAliveAck", movelladot_pc_sdkJNI.XMID_KeepAliveAck_get());
  public final static XsXbusMessageId XMID_CloseConnection = new XsXbusMessageId("XMID_CloseConnection", movelladot_pc_sdkJNI.XMID_CloseConnection_get());
  public final static XsXbusMessageId XMID_CloseConnectionAck = new XsXbusMessageId("XMID_CloseConnectionAck", movelladot_pc_sdkJNI.XMID_CloseConnectionAck_get());
  public final static XsXbusMessageId XMID_IccCommand = new XsXbusMessageId("XMID_IccCommand", movelladot_pc_sdkJNI.XMID_IccCommand_get());
  public final static XsXbusMessageId XMID_IccCommandAck = new XsXbusMessageId("XMID_IccCommandAck", movelladot_pc_sdkJNI.XMID_IccCommandAck_get());
  public final static XsXbusMessageId XMID_ReqGnssPlatform = new XsXbusMessageId("XMID_ReqGnssPlatform", movelladot_pc_sdkJNI.XMID_ReqGnssPlatform_get());
  public final static XsXbusMessageId XMID_ReqGnssPlatformAck = new XsXbusMessageId("XMID_ReqGnssPlatformAck", movelladot_pc_sdkJNI.XMID_ReqGnssPlatformAck_get());
  public final static XsXbusMessageId XMID_SetGnssPlatform = new XsXbusMessageId("XMID_SetGnssPlatform", movelladot_pc_sdkJNI.XMID_SetGnssPlatform_get());
  public final static XsXbusMessageId XMID_SetGnssPlatformAck = new XsXbusMessageId("XMID_SetGnssPlatformAck", movelladot_pc_sdkJNI.XMID_SetGnssPlatformAck_get());
  public final static XsXbusMessageId XMID_ReqConnectionSettings = new XsXbusMessageId("XMID_ReqConnectionSettings", movelladot_pc_sdkJNI.XMID_ReqConnectionSettings_get());
  public final static XsXbusMessageId XMID_ReqConnectionSettingsAck = new XsXbusMessageId("XMID_ReqConnectionSettingsAck", movelladot_pc_sdkJNI.XMID_ReqConnectionSettingsAck_get());
  public final static XsXbusMessageId XMID_SetConnectionSettings = new XsXbusMessageId("XMID_SetConnectionSettings", movelladot_pc_sdkJNI.XMID_SetConnectionSettings_get());
  public final static XsXbusMessageId XMID_SetConnectionSettingsAck = new XsXbusMessageId("XMID_SetConnectionSettingsAck", movelladot_pc_sdkJNI.XMID_SetConnectionSettingsAck_get());
  public final static XsXbusMessageId XMID_BodyPackBundle = new XsXbusMessageId("XMID_BodyPackBundle", movelladot_pc_sdkJNI.XMID_BodyPackBundle_get());
  public final static XsXbusMessageId XMID_BodyPackBundleAck = new XsXbusMessageId("XMID_BodyPackBundleAck", movelladot_pc_sdkJNI.XMID_BodyPackBundleAck_get());
  public final static XsXbusMessageId XMID_ReqStationOptions = new XsXbusMessageId("XMID_ReqStationOptions", movelladot_pc_sdkJNI.XMID_ReqStationOptions_get());
  public final static XsXbusMessageId XMID_ReqStationOptionsAck = new XsXbusMessageId("XMID_ReqStationOptionsAck", movelladot_pc_sdkJNI.XMID_ReqStationOptionsAck_get());
  public final static XsXbusMessageId XMID_ReqErrorReport = new XsXbusMessageId("XMID_ReqErrorReport", movelladot_pc_sdkJNI.XMID_ReqErrorReport_get());
  public final static XsXbusMessageId XMID_ErrorReport = new XsXbusMessageId("XMID_ErrorReport", movelladot_pc_sdkJNI.XMID_ErrorReport_get());
  public final static XsXbusMessageId XMID_ReqXmErrorMode = new XsXbusMessageId("XMID_ReqXmErrorMode", movelladot_pc_sdkJNI.XMID_ReqXmErrorMode_get());
  public final static XsXbusMessageId XMID_ReqXmErrorModeAck = new XsXbusMessageId("XMID_ReqXmErrorModeAck", movelladot_pc_sdkJNI.XMID_ReqXmErrorModeAck_get());
  public final static XsXbusMessageId XMID_SetXmErrorMode = new XsXbusMessageId("XMID_SetXmErrorMode", movelladot_pc_sdkJNI.XMID_SetXmErrorMode_get());
  public final static XsXbusMessageId XMID_SetXmErrorModeAck = new XsXbusMessageId("XMID_SetXmErrorModeAck", movelladot_pc_sdkJNI.XMID_SetXmErrorModeAck_get());
  public final static XsXbusMessageId XMID_ReqBufferSize = new XsXbusMessageId("XMID_ReqBufferSize", movelladot_pc_sdkJNI.XMID_ReqBufferSize_get());
  public final static XsXbusMessageId XMID_ReqBufferSizeAck = new XsXbusMessageId("XMID_ReqBufferSizeAck", movelladot_pc_sdkJNI.XMID_ReqBufferSizeAck_get());
  public final static XsXbusMessageId XMID_SetBufferSize = new XsXbusMessageId("XMID_SetBufferSize", movelladot_pc_sdkJNI.XMID_SetBufferSize_get());
  public final static XsXbusMessageId XMID_SetBufferSizeAck = new XsXbusMessageId("XMID_SetBufferSizeAck", movelladot_pc_sdkJNI.XMID_SetBufferSizeAck_get());
  public final static XsXbusMessageId XMID_ReqHeading = new XsXbusMessageId("XMID_ReqHeading", movelladot_pc_sdkJNI.XMID_ReqHeading_get());
  public final static XsXbusMessageId XMID_ReqHeadingAck = new XsXbusMessageId("XMID_ReqHeadingAck", movelladot_pc_sdkJNI.XMID_ReqHeadingAck_get());
  public final static XsXbusMessageId XMID_SetHeading = new XsXbusMessageId("XMID_SetHeading", movelladot_pc_sdkJNI.XMID_SetHeading_get());
  public final static XsXbusMessageId XMID_SetHeadingAck = new XsXbusMessageId("XMID_SetHeadingAck", movelladot_pc_sdkJNI.XMID_SetHeadingAck_get());
  public final static XsXbusMessageId XMID_ReqLocationId = new XsXbusMessageId("XMID_ReqLocationId", movelladot_pc_sdkJNI.XMID_ReqLocationId_get());
  public final static XsXbusMessageId XMID_ReqLocationIdAck = new XsXbusMessageId("XMID_ReqLocationIdAck", movelladot_pc_sdkJNI.XMID_ReqLocationIdAck_get());
  public final static XsXbusMessageId XMID_SetLocationId = new XsXbusMessageId("XMID_SetLocationId", movelladot_pc_sdkJNI.XMID_SetLocationId_get());
  public final static XsXbusMessageId XMID_SetLocationIdAck = new XsXbusMessageId("XMID_SetLocationIdAck", movelladot_pc_sdkJNI.XMID_SetLocationIdAck_get());
  public final static XsXbusMessageId XMID_ReqExtOutputMode = new XsXbusMessageId("XMID_ReqExtOutputMode", movelladot_pc_sdkJNI.XMID_ReqExtOutputMode_get());
  public final static XsXbusMessageId XMID_ReqExtOutputModeAck = new XsXbusMessageId("XMID_ReqExtOutputModeAck", movelladot_pc_sdkJNI.XMID_ReqExtOutputModeAck_get());
  public final static XsXbusMessageId XMID_SetExtOutputMode = new XsXbusMessageId("XMID_SetExtOutputMode", movelladot_pc_sdkJNI.XMID_SetExtOutputMode_get());
  public final static XsXbusMessageId XMID_SetExtOutputModeAck = new XsXbusMessageId("XMID_SetExtOutputModeAck", movelladot_pc_sdkJNI.XMID_SetExtOutputModeAck_get());
  public final static XsXbusMessageId XMID_ReqBatteryLevel = new XsXbusMessageId("XMID_ReqBatteryLevel", movelladot_pc_sdkJNI.XMID_ReqBatteryLevel_get());
  public final static XsXbusMessageId XMID_Batterylevel = new XsXbusMessageId("XMID_Batterylevel", movelladot_pc_sdkJNI.XMID_Batterylevel_get());
  public final static XsXbusMessageId XMID_ReqInitTrackMode = new XsXbusMessageId("XMID_ReqInitTrackMode", movelladot_pc_sdkJNI.XMID_ReqInitTrackMode_get());
  public final static XsXbusMessageId XMID_ReqInitTrackModeAck = new XsXbusMessageId("XMID_ReqInitTrackModeAck", movelladot_pc_sdkJNI.XMID_ReqInitTrackModeAck_get());
  public final static XsXbusMessageId XMID_SetInitTrackMode = new XsXbusMessageId("XMID_SetInitTrackMode", movelladot_pc_sdkJNI.XMID_SetInitTrackMode_get());
  public final static XsXbusMessageId XMID_SetInitTrackModeAck = new XsXbusMessageId("XMID_SetInitTrackModeAck", movelladot_pc_sdkJNI.XMID_SetInitTrackModeAck_get());
  public final static XsXbusMessageId XMID_ReqMasterSettings = new XsXbusMessageId("XMID_ReqMasterSettings", movelladot_pc_sdkJNI.XMID_ReqMasterSettings_get());
  public final static XsXbusMessageId XMID_MasterSettings = new XsXbusMessageId("XMID_MasterSettings", movelladot_pc_sdkJNI.XMID_MasterSettings_get());
  public final static XsXbusMessageId XMID_StoreFilterState = new XsXbusMessageId("XMID_StoreFilterState", movelladot_pc_sdkJNI.XMID_StoreFilterState_get());
  public final static XsXbusMessageId XMID_StoreFilterStateAck = new XsXbusMessageId("XMID_StoreFilterStateAck", movelladot_pc_sdkJNI.XMID_StoreFilterStateAck_get());
  public final static XsXbusMessageId XMID_ReqPortConfig = new XsXbusMessageId("XMID_ReqPortConfig", movelladot_pc_sdkJNI.XMID_ReqPortConfig_get());
  public final static XsXbusMessageId XMID_SetPortConfig = new XsXbusMessageId("XMID_SetPortConfig", movelladot_pc_sdkJNI.XMID_SetPortConfig_get());
  public final static XsXbusMessageId XMID_PortConfig = new XsXbusMessageId("XMID_PortConfig", movelladot_pc_sdkJNI.XMID_PortConfig_get());
  public final static XsXbusMessageId XMID_SetPortConfigAck = new XsXbusMessageId("XMID_SetPortConfigAck", movelladot_pc_sdkJNI.XMID_SetPortConfigAck_get());
  public final static XsXbusMessageId XMID_ReqStringOutputType = new XsXbusMessageId("XMID_ReqStringOutputType", movelladot_pc_sdkJNI.XMID_ReqStringOutputType_get());
  public final static XsXbusMessageId XMID_ReqStringOutputTypeAck = new XsXbusMessageId("XMID_ReqStringOutputTypeAck", movelladot_pc_sdkJNI.XMID_ReqStringOutputTypeAck_get());
  public final static XsXbusMessageId XMID_SetStringOutputType = new XsXbusMessageId("XMID_SetStringOutputType", movelladot_pc_sdkJNI.XMID_SetStringOutputType_get());
  public final static XsXbusMessageId XMID_SetStringOutputTypeAck = new XsXbusMessageId("XMID_SetStringOutputTypeAck", movelladot_pc_sdkJNI.XMID_SetStringOutputTypeAck_get());
  public final static XsXbusMessageId XMID_ReqStringOutputConfig = new XsXbusMessageId("XMID_ReqStringOutputConfig", movelladot_pc_sdkJNI.XMID_ReqStringOutputConfig_get());
  public final static XsXbusMessageId XMID_ReqStringOutputConfigAck = new XsXbusMessageId("XMID_ReqStringOutputConfigAck", movelladot_pc_sdkJNI.XMID_ReqStringOutputConfigAck_get());
  public final static XsXbusMessageId XMID_SetStringOutputConfig = new XsXbusMessageId("XMID_SetStringOutputConfig", movelladot_pc_sdkJNI.XMID_SetStringOutputConfig_get());
  public final static XsXbusMessageId XMID_SetStringOutputConfigAck = new XsXbusMessageId("XMID_SetStringOutputConfigAck", movelladot_pc_sdkJNI.XMID_SetStringOutputConfigAck_get());
  public final static XsXbusMessageId XMID_ReqEmts = new XsXbusMessageId("XMID_ReqEmts", movelladot_pc_sdkJNI.XMID_ReqEmts_get());
  public final static XsXbusMessageId XMID_EmtsData = new XsXbusMessageId("XMID_EmtsData", movelladot_pc_sdkJNI.XMID_EmtsData_get());
  public final static XsXbusMessageId XMID_UpdateFilterProfile = new XsXbusMessageId("XMID_UpdateFilterProfile", movelladot_pc_sdkJNI.XMID_UpdateFilterProfile_get());
  public final static XsXbusMessageId XMID_UpdateFilterProfileAck = new XsXbusMessageId("XMID_UpdateFilterProfileAck", movelladot_pc_sdkJNI.XMID_UpdateFilterProfileAck_get());
  public final static XsXbusMessageId XMID_RestoreEmts = new XsXbusMessageId("XMID_RestoreEmts", movelladot_pc_sdkJNI.XMID_RestoreEmts_get());
  public final static XsXbusMessageId XMID_RestoreEmtsAck = new XsXbusMessageId("XMID_RestoreEmtsAck", movelladot_pc_sdkJNI.XMID_RestoreEmtsAck_get());
  public final static XsXbusMessageId XMID_StoreEmts = new XsXbusMessageId("XMID_StoreEmts", movelladot_pc_sdkJNI.XMID_StoreEmts_get());
  public final static XsXbusMessageId XMID_StoreEmtsAck = new XsXbusMessageId("XMID_StoreEmtsAck", movelladot_pc_sdkJNI.XMID_StoreEmtsAck_get());
  public final static XsXbusMessageId XMID_UnlockMaintenanceMode = new XsXbusMessageId("XMID_UnlockMaintenanceMode", movelladot_pc_sdkJNI.XMID_UnlockMaintenanceMode_get());
  public final static XsXbusMessageId XMID_UnlockMaintenanceModeAck = new XsXbusMessageId("XMID_UnlockMaintenanceModeAck", movelladot_pc_sdkJNI.XMID_UnlockMaintenanceModeAck_get());
  public final static XsXbusMessageId XMID_ClockSyncCommand = new XsXbusMessageId("XMID_ClockSyncCommand", movelladot_pc_sdkJNI.XMID_ClockSyncCommand_get());
  public final static XsXbusMessageId XMID_ClockSyncCommandAck = new XsXbusMessageId("XMID_ClockSyncCommandAck", movelladot_pc_sdkJNI.XMID_ClockSyncCommandAck_get());
  public final static XsXbusMessageId XMID_ReqActiveClockCorrection = new XsXbusMessageId("XMID_ReqActiveClockCorrection", movelladot_pc_sdkJNI.XMID_ReqActiveClockCorrection_get());
  public final static XsXbusMessageId XMID_ActiveClockCorrection = new XsXbusMessageId("XMID_ActiveClockCorrection", movelladot_pc_sdkJNI.XMID_ActiveClockCorrection_get());
  public final static XsXbusMessageId XMID_StoreActiveClockCorrection = new XsXbusMessageId("XMID_StoreActiveClockCorrection", movelladot_pc_sdkJNI.XMID_StoreActiveClockCorrection_get());
  public final static XsXbusMessageId XMID_StoreActiveClockCorrectionAck = new XsXbusMessageId("XMID_StoreActiveClockCorrectionAck", movelladot_pc_sdkJNI.XMID_StoreActiveClockCorrectionAck_get());
  public final static XsXbusMessageId XMID_ReqFilterSettings = new XsXbusMessageId("XMID_ReqFilterSettings", movelladot_pc_sdkJNI.XMID_ReqFilterSettings_get());
  public final static XsXbusMessageId XMID_ReqFilterSettingsAck = new XsXbusMessageId("XMID_ReqFilterSettingsAck", movelladot_pc_sdkJNI.XMID_ReqFilterSettingsAck_get());
  public final static XsXbusMessageId XMID_SetFilterSettings = new XsXbusMessageId("XMID_SetFilterSettings", movelladot_pc_sdkJNI.XMID_SetFilterSettings_get());
  public final static XsXbusMessageId XMID_SetFilterSettingsAck = new XsXbusMessageId("XMID_SetFilterSettingsAck", movelladot_pc_sdkJNI.XMID_SetFilterSettingsAck_get());
  public final static XsXbusMessageId XMID_ReqAmd = new XsXbusMessageId("XMID_ReqAmd", movelladot_pc_sdkJNI.XMID_ReqAmd_get());
  public final static XsXbusMessageId XMID_ReqAmdAck = new XsXbusMessageId("XMID_ReqAmdAck", movelladot_pc_sdkJNI.XMID_ReqAmdAck_get());
  public final static XsXbusMessageId XMID_SetAmd = new XsXbusMessageId("XMID_SetAmd", movelladot_pc_sdkJNI.XMID_SetAmd_get());
  public final static XsXbusMessageId XMID_SetAmdAck = new XsXbusMessageId("XMID_SetAmdAck", movelladot_pc_sdkJNI.XMID_SetAmdAck_get());
  public final static XsXbusMessageId XMID_ResetOrientation = new XsXbusMessageId("XMID_ResetOrientation", movelladot_pc_sdkJNI.XMID_ResetOrientation_get());
  public final static XsXbusMessageId XMID_ResetOrientationAck = new XsXbusMessageId("XMID_ResetOrientationAck", movelladot_pc_sdkJNI.XMID_ResetOrientationAck_get());
  public final static XsXbusMessageId XMID_ReqGnssStatus = new XsXbusMessageId("XMID_ReqGnssStatus", movelladot_pc_sdkJNI.XMID_ReqGnssStatus_get());
  public final static XsXbusMessageId XMID_GnssStatus = new XsXbusMessageId("XMID_GnssStatus", movelladot_pc_sdkJNI.XMID_GnssStatus_get());
  public final static XsXbusMessageId XMID_AdjustUtcTime = new XsXbusMessageId("XMID_AdjustUtcTime", movelladot_pc_sdkJNI.XMID_AdjustUtcTime_get());
  public final static XsXbusMessageId XMID_AdjustUtcTimeAck = new XsXbusMessageId("XMID_AdjustUtcTimeAck", movelladot_pc_sdkJNI.XMID_AdjustUtcTimeAck_get());
  public final static XsXbusMessageId XMID_ReqAssemblyId = new XsXbusMessageId("XMID_ReqAssemblyId", movelladot_pc_sdkJNI.XMID_ReqAssemblyId_get());
  public final static XsXbusMessageId XMID_SetAssemblyId = new XsXbusMessageId("XMID_SetAssemblyId", movelladot_pc_sdkJNI.XMID_SetAssemblyId_get());
  public final static XsXbusMessageId XMID_AssemblyId = new XsXbusMessageId("XMID_AssemblyId", movelladot_pc_sdkJNI.XMID_AssemblyId_get());
  public final static XsXbusMessageId XMID_SetAssemblyIdAck = new XsXbusMessageId("XMID_SetAssemblyIdAck", movelladot_pc_sdkJNI.XMID_SetAssemblyIdAck_get());
  public final static XsXbusMessageId XMID_ReqGnssReceiverSettings = new XsXbusMessageId("XMID_ReqGnssReceiverSettings", movelladot_pc_sdkJNI.XMID_ReqGnssReceiverSettings_get());
  public final static XsXbusMessageId XMID_ReqGnssReceiverSettingsAck = new XsXbusMessageId("XMID_ReqGnssReceiverSettingsAck", movelladot_pc_sdkJNI.XMID_ReqGnssReceiverSettingsAck_get());
  public final static XsXbusMessageId XMID_SetGnssReceiverSettings = new XsXbusMessageId("XMID_SetGnssReceiverSettings", movelladot_pc_sdkJNI.XMID_SetGnssReceiverSettings_get());
  public final static XsXbusMessageId XMID_SetGnssReceiverSettingsAck = new XsXbusMessageId("XMID_SetGnssReceiverSettingsAck", movelladot_pc_sdkJNI.XMID_SetGnssReceiverSettingsAck_get());
  public final static XsXbusMessageId XMID_ReqAccessControlList = new XsXbusMessageId("XMID_ReqAccessControlList", movelladot_pc_sdkJNI.XMID_ReqAccessControlList_get());
  public final static XsXbusMessageId XMID_AccessControlList = new XsXbusMessageId("XMID_AccessControlList", movelladot_pc_sdkJNI.XMID_AccessControlList_get());
  public final static XsXbusMessageId XMID_SetAccessControlList = new XsXbusMessageId("XMID_SetAccessControlList", movelladot_pc_sdkJNI.XMID_SetAccessControlList_get());
  public final static XsXbusMessageId XMID_SetAccessControlListAck = new XsXbusMessageId("XMID_SetAccessControlListAck", movelladot_pc_sdkJNI.XMID_SetAccessControlListAck_get());
  public final static XsXbusMessageId XMID_ScanChannels = new XsXbusMessageId("XMID_ScanChannels", movelladot_pc_sdkJNI.XMID_ScanChannels_get());
  public final static XsXbusMessageId XMID_ScanChannelsAck = new XsXbusMessageId("XMID_ScanChannelsAck", movelladot_pc_sdkJNI.XMID_ScanChannelsAck_get());
  public final static XsXbusMessageId XMID_EnableMaster = new XsXbusMessageId("XMID_EnableMaster", movelladot_pc_sdkJNI.XMID_EnableMaster_get());
  public final static XsXbusMessageId XMID_EnableMasterAck = new XsXbusMessageId("XMID_EnableMasterAck", movelladot_pc_sdkJNI.XMID_EnableMasterAck_get());
  public final static XsXbusMessageId XMID_DisableMaster = new XsXbusMessageId("XMID_DisableMaster", movelladot_pc_sdkJNI.XMID_DisableMaster_get());
  public final static XsXbusMessageId XMID_DisableMasterAck = new XsXbusMessageId("XMID_DisableMasterAck", movelladot_pc_sdkJNI.XMID_DisableMasterAck_get());
  public final static XsXbusMessageId XMID_ReqRadioChannel = new XsXbusMessageId("XMID_ReqRadioChannel", movelladot_pc_sdkJNI.XMID_ReqRadioChannel_get());
  public final static XsXbusMessageId XMID_ReqRadioChannelAck = new XsXbusMessageId("XMID_ReqRadioChannelAck", movelladot_pc_sdkJNI.XMID_ReqRadioChannelAck_get());
  public final static XsXbusMessageId XMID_SetClientPriority = new XsXbusMessageId("XMID_SetClientPriority", movelladot_pc_sdkJNI.XMID_SetClientPriority_get());
  public final static XsXbusMessageId XMID_SetClientPriorityAck = new XsXbusMessageId("XMID_SetClientPriorityAck", movelladot_pc_sdkJNI.XMID_SetClientPriorityAck_get());
  public final static XsXbusMessageId XMID_ReqClientPriority = new XsXbusMessageId("XMID_ReqClientPriority", movelladot_pc_sdkJNI.XMID_ReqClientPriority_get());
  public final static XsXbusMessageId XMID_ReqClientPriorityAck = new XsXbusMessageId("XMID_ReqClientPriorityAck", movelladot_pc_sdkJNI.XMID_ReqClientPriorityAck_get());
  public final static XsXbusMessageId XMID_SetWirelessConfig = new XsXbusMessageId("XMID_SetWirelessConfig", movelladot_pc_sdkJNI.XMID_SetWirelessConfig_get());
  public final static XsXbusMessageId XMID_SetWirelessConfigAck = new XsXbusMessageId("XMID_SetWirelessConfigAck", movelladot_pc_sdkJNI.XMID_SetWirelessConfigAck_get());
  public final static XsXbusMessageId XMID_ReqWirelessConfig = new XsXbusMessageId("XMID_ReqWirelessConfig", movelladot_pc_sdkJNI.XMID_ReqWirelessConfig_get());
  public final static XsXbusMessageId XMID_ReqWirelessConfigAck = new XsXbusMessageId("XMID_ReqWirelessConfigAck", movelladot_pc_sdkJNI.XMID_ReqWirelessConfigAck_get());
  public final static XsXbusMessageId XMID_UpdateBias = new XsXbusMessageId("XMID_UpdateBias", movelladot_pc_sdkJNI.XMID_UpdateBias_get());
  public final static XsXbusMessageId XMID_UpdateBiasAck = new XsXbusMessageId("XMID_UpdateBiasAck", movelladot_pc_sdkJNI.XMID_UpdateBiasAck_get());
  public final static XsXbusMessageId XMID_ToggleIoPins = new XsXbusMessageId("XMID_ToggleIoPins", movelladot_pc_sdkJNI.XMID_ToggleIoPins_get());
  public final static XsXbusMessageId XMID_ToggleIoPinsAck = new XsXbusMessageId("XMID_ToggleIoPinsAck", movelladot_pc_sdkJNI.XMID_ToggleIoPinsAck_get());
  public final static XsXbusMessageId XMID_GotoOperational = new XsXbusMessageId("XMID_GotoOperational", movelladot_pc_sdkJNI.XMID_GotoOperational_get());
  public final static XsXbusMessageId XMID_GotoOperationalAck = new XsXbusMessageId("XMID_GotoOperationalAck", movelladot_pc_sdkJNI.XMID_GotoOperationalAck_get());
  public final static XsXbusMessageId XMID_SetTransportMode = new XsXbusMessageId("XMID_SetTransportMode", movelladot_pc_sdkJNI.XMID_SetTransportMode_get());
  public final static XsXbusMessageId XMID_SetTransportModeAck = new XsXbusMessageId("XMID_SetTransportModeAck", movelladot_pc_sdkJNI.XMID_SetTransportModeAck_get());
  public final static XsXbusMessageId XMID_ReqTransportMode = new XsXbusMessageId("XMID_ReqTransportMode", movelladot_pc_sdkJNI.XMID_ReqTransportMode_get());
  public final static XsXbusMessageId XMID_ReqTransportModeAck = new XsXbusMessageId("XMID_ReqTransportModeAck", movelladot_pc_sdkJNI.XMID_ReqTransportModeAck_get());
  public final static XsXbusMessageId XMID_AcceptMtw = new XsXbusMessageId("XMID_AcceptMtw", movelladot_pc_sdkJNI.XMID_AcceptMtw_get());
  public final static XsXbusMessageId XMID_AcceptMtwAck = new XsXbusMessageId("XMID_AcceptMtwAck", movelladot_pc_sdkJNI.XMID_AcceptMtwAck_get());
  public final static XsXbusMessageId XMID_RejectMtw = new XsXbusMessageId("XMID_RejectMtw", movelladot_pc_sdkJNI.XMID_RejectMtw_get());
  public final static XsXbusMessageId XMID_RejectMtwAck = new XsXbusMessageId("XMID_RejectMtwAck", movelladot_pc_sdkJNI.XMID_RejectMtwAck_get());
  public final static XsXbusMessageId XMID_InfoRequest = new XsXbusMessageId("XMID_InfoRequest", movelladot_pc_sdkJNI.XMID_InfoRequest_get());
  public final static XsXbusMessageId XMID_InfoRequestAck = new XsXbusMessageId("XMID_InfoRequestAck", movelladot_pc_sdkJNI.XMID_InfoRequestAck_get());
  public final static XsXbusMessageId XMID_ReqFrameRates = new XsXbusMessageId("XMID_ReqFrameRates", movelladot_pc_sdkJNI.XMID_ReqFrameRates_get());
  public final static XsXbusMessageId XMID_ReqFrameRatesAck = new XsXbusMessageId("XMID_ReqFrameRatesAck", movelladot_pc_sdkJNI.XMID_ReqFrameRatesAck_get());
  public final static XsXbusMessageId XMID_StartRecording = new XsXbusMessageId("XMID_StartRecording", movelladot_pc_sdkJNI.XMID_StartRecording_get());
  public final static XsXbusMessageId XMID_StartRecordingAck = new XsXbusMessageId("XMID_StartRecordingAck", movelladot_pc_sdkJNI.XMID_StartRecordingAck_get());
  public final static XsXbusMessageId XMID_StopRecording = new XsXbusMessageId("XMID_StopRecording", movelladot_pc_sdkJNI.XMID_StopRecording_get());
  public final static XsXbusMessageId XMID_StopRecordingAck = new XsXbusMessageId("XMID_StopRecordingAck", movelladot_pc_sdkJNI.XMID_StopRecordingAck_get());
  public final static XsXbusMessageId XMID_ReqOutputConfiguration = new XsXbusMessageId("XMID_ReqOutputConfiguration", movelladot_pc_sdkJNI.XMID_ReqOutputConfiguration_get());
  public final static XsXbusMessageId XMID_ReqOutputConfigurationAck = new XsXbusMessageId("XMID_ReqOutputConfigurationAck", movelladot_pc_sdkJNI.XMID_ReqOutputConfigurationAck_get());
  public final static XsXbusMessageId XMID_SetOutputConfiguration = new XsXbusMessageId("XMID_SetOutputConfiguration", movelladot_pc_sdkJNI.XMID_SetOutputConfiguration_get());
  public final static XsXbusMessageId XMID_SetOutputConfigurationAck = new XsXbusMessageId("XMID_SetOutputConfigurationAck", movelladot_pc_sdkJNI.XMID_SetOutputConfigurationAck_get());
  public final static XsXbusMessageId XMID_ReqOutputMode = new XsXbusMessageId("XMID_ReqOutputMode", movelladot_pc_sdkJNI.XMID_ReqOutputMode_get());
  public final static XsXbusMessageId XMID_ReqOutputModeAck = new XsXbusMessageId("XMID_ReqOutputModeAck", movelladot_pc_sdkJNI.XMID_ReqOutputModeAck_get());
  public final static XsXbusMessageId XMID_SetOutputMode = new XsXbusMessageId("XMID_SetOutputMode", movelladot_pc_sdkJNI.XMID_SetOutputMode_get());
  public final static XsXbusMessageId XMID_SetOutputModeAck = new XsXbusMessageId("XMID_SetOutputModeAck", movelladot_pc_sdkJNI.XMID_SetOutputModeAck_get());
  public final static XsXbusMessageId XMID_ReqOutputSettings = new XsXbusMessageId("XMID_ReqOutputSettings", movelladot_pc_sdkJNI.XMID_ReqOutputSettings_get());
  public final static XsXbusMessageId XMID_ReqOutputSettingsAck = new XsXbusMessageId("XMID_ReqOutputSettingsAck", movelladot_pc_sdkJNI.XMID_ReqOutputSettingsAck_get());
  public final static XsXbusMessageId XMID_SetOutputSettings = new XsXbusMessageId("XMID_SetOutputSettings", movelladot_pc_sdkJNI.XMID_SetOutputSettings_get());
  public final static XsXbusMessageId XMID_SetOutputSettingsAck = new XsXbusMessageId("XMID_SetOutputSettingsAck", movelladot_pc_sdkJNI.XMID_SetOutputSettingsAck_get());
  public final static XsXbusMessageId XMID_ReqOutputSkipFactor = new XsXbusMessageId("XMID_ReqOutputSkipFactor", movelladot_pc_sdkJNI.XMID_ReqOutputSkipFactor_get());
  public final static XsXbusMessageId XMID_ReqOutputSkipFactorAck = new XsXbusMessageId("XMID_ReqOutputSkipFactorAck", movelladot_pc_sdkJNI.XMID_ReqOutputSkipFactorAck_get());
  public final static XsXbusMessageId XMID_SetOutputSkipFactor = new XsXbusMessageId("XMID_SetOutputSkipFactor", movelladot_pc_sdkJNI.XMID_SetOutputSkipFactor_get());
  public final static XsXbusMessageId XMID_SetOutputSkipFactorAck = new XsXbusMessageId("XMID_SetOutputSkipFactorAck", movelladot_pc_sdkJNI.XMID_SetOutputSkipFactorAck_get());
  public final static XsXbusMessageId XMID_SetInitialHeading = new XsXbusMessageId("XMID_SetInitialHeading", movelladot_pc_sdkJNI.XMID_SetInitialHeading_get());
  public final static XsXbusMessageId XMID_SetInitialHeadingAck = new XsXbusMessageId("XMID_SetInitialHeadingAck", movelladot_pc_sdkJNI.XMID_SetInitialHeadingAck_get());
  public final static XsXbusMessageId XMID_ReqErrorMode = new XsXbusMessageId("XMID_ReqErrorMode", movelladot_pc_sdkJNI.XMID_ReqErrorMode_get());
  public final static XsXbusMessageId XMID_ReqErrorModeAck = new XsXbusMessageId("XMID_ReqErrorModeAck", movelladot_pc_sdkJNI.XMID_ReqErrorModeAck_get());
  public final static XsXbusMessageId XMID_SetErrorMode = new XsXbusMessageId("XMID_SetErrorMode", movelladot_pc_sdkJNI.XMID_SetErrorMode_get());
  public final static XsXbusMessageId XMID_SetErrorModeAck = new XsXbusMessageId("XMID_SetErrorModeAck", movelladot_pc_sdkJNI.XMID_SetErrorModeAck_get());
  public final static XsXbusMessageId XMID_ReqTransmitDelay = new XsXbusMessageId("XMID_ReqTransmitDelay", movelladot_pc_sdkJNI.XMID_ReqTransmitDelay_get());
  public final static XsXbusMessageId XMID_ReqTransmitDelayAck = new XsXbusMessageId("XMID_ReqTransmitDelayAck", movelladot_pc_sdkJNI.XMID_ReqTransmitDelayAck_get());
  public final static XsXbusMessageId XMID_SetTransmitDelay = new XsXbusMessageId("XMID_SetTransmitDelay", movelladot_pc_sdkJNI.XMID_SetTransmitDelay_get());
  public final static XsXbusMessageId XMID_SetTransmitDelayAck = new XsXbusMessageId("XMID_SetTransmitDelayAck", movelladot_pc_sdkJNI.XMID_SetTransmitDelayAck_get());
  public final static XsXbusMessageId XMID_SetMfmResults = new XsXbusMessageId("XMID_SetMfmResults", movelladot_pc_sdkJNI.XMID_SetMfmResults_get());
  public final static XsXbusMessageId XMID_SetMfmResultsAck = new XsXbusMessageId("XMID_SetMfmResultsAck", movelladot_pc_sdkJNI.XMID_SetMfmResultsAck_get());
  public final static XsXbusMessageId XMID_ReqObjectAlignment = new XsXbusMessageId("XMID_ReqObjectAlignment", movelladot_pc_sdkJNI.XMID_ReqObjectAlignment_get());
  public final static XsXbusMessageId XMID_ReqObjectAlignmentAck = new XsXbusMessageId("XMID_ReqObjectAlignmentAck", movelladot_pc_sdkJNI.XMID_ReqObjectAlignmentAck_get());
  public final static XsXbusMessageId XMID_SetObjectAlignment = new XsXbusMessageId("XMID_SetObjectAlignment", movelladot_pc_sdkJNI.XMID_SetObjectAlignment_get());
  public final static XsXbusMessageId XMID_SetObjectAlignmentAck = new XsXbusMessageId("XMID_SetObjectAlignmentAck", movelladot_pc_sdkJNI.XMID_SetObjectAlignmentAck_get());
  public final static XsXbusMessageId XMID_ForwardGnssData = new XsXbusMessageId("XMID_ForwardGnssData", movelladot_pc_sdkJNI.XMID_ForwardGnssData_get());
  public final static XsXbusMessageId XMID_ForwardGnssDataAck = new XsXbusMessageId("XMID_ForwardGnssDataAck", movelladot_pc_sdkJNI.XMID_ForwardGnssDataAck_get());
  public final static XsXbusMessageId XMID_ReqCanConfig = new XsXbusMessageId("XMID_ReqCanConfig", movelladot_pc_sdkJNI.XMID_ReqCanConfig_get());
  public final static XsXbusMessageId XMID_SetCanConfig = new XsXbusMessageId("XMID_SetCanConfig", movelladot_pc_sdkJNI.XMID_SetCanConfig_get());
  public final static XsXbusMessageId XMID_CanConfig = new XsXbusMessageId("XMID_CanConfig", movelladot_pc_sdkJNI.XMID_CanConfig_get());
  public final static XsXbusMessageId XMID_SetCanConfigAck = new XsXbusMessageId("XMID_SetCanConfigAck", movelladot_pc_sdkJNI.XMID_SetCanConfigAck_get());
  public final static XsXbusMessageId XMID_ReqCanOutputConfig = new XsXbusMessageId("XMID_ReqCanOutputConfig", movelladot_pc_sdkJNI.XMID_ReqCanOutputConfig_get());
  public final static XsXbusMessageId XMID_SetCanOutputConfig = new XsXbusMessageId("XMID_SetCanOutputConfig", movelladot_pc_sdkJNI.XMID_SetCanOutputConfig_get());
  public final static XsXbusMessageId XMID_CanOutputConfig = new XsXbusMessageId("XMID_CanOutputConfig", movelladot_pc_sdkJNI.XMID_CanOutputConfig_get());
  public final static XsXbusMessageId XMID_SetCanOutputConfigAck = new XsXbusMessageId("XMID_SetCanOutputConfigAck", movelladot_pc_sdkJNI.XMID_SetCanOutputConfigAck_get());
  public final static XsXbusMessageId XMID_ReqAlignmentRotation = new XsXbusMessageId("XMID_ReqAlignmentRotation", movelladot_pc_sdkJNI.XMID_ReqAlignmentRotation_get());
  public final static XsXbusMessageId XMID_ReqAlignmentRotationAck = new XsXbusMessageId("XMID_ReqAlignmentRotationAck", movelladot_pc_sdkJNI.XMID_ReqAlignmentRotationAck_get());
  public final static XsXbusMessageId XMID_SetAlignmentRotation = new XsXbusMessageId("XMID_SetAlignmentRotation", movelladot_pc_sdkJNI.XMID_SetAlignmentRotation_get());
  public final static XsXbusMessageId XMID_SetAlignmentRotationAck = new XsXbusMessageId("XMID_SetAlignmentRotationAck", movelladot_pc_sdkJNI.XMID_SetAlignmentRotationAck_get());
  public final static XsXbusMessageId XMID_ExtendedMessageID = new XsXbusMessageId("XMID_ExtendedMessageID", movelladot_pc_sdkJNI.XMID_ExtendedMessageID_get());
  public final static XsXbusMessageId XMID_SetDeviceIdContext = new XsXbusMessageId("XMID_SetDeviceIdContext", movelladot_pc_sdkJNI.XMID_SetDeviceIdContext_get());
  public final static XsXbusMessageId XMID_SetDeviceIdContextAck = new XsXbusMessageId("XMID_SetDeviceIdContextAck", movelladot_pc_sdkJNI.XMID_SetDeviceIdContextAck_get());
  public final static XsXbusMessageId XMID_SetLogLevel = new XsXbusMessageId("XMID_SetLogLevel", movelladot_pc_sdkJNI.XMID_SetLogLevel_get());
  public final static XsXbusMessageId XMID_SetLogLevelAck = new XsXbusMessageId("XMID_SetLogLevelAck", movelladot_pc_sdkJNI.XMID_SetLogLevelAck_get());
  public final static XsXbusMessageId XMID_Log = new XsXbusMessageId("XMID_Log", movelladot_pc_sdkJNI.XMID_Log_get());
  public final static XsXbusMessageId XMID_Reserved = new XsXbusMessageId("XMID_Reserved", movelladot_pc_sdkJNI.XMID_Reserved_get());
  public final static XsXbusMessageId XMID_SetInternalOptions = new XsXbusMessageId("XMID_SetInternalOptions", movelladot_pc_sdkJNI.XMID_SetInternalOptions_get());
  public final static XsXbusMessageId XMID_SetInternalOptionsAck = new XsXbusMessageId("XMID_SetInternalOptionsAck", movelladot_pc_sdkJNI.XMID_SetInternalOptionsAck_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsXbusMessageId swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsXbusMessageId.class + " with value " + swigValue);
  }

  private XsXbusMessageId(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsXbusMessageId(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsXbusMessageId(String swigName, XsXbusMessageId swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsXbusMessageId[] swigValues = { XMID_InvalidMessage, XMID_ReqDid, XMID_DeviceId, XMID_Initbus, XMID_InitBusResults, XMID_ReqPeriod, XMID_ReqPeriodAck, XMID_SetPeriod, XMID_SetPeriodAck, XMID_SetBid, XMID_SetBidAck, XMID_AutoStart, XMID_AutoStartAck, XMID_BusPower, XMID_BusPowerAck, XMID_ReqDataLength, XMID_DataLength, XMID_ReqConfiguration, XMID_Configuration, XMID_RestoreFactoryDef, XMID_RestoreFactoryDefAck, XMID_GotoMeasurement, XMID_GotoMeasurementAck, XMID_ReqFirmwareRevision, XMID_FirmwareRevision, XMID_ReqUniqueId, XMID_UniqueId, XMID_ReqBodypackMode, XMID_ReqBodypackAck, XMID_SetBodypackMode, XMID_SetBodypackModeAck, XMID_ReqBaudrate, XMID_ReqBaudrateAck, XMID_SetBaudrate, XMID_SetBaudrateAck, XMID_ReqProductVariant, XMID_ProductVariant, XMID_ReqProductCode, XMID_ProductCode, XMID_ReqHardwareVersion, XMID_HardwareVersion, XMID_ReqProcessingFlags, XMID_ReqProcessingFlagsAck, XMID_SetProcessingFlags, XMID_SetProcessingFlagsAck, XMID_SetNoRotation, XMID_SetNoRotationAck, XMID_RunSelfTest, XMID_SelfTestResults, XMID_ReqInputTrigger, XMID_ReqInputTriggerAck, XMID_SetInputTrigger, XMID_SetInputTriggerAck, XMID_ReqOutputTrigger, XMID_ReqOutputTriggerAck, XMID_SetOutputTrigger, XMID_SetOutputTriggerAck, XMID_SetSyncStationMode, XMID_SetSyncStationModeAck, XMID_ReqSyncStationMode, XMID_ReqSyncStationModeAck, XMID_SetSyncConfiguration, XMID_SetSyncConfigurationAck, XMID_ReqSyncConfiguration, XMID_SyncConfiguration, XMID_DriverDisconnect, XMID_DriverDisconnectAck, XMID_GotoConfig, XMID_GotoConfigAck, XMID_MtData, XMID_BusData, XMID_PrepareData, XMID_ReqData, XMID_ReqDataAck, XMID_MtData2, XMID_MtData2Ack, XMID_RequestControl, XMID_RequestControlAck, XMID_SetDataPort, XMID_SetDataPortAck, XMID_ReqRetransmission, XMID_ReqRetransmissionAck, XMID_Wakeup, XMID_WakeupAck, XMID_Reset, XMID_ResetAck, XMID_Error, XMID_Warning, XMID_XmPowerOff, XMID_MasterIndication, XMID_XsbData, XMID_ReqOptionFlags, XMID_ReqOptionFlagsAck, XMID_SetOptionFlags, XMID_SetOptionFlagsAck, XMID_ReqStealthMode, XMID_StealthMode, XMID_SetStealthMode, XMID_SetStealthModeAck, XMID_UserInterface, XMID_UserInterfaceAck, XMID_EndOfRecording, XMID_EndOfRecordingAck, XMID_GotoTransparentMode, XMID_GotoTransparentModeAck, XMID_ReqDeviceCapabilities, XMID_DeviceCapabilities, XMID_DiscardRetransmissions, XMID_DiscardRetransmissionsAck, XMID_RunFactoryTest, XMID_FactoryTestResults, XMID_FactoryTestConnect, XMID_FactoryTestConnectAck, XMID_SetDataOutputDelay, XMID_SetDataOutputDelayAck, XMID_SetBodypackConfigFile, XMID_SetBodypackConfigFileAck, XMID_ReqObrStatus, XMID_ObrStatus, XMID_SetUtcTime, XMID_ReqUtcTime, XMID_SetUtcTimeAck, XMID_UtcTime, XMID_FactoryTestSensorTiming, XMID_FactoryTestSensorTimingResults, XMID_ReqAvailableFilterProfiles, XMID_AvailableFilterProfiles, XMID_ReqFilterProfile, XMID_ReqFilterProfileAck, XMID_SetFilterProfile, XMID_SetFilterProfileAck, XMID_ReqGravityMagnitude, XMID_ReqGravityMagnitudeAck, XMID_SetGravityMagnitude, XMID_SetGravityMagnitudeAck, XMID_ReqGnssLeverArm, XMID_ReqGnssLeverArmAck, XMID_SetGnssLeverArm, XMID_SetGnssLeverArmAck, XMID_ReqMagneticField, XMID_ReqMagneticFieldAck, XMID_SetMagneticField, XMID_SetMagneticFieldAck, XMID_ReqReplayMode, XMID_ReqReplayModeAck, XMID_SetReplayMode, XMID_SetReplayModeAck, XMID_ReqLatLonAlt, XMID_ReqLatLonAltAck, XMID_SetLatLonAlt, XMID_SetLatLonAltAck, XMID_KeepAlive, XMID_KeepAliveAck, XMID_CloseConnection, XMID_CloseConnectionAck, XMID_IccCommand, XMID_IccCommandAck, XMID_ReqGnssPlatform, XMID_ReqGnssPlatformAck, XMID_SetGnssPlatform, XMID_SetGnssPlatformAck, XMID_ReqConnectionSettings, XMID_ReqConnectionSettingsAck, XMID_SetConnectionSettings, XMID_SetConnectionSettingsAck, XMID_BodyPackBundle, XMID_BodyPackBundleAck, XMID_ReqStationOptions, XMID_ReqStationOptionsAck, XMID_ReqErrorReport, XMID_ErrorReport, XMID_ReqXmErrorMode, XMID_ReqXmErrorModeAck, XMID_SetXmErrorMode, XMID_SetXmErrorModeAck, XMID_ReqBufferSize, XMID_ReqBufferSizeAck, XMID_SetBufferSize, XMID_SetBufferSizeAck, XMID_ReqHeading, XMID_ReqHeadingAck, XMID_SetHeading, XMID_SetHeadingAck, XMID_ReqLocationId, XMID_ReqLocationIdAck, XMID_SetLocationId, XMID_SetLocationIdAck, XMID_ReqExtOutputMode, XMID_ReqExtOutputModeAck, XMID_SetExtOutputMode, XMID_SetExtOutputModeAck, XMID_ReqBatteryLevel, XMID_Batterylevel, XMID_ReqInitTrackMode, XMID_ReqInitTrackModeAck, XMID_SetInitTrackMode, XMID_SetInitTrackModeAck, XMID_ReqMasterSettings, XMID_MasterSettings, XMID_StoreFilterState, XMID_StoreFilterStateAck, XMID_ReqPortConfig, XMID_SetPortConfig, XMID_PortConfig, XMID_SetPortConfigAck, XMID_ReqStringOutputType, XMID_ReqStringOutputTypeAck, XMID_SetStringOutputType, XMID_SetStringOutputTypeAck, XMID_ReqStringOutputConfig, XMID_ReqStringOutputConfigAck, XMID_SetStringOutputConfig, XMID_SetStringOutputConfigAck, XMID_ReqEmts, XMID_EmtsData, XMID_UpdateFilterProfile, XMID_UpdateFilterProfileAck, XMID_RestoreEmts, XMID_RestoreEmtsAck, XMID_StoreEmts, XMID_StoreEmtsAck, XMID_UnlockMaintenanceMode, XMID_UnlockMaintenanceModeAck, XMID_ClockSyncCommand, XMID_ClockSyncCommandAck, XMID_ReqActiveClockCorrection, XMID_ActiveClockCorrection, XMID_StoreActiveClockCorrection, XMID_StoreActiveClockCorrectionAck, XMID_ReqFilterSettings, XMID_ReqFilterSettingsAck, XMID_SetFilterSettings, XMID_SetFilterSettingsAck, XMID_ReqAmd, XMID_ReqAmdAck, XMID_SetAmd, XMID_SetAmdAck, XMID_ResetOrientation, XMID_ResetOrientationAck, XMID_ReqGnssStatus, XMID_GnssStatus, XMID_AdjustUtcTime, XMID_AdjustUtcTimeAck, XMID_ReqAssemblyId, XMID_SetAssemblyId, XMID_AssemblyId, XMID_SetAssemblyIdAck, XMID_ReqGnssReceiverSettings, XMID_ReqGnssReceiverSettingsAck, XMID_SetGnssReceiverSettings, XMID_SetGnssReceiverSettingsAck, XMID_ReqAccessControlList, XMID_AccessControlList, XMID_SetAccessControlList, XMID_SetAccessControlListAck, XMID_ScanChannels, XMID_ScanChannelsAck, XMID_EnableMaster, XMID_EnableMasterAck, XMID_DisableMaster, XMID_DisableMasterAck, XMID_ReqRadioChannel, XMID_ReqRadioChannelAck, XMID_SetClientPriority, XMID_SetClientPriorityAck, XMID_ReqClientPriority, XMID_ReqClientPriorityAck, XMID_SetWirelessConfig, XMID_SetWirelessConfigAck, XMID_ReqWirelessConfig, XMID_ReqWirelessConfigAck, XMID_UpdateBias, XMID_UpdateBiasAck, XMID_ToggleIoPins, XMID_ToggleIoPinsAck, XMID_GotoOperational, XMID_GotoOperationalAck, XMID_SetTransportMode, XMID_SetTransportModeAck, XMID_ReqTransportMode, XMID_ReqTransportModeAck, XMID_AcceptMtw, XMID_AcceptMtwAck, XMID_RejectMtw, XMID_RejectMtwAck, XMID_InfoRequest, XMID_InfoRequestAck, XMID_ReqFrameRates, XMID_ReqFrameRatesAck, XMID_StartRecording, XMID_StartRecordingAck, XMID_StopRecording, XMID_StopRecordingAck, XMID_ReqOutputConfiguration, XMID_ReqOutputConfigurationAck, XMID_SetOutputConfiguration, XMID_SetOutputConfigurationAck, XMID_ReqOutputMode, XMID_ReqOutputModeAck, XMID_SetOutputMode, XMID_SetOutputModeAck, XMID_ReqOutputSettings, XMID_ReqOutputSettingsAck, XMID_SetOutputSettings, XMID_SetOutputSettingsAck, XMID_ReqOutputSkipFactor, XMID_ReqOutputSkipFactorAck, XMID_SetOutputSkipFactor, XMID_SetOutputSkipFactorAck, XMID_SetInitialHeading, XMID_SetInitialHeadingAck, XMID_ReqErrorMode, XMID_ReqErrorModeAck, XMID_SetErrorMode, XMID_SetErrorModeAck, XMID_ReqTransmitDelay, XMID_ReqTransmitDelayAck, XMID_SetTransmitDelay, XMID_SetTransmitDelayAck, XMID_SetMfmResults, XMID_SetMfmResultsAck, XMID_ReqObjectAlignment, XMID_ReqObjectAlignmentAck, XMID_SetObjectAlignment, XMID_SetObjectAlignmentAck, XMID_ForwardGnssData, XMID_ForwardGnssDataAck, XMID_ReqCanConfig, XMID_SetCanConfig, XMID_CanConfig, XMID_SetCanConfigAck, XMID_ReqCanOutputConfig, XMID_SetCanOutputConfig, XMID_CanOutputConfig, XMID_SetCanOutputConfigAck, XMID_ReqAlignmentRotation, XMID_ReqAlignmentRotationAck, XMID_SetAlignmentRotation, XMID_SetAlignmentRotationAck, XMID_ExtendedMessageID, XMID_SetDeviceIdContext, XMID_SetDeviceIdContextAck, XMID_SetLogLevel, XMID_SetLogLevelAck, XMID_Log, XMID_Reserved, XMID_SetInternalOptions, XMID_SetInternalOptionsAck };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

