
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsCalibratedData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsCalibratedData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsCalibratedData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsCalibratedData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsCalibratedData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsVector3 m_acc {
    set {
      movelladot_pc_sdkPINVOKE.XsCalibratedData_m_acc_set(swigCPtr, XsVector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsCalibratedData_m_acc_get(swigCPtr);
      XsVector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsVector3(cPtr, false);
      return ret;
    } 
  }

  public XsVector3 m_gyr {
    set {
      movelladot_pc_sdkPINVOKE.XsCalibratedData_m_gyr_set(swigCPtr, XsVector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsCalibratedData_m_gyr_get(swigCPtr);
      XsVector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsVector3(cPtr, false);
      return ret;
    } 
  }

  public XsVector3 m_mag {
    set {
      movelladot_pc_sdkPINVOKE.XsCalibratedData_m_mag_set(swigCPtr, XsVector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsCalibratedData_m_mag_get(swigCPtr);
      XsVector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsVector3(cPtr, false);
      return ret;
    } 
  }

  public XsCalibratedData() : this(movelladot_pc_sdkPINVOKE.new_XsCalibratedData__SWIG_0(), true) {
  }

  public XsCalibratedData(XsCalibratedData other) : this(movelladot_pc_sdkPINVOKE.new_XsCalibratedData__SWIG_1(XsCalibratedData.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
