
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsMatrix : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsMatrix(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsMatrix obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsMatrix() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsMatrix(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsMatrix(uint rows, uint cols, uint strde, SWIGTYPE_p_double dat) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_0(rows, cols, strde, SWIGTYPE_p_double.getCPtr(dat)), true) {
  }

  public XsMatrix(uint rows, uint cols, uint strde) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_1(rows, cols, strde), true) {
  }

  public XsMatrix(uint rows, uint cols) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_2(rows, cols), true) {
  }

  public XsMatrix(uint rows) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_3(rows), true) {
  }

  public XsMatrix() : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_4(), true) {
  }

  public XsMatrix(XsMatrix other) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_5(XsMatrix.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsMatrix(SWIGTYPE_p_double ref_, uint rows, uint cols, uint stride, XsDataFlags flags) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_6(SWIGTYPE_p_double.getCPtr(ref_), rows, cols, stride, (int)flags), true) {
  }

  public XsMatrix(XsMatrix other, SWIGTYPE_p_double ref_, uint rows, uint cols, uint stride, XsDataFlags flags) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_7(XsMatrix.getCPtr(other), SWIGTYPE_p_double.getCPtr(ref_), rows, cols, stride, (int)flags), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsMatrix(XsQuaternion quat) : this(movelladot_pc_sdkPINVOKE.new_XsMatrix__SWIG_8(XsQuaternion.getCPtr(quat)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSize(uint rows, uint cols, uint stride) {
    movelladot_pc_sdkPINVOKE.XsMatrix_setSize__SWIG_0(swigCPtr, rows, cols, stride);
  }

  public void setSize(uint rows, uint cols) {
    movelladot_pc_sdkPINVOKE.XsMatrix_setSize__SWIG_1(swigCPtr, rows, cols);
  }

  public bool empty() {
    bool ret = movelladot_pc_sdkPINVOKE.XsMatrix_empty(swigCPtr);
    return ret;
  }

  public void setZero() {
    movelladot_pc_sdkPINVOKE.XsMatrix_setZero(swigCPtr);
  }

  public uint offset(uint row, uint column) {
    uint ret = movelladot_pc_sdkPINVOKE.XsMatrix_offset(swigCPtr, row, column);
    return ret;
  }

  public double value(uint row, uint column) {
    double ret = movelladot_pc_sdkPINVOKE.XsMatrix_value(swigCPtr, row, column);
    return ret;
  }

  public void setValue(uint row, uint column, double value) {
    movelladot_pc_sdkPINVOKE.XsMatrix_setValue(swigCPtr, row, column, value);
  }

  public XsMatrix fromQuaternion(XsQuaternion quat) {
    XsMatrix ret = new XsMatrix(movelladot_pc_sdkPINVOKE.XsMatrix_fromQuaternion(swigCPtr, XsQuaternion.getCPtr(quat)), false);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void zero() {
    movelladot_pc_sdkPINVOKE.XsMatrix_zero(swigCPtr);
  }

  public uint rows() {
    uint ret = movelladot_pc_sdkPINVOKE.XsMatrix_rows(swigCPtr);
    return ret;
  }

  public uint cols() {
    uint ret = movelladot_pc_sdkPINVOKE.XsMatrix_cols(swigCPtr);
    return ret;
  }

  public uint stride() {
    uint ret = movelladot_pc_sdkPINVOKE.XsMatrix_stride(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double data() {
    global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsMatrix_data(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public bool isEqual(XsMatrix other, double tolerance) {
    bool ret = movelladot_pc_sdkPINVOKE.XsMatrix_isEqual(swigCPtr, XsMatrix.getCPtr(other), tolerance);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void swap(XsMatrix b) {
    movelladot_pc_sdkPINVOKE.XsMatrix_swap(swigCPtr, XsMatrix.getCPtr(b));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
