
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsSimpleVersion : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsSimpleVersion(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsSimpleVersion obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsSimpleVersion() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsSimpleVersion(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsSimpleVersion(int vmaj, int vmin, int vrev) : this(movelladot_pc_sdkPINVOKE.new_XsSimpleVersion__SWIG_0(vmaj, vmin, vrev), true) {
  }

  public XsSimpleVersion(int vmaj, int vmin) : this(movelladot_pc_sdkPINVOKE.new_XsSimpleVersion__SWIG_1(vmaj, vmin), true) {
  }

  public XsSimpleVersion(int vmaj) : this(movelladot_pc_sdkPINVOKE.new_XsSimpleVersion__SWIG_2(vmaj), true) {
  }

  public XsSimpleVersion() : this(movelladot_pc_sdkPINVOKE.new_XsSimpleVersion__SWIG_3(), true) {
  }

  public XsSimpleVersion(XsSimpleVersion other) : this(movelladot_pc_sdkPINVOKE.new_XsSimpleVersion__SWIG_4(XsSimpleVersion.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool empty() {
    bool ret = movelladot_pc_sdkPINVOKE.XsSimpleVersion_empty(swigCPtr);
    return ret;
  }

  public int major() {
    int ret = movelladot_pc_sdkPINVOKE.XsSimpleVersion_major(swigCPtr);
    return ret;
  }

  public int minor() {
    int ret = movelladot_pc_sdkPINVOKE.XsSimpleVersion_minor(swigCPtr);
    return ret;
  }

  public int revision() {
    int ret = movelladot_pc_sdkPINVOKE.XsSimpleVersion_revision(swigCPtr);
    return ret;
  }

  public static XsSimpleVersion osVersion() {
    XsSimpleVersion ret = new XsSimpleVersion(movelladot_pc_sdkPINVOKE.XsSimpleVersion_osVersion(), true);
    return ret;
  }

}

}
