
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsSyncSetting : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsSyncSetting(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsSyncSetting obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsSyncSetting() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsSyncSetting(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsSyncLine m_line {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_line_set(swigCPtr, (int)value);
    } 
    get {
      XsSyncLine ret = (XsSyncLine)movelladot_pc_sdkPINVOKE.XsSyncSetting_m_line_get(swigCPtr);
      return ret;
    } 
  }

  public XsSyncFunction m_function {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_function_set(swigCPtr, (int)value);
    } 
    get {
      XsSyncFunction ret = (XsSyncFunction)movelladot_pc_sdkPINVOKE.XsSyncSetting_m_function_get(swigCPtr);
      return ret;
    } 
  }

  public XsSyncPolarity m_polarity {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_polarity_set(swigCPtr, (int)value);
    } 
    get {
      XsSyncPolarity ret = (XsSyncPolarity)movelladot_pc_sdkPINVOKE.XsSyncSetting_m_polarity_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_pulseWidth {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_pulseWidth_set(swigCPtr, value);
    } 
    get {
      uint ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_m_pulseWidth_get(swigCPtr);
      return ret;
    } 
  }

  public int m_offset {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_offset_set(swigCPtr, value);
    } 
    get {
      int ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_m_offset_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_skipFirst {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_skipFirst_set(swigCPtr, value);
    } 
    get {
      ushort ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_m_skipFirst_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_skipFactor {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_skipFactor_set(swigCPtr, value);
    } 
    get {
      ushort ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_m_skipFactor_get(swigCPtr);
      return ret;
    } 
  }

  public ushort m_clockPeriod {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_clockPeriod_set(swigCPtr, value);
    } 
    get {
      ushort ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_m_clockPeriod_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_triggerOnce {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_triggerOnce_set(swigCPtr, value);
    } 
    get {
      byte ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_m_triggerOnce_get(swigCPtr);
      return ret;
    } 
  }

  public byte m_padding {
    set {
      movelladot_pc_sdkPINVOKE.XsSyncSetting_m_padding_set(swigCPtr, value);
    } 
    get {
      byte ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_m_padding_get(swigCPtr);
      return ret;
    } 
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function, XsSyncPolarity polarity, uint pulseWidth, int offset, ushort skipFirst, ushort skipFactor, ushort clockPeriod, byte triggerOnce) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_0((int)line, (int)function, (int)polarity, pulseWidth, offset, skipFirst, skipFactor, clockPeriod, triggerOnce), true) {
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function, XsSyncPolarity polarity, uint pulseWidth, int offset, ushort skipFirst, ushort skipFactor, ushort clockPeriod) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_1((int)line, (int)function, (int)polarity, pulseWidth, offset, skipFirst, skipFactor, clockPeriod), true) {
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function, XsSyncPolarity polarity, uint pulseWidth, int offset, ushort skipFirst, ushort skipFactor) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_2((int)line, (int)function, (int)polarity, pulseWidth, offset, skipFirst, skipFactor), true) {
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function, XsSyncPolarity polarity, uint pulseWidth, int offset, ushort skipFirst) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_3((int)line, (int)function, (int)polarity, pulseWidth, offset, skipFirst), true) {
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function, XsSyncPolarity polarity, uint pulseWidth, int offset) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_4((int)line, (int)function, (int)polarity, pulseWidth, offset), true) {
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function, XsSyncPolarity polarity, uint pulseWidth) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_5((int)line, (int)function, (int)polarity, pulseWidth), true) {
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function, XsSyncPolarity polarity) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_6((int)line, (int)function, (int)polarity), true) {
  }

  public XsSyncSetting(XsSyncLine line, XsSyncFunction function) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_7((int)line, (int)function), true) {
  }

  public XsSyncSetting(XsSyncLine line) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_8((int)line), true) {
  }

  public XsSyncSetting() : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_9(), true) {
  }

  public XsSyncSetting(XsSyncSetting other) : this(movelladot_pc_sdkPINVOKE.new_XsSyncSetting__SWIG_10(XsSyncSetting.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isInput() {
    bool ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_isInput(swigCPtr);
    return ret;
  }

  public bool isOutput() {
    bool ret = movelladot_pc_sdkPINVOKE.XsSyncSetting_isOutput(swigCPtr);
    return ret;
  }

  public void swap(XsSyncSetting other) {
    movelladot_pc_sdkPINVOKE.XsSyncSetting_swap(swigCPtr, XsSyncSetting.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
