
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsCanOutputConfigurationArrayImpl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsCanOutputConfigurationArrayImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsCanOutputConfigurationArrayImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsCanOutputConfigurationArrayImpl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsCanOutputConfigurationArrayImpl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsCanOutputConfigurationArrayImpl(uint count, XsCanOutputConfiguration src) : this(movelladot_pc_sdkPINVOKE.new_XsCanOutputConfigurationArrayImpl__SWIG_0(count, XsCanOutputConfiguration.getCPtr(src)), true) {
  }

  public XsCanOutputConfigurationArrayImpl(uint count) : this(movelladot_pc_sdkPINVOKE.new_XsCanOutputConfigurationArrayImpl__SWIG_1(count), true) {
  }

  public XsCanOutputConfigurationArrayImpl() : this(movelladot_pc_sdkPINVOKE.new_XsCanOutputConfigurationArrayImpl__SWIG_2(), true) {
  }

  public XsCanOutputConfigurationArrayImpl(XsCanOutputConfigurationArrayImpl other) : this(movelladot_pc_sdkPINVOKE.new_XsCanOutputConfigurationArrayImpl__SWIG_3(XsCanOutputConfigurationArrayImpl.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsCanOutputConfigurationArrayImpl(XsCanOutputConfiguration ref_, uint sz, XsDataFlags flags) : this(movelladot_pc_sdkPINVOKE.new_XsCanOutputConfigurationArrayImpl__SWIG_4(XsCanOutputConfiguration.getCPtr(ref_), sz, (int)flags), true) {
  }

  public void clear() {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_clear(swigCPtr);
  }

  public void reserve(uint count) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_reserve(swigCPtr, count);
  }

  public uint reserved() {
    uint ret = movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_reserved(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_XsArrayDescriptor descriptor() {
    SWIGTYPE_p_XsArrayDescriptor ret = new SWIGTYPE_p_XsArrayDescriptor(movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_descriptor(swigCPtr), false);
    return ret;
  }

  public XsCanOutputConfiguration value(uint index) {
    XsCanOutputConfiguration ret = new XsCanOutputConfiguration(movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_value(swigCPtr, index), true);
    return ret;
  }

  public XsCanOutputConfiguration first() {
    XsCanOutputConfiguration ret = new XsCanOutputConfiguration(movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_first(swigCPtr), true);
    return ret;
  }

  public XsCanOutputConfiguration last() {
    XsCanOutputConfiguration ret = new XsCanOutputConfiguration(movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_last(swigCPtr), true);
    return ret;
  }

  public XsCanOutputConfiguration at(uint index) {
    XsCanOutputConfiguration ret = new XsCanOutputConfiguration(movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_at__SWIG_0(swigCPtr, index), false);
    return ret;
  }

  public void insert(XsCanOutputConfiguration item, uint index) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_insert__SWIG_0(swigCPtr, XsCanOutputConfiguration.getCPtr(item), index);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void insert(XsCanOutputConfiguration items, uint index, uint count) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_insert__SWIG_1(swigCPtr, XsCanOutputConfiguration.getCPtr(items), index, count);
  }

  public void push_back(XsCanOutputConfiguration item) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_push_back(swigCPtr, XsCanOutputConfiguration.getCPtr(item));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_back(uint count) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_pop_back__SWIG_0(swigCPtr, count);
  }

  public void pop_back() {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_pop_back__SWIG_1(swigCPtr);
  }

  public void push_front(XsCanOutputConfiguration item) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_push_front(swigCPtr, XsCanOutputConfiguration.getCPtr(item));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void pop_front(uint count) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_pop_front__SWIG_0(swigCPtr, count);
  }

  public void pop_front() {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_pop_front__SWIG_1(swigCPtr);
  }

  public uint size() {
    uint ret = movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_size(swigCPtr);
    return ret;
  }

  public void erase(uint index, uint count) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_erase__SWIG_0(swigCPtr, index, count);
  }

  public void erase(uint index) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_erase__SWIG_1(swigCPtr, index);
  }

  public void assign(uint count, XsCanOutputConfiguration src) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_assign(swigCPtr, count, XsCanOutputConfiguration.getCPtr(src));
  }

  public void resize(uint count) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_resize(swigCPtr, count);
  }

  public void setSize(uint count) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_setSize(swigCPtr, count);
  }

  public void append(XsCanOutputConfigurationArrayImpl other) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_append(swigCPtr, XsCanOutputConfigurationArrayImpl.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool empty() {
    bool ret = movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_empty(swigCPtr);
    return ret;
  }

  public bool badAlloc() {
    bool ret = movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_badAlloc(swigCPtr);
    return ret;
  }

  public void swap(XsCanOutputConfigurationArrayImpl other) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_swap__SWIG_0(swigCPtr, XsCanOutputConfigurationArrayImpl.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(uint a, uint b) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_swap__SWIG_1(swigCPtr, a, b);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsCanOutputConfiguration needle) {
    SWIGTYPE_p_ptrdiff_t ret = new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_find(swigCPtr, XsCanOutputConfiguration.getCPtr(needle)), true);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool contains(XsCanOutputConfiguration needle) {
    bool ret = movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_contains(swigCPtr, XsCanOutputConfiguration.getCPtr(needle));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void removeDuplicates() {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_removeDuplicates(swigCPtr);
  }

  public void removeDuplicatesPredicate(SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int predicate) {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_removeDuplicatesPredicate(swigCPtr, SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int.getCPtr(predicate));
  }

  public void sort() {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_sort(swigCPtr);
  }

  public void reverse() {
    movelladot_pc_sdkPINVOKE.XsCanOutputConfigurationArrayImpl_reverse(swigCPtr);
  }

}

}
