
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsDataPacketPtrArrayImpl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsDataPacketPtrArrayImpl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsDataPacketPtrArrayImpl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsDataPacketPtrArrayImpl() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsDataPacketPtrArrayImpl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsDataPacketPtrArrayImpl(uint count, SWIGTYPE_p_p_XsDataPacket src) : this(movelladot_pc_sdkPINVOKE.new_XsDataPacketPtrArrayImpl__SWIG_0(count, SWIGTYPE_p_p_XsDataPacket.getCPtr(src)), true) {
  }

  public XsDataPacketPtrArrayImpl(uint count) : this(movelladot_pc_sdkPINVOKE.new_XsDataPacketPtrArrayImpl__SWIG_1(count), true) {
  }

  public XsDataPacketPtrArrayImpl() : this(movelladot_pc_sdkPINVOKE.new_XsDataPacketPtrArrayImpl__SWIG_2(), true) {
  }

  public XsDataPacketPtrArrayImpl(SWIGTYPE_p_XsArrayImplT_XsDataPacketPtr_g_xsDataPacketPtrArrayDescriptor_XsDataPacketPtrArray_t__ArrayImpl other) : this(movelladot_pc_sdkPINVOKE.new_XsDataPacketPtrArrayImpl__SWIG_3(SWIGTYPE_p_XsArrayImplT_XsDataPacketPtr_g_xsDataPacketPtrArrayDescriptor_XsDataPacketPtrArray_t__ArrayImpl.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsDataPacketPtrArrayImpl(SWIGTYPE_p_p_XsDataPacket ref_, uint sz, XsDataFlags flags) : this(movelladot_pc_sdkPINVOKE.new_XsDataPacketPtrArrayImpl__SWIG_4(SWIGTYPE_p_p_XsDataPacket.getCPtr(ref_), sz, (int)flags), true) {
  }

  public void clear() {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_clear(swigCPtr);
  }

  public void reserve(uint count) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_reserve(swigCPtr, count);
  }

  public uint reserved() {
    uint ret = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_reserved(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_XsArrayDescriptor descriptor() {
    SWIGTYPE_p_XsArrayDescriptor ret = new SWIGTYPE_p_XsArrayDescriptor(movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_descriptor(swigCPtr), false);
    return ret;
  }

  public XsDataPacket value(uint index) {
    global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_value(swigCPtr, index);
    XsDataPacket ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDataPacket(cPtr, false);
    return ret;
  }

  public XsDataPacket first() {
    global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_first(swigCPtr);
    XsDataPacket ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDataPacket(cPtr, false);
    return ret;
  }

  public XsDataPacket last() {
    global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_last(swigCPtr);
    XsDataPacket ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDataPacket(cPtr, false);
    return ret;
  }

  public XsDataPacket at(uint index) {
    global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_at__SWIG_0(swigCPtr, index);
    XsDataPacket ret = (cPtr == global::System.IntPtr.Zero) ? null : new XsDataPacket(cPtr, false);
    return ret;
  }

  public void insert(XsDataPacket item, uint index) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_insert__SWIG_0(swigCPtr, XsDataPacket.getCPtr(item), index);
  }

  public void insert(SWIGTYPE_p_p_XsDataPacket items, uint index, uint count) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_insert__SWIG_1(swigCPtr, SWIGTYPE_p_p_XsDataPacket.getCPtr(items), index, count);
  }

  public void push_back(XsDataPacket item) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_push_back(swigCPtr, XsDataPacket.getCPtr(item));
  }

  public void pop_back(uint count) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_pop_back__SWIG_0(swigCPtr, count);
  }

  public void pop_back() {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_pop_back__SWIG_1(swigCPtr);
  }

  public void push_front(XsDataPacket item) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_push_front(swigCPtr, XsDataPacket.getCPtr(item));
  }

  public void pop_front(uint count) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_pop_front__SWIG_0(swigCPtr, count);
  }

  public void pop_front() {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_pop_front__SWIG_1(swigCPtr);
  }

  public uint size() {
    uint ret = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_size(swigCPtr);
    return ret;
  }

  public void erase(uint index, uint count) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_erase__SWIG_0(swigCPtr, index, count);
  }

  public void erase(uint index) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_erase__SWIG_1(swigCPtr, index);
  }

  public void assign(uint count, SWIGTYPE_p_p_XsDataPacket src) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_assign(swigCPtr, count, SWIGTYPE_p_p_XsDataPacket.getCPtr(src));
  }

  public void resize(uint count) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_resize(swigCPtr, count);
  }

  public void setSize(uint count) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_setSize(swigCPtr, count);
  }

  public void append(SWIGTYPE_p_XsArrayImplT_XsDataPacketPtr_g_xsDataPacketPtrArrayDescriptor_XsDataPacketPtrArray_t__ArrayImpl other) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_append(swigCPtr, SWIGTYPE_p_XsArrayImplT_XsDataPacketPtr_g_xsDataPacketPtrArrayDescriptor_XsDataPacketPtrArray_t__ArrayImpl.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool empty() {
    bool ret = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_empty(swigCPtr);
    return ret;
  }

  public bool badAlloc() {
    bool ret = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_badAlloc(swigCPtr);
    return ret;
  }

  public void swap(SWIGTYPE_p_XsArrayImplT_XsDataPacketPtr_g_xsDataPacketPtrArrayDescriptor_XsDataPacketPtrArray_t__ArrayImpl other) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_swap__SWIG_0(swigCPtr, SWIGTYPE_p_XsArrayImplT_XsDataPacketPtr_g_xsDataPacketPtrArrayDescriptor_XsDataPacketPtrArray_t__ArrayImpl.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(uint a, uint b) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_swap__SWIG_1(swigCPtr, a, b);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsDataPacket needle) {
    SWIGTYPE_p_ptrdiff_t ret = new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_find(swigCPtr, XsDataPacket.getCPtr(needle)), true);
    return ret;
  }

  public bool contains(XsDataPacket needle) {
    bool ret = movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_contains(swigCPtr, XsDataPacket.getCPtr(needle));
    return ret;
  }

  public void removeDuplicates() {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_removeDuplicates(swigCPtr);
  }

  public void removeDuplicatesPredicate(SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int predicate) {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_removeDuplicatesPredicate(swigCPtr, SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int.getCPtr(predicate));
  }

  public void sort() {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_sort(swigCPtr);
  }

  public void reverse() {
    movelladot_pc_sdkPINVOKE.XsDataPacketPtrArrayImpl_reverse(swigCPtr);
  }

}

}
