
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsString : XsStringImpl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal XsString(global::System.IntPtr cPtr, bool cMemoryOwn) : base(movelladot_pc_sdkPINVOKE.XsString_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsString obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsString(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public XsString(uint sz, string src) : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_0(sz, src), true) {
  }

  public XsString(uint sz) : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_1(sz), true) {
  }

  public XsString() : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_2(), true) {
  }

  public XsString(XsString other) : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_3(XsString.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsString(ref string ref_, uint sz, XsDataFlags flags) : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_4(ref ref_, sz, (int)flags), true) {
  }

  public XsString(string src) : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_5(src), true) {
  }

  public XsString(SWIGTYPE_p_wchar_t src) : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_6(SWIGTYPE_p_wchar_t.getCPtr(src)), true) {
  }

  public XsString(SWIGTYPE_p_std__wstring src) : this(movelladot_pc_sdkPINVOKE.new_XsString__SWIG_8(SWIGTYPE_p_std__wstring.getCPtr(src)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public string c_str() {
    string ret = movelladot_pc_sdkPINVOKE.XsString_c_str__SWIG_0(swigCPtr);
    return ret;
  }

  public string toString() {
    string ret = movelladot_pc_sdkPINVOKE.XsString_toString(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__wstring toStdWString() {
    SWIGTYPE_p_std__wstring ret = new SWIGTYPE_p_std__wstring(movelladot_pc_sdkPINVOKE.XsString_toStdWString(swigCPtr), true);
    return ret;
  }

  public new bool empty() {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_empty(swigCPtr);
    return ret;
  }

  public void append(XsString other) {
    movelladot_pc_sdkPINVOKE.XsString_append__SWIG_0(swigCPtr, XsString.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void append(string other) {
    movelladot_pc_sdkPINVOKE.XsString_append__SWIG_1(swigCPtr, other);
  }

  public void append(SWIGTYPE_p_wchar_t other) {
    movelladot_pc_sdkPINVOKE.XsString_append__SWIG_2(swigCPtr, SWIGTYPE_p_wchar_t.getCPtr(other));
  }

  public uint utf8Len() {
    uint ret = movelladot_pc_sdkPINVOKE.XsString_utf8Len(swigCPtr);
    return ret;
  }

  public bool endsWith(XsString other, bool caseSensitive) {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_endsWith__SWIG_0(swigCPtr, XsString.getCPtr(other), caseSensitive);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool endsWith(XsString other) {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_endsWith__SWIG_1(swigCPtr, XsString.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool startsWith(XsString other, bool caseSensitive) {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_startsWith__SWIG_0(swigCPtr, XsString.getCPtr(other), caseSensitive);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool startsWith(XsString other) {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_startsWith__SWIG_1(swigCPtr, XsString.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool contains(XsString other, bool caseSensitive, SWIGTYPE_p_size_t offset) {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_contains__SWIG_0(swigCPtr, XsString.getCPtr(other), caseSensitive, SWIGTYPE_p_size_t.getCPtr(offset));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool contains(XsString other, bool caseSensitive) {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_contains__SWIG_1(swigCPtr, XsString.getCPtr(other), caseSensitive);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool contains(XsString other) {
    bool ret = movelladot_pc_sdkPINVOKE.XsString_contains__SWIG_2(swigCPtr, XsString.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_wchar_t utf8At(uint index) {
    SWIGTYPE_p_wchar_t ret = new SWIGTYPE_p_wchar_t(movelladot_pc_sdkPINVOKE.XsString_utf8At(swigCPtr, index), true);
    return ret;
  }

  public new void sort() {
    movelladot_pc_sdkPINVOKE.XsString_sort(swigCPtr);
  }

  public new void reverse() {
    movelladot_pc_sdkPINVOKE.XsString_reverse(swigCPtr);
  }

  public SWIGTYPE_p_ptrdiff_t findSubStr(XsString needle) {
    SWIGTYPE_p_ptrdiff_t ret = new SWIGTYPE_p_ptrdiff_t(movelladot_pc_sdkPINVOKE.XsString_findSubStr(swigCPtr, XsString.getCPtr(needle)), true);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public XsString mid(uint start, uint count) {
    XsString ret = new XsString(movelladot_pc_sdkPINVOKE.XsString_mid(swigCPtr, start, count), true);
    return ret;
  }

  public void replaceAll(XsString src, XsString dst) {
    movelladot_pc_sdkPINVOKE.XsString_replaceAll(swigCPtr, XsString.getCPtr(src), XsString.getCPtr(dst));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsString replacedAll(XsString src, XsString dst) {
    XsString ret = new XsString(movelladot_pc_sdkPINVOKE.XsString_replacedAll(swigCPtr, XsString.getCPtr(src), XsString.getCPtr(dst)), true);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void trim() {
    movelladot_pc_sdkPINVOKE.XsString_trim(swigCPtr);
  }

  public XsString trimmed() {
    XsString ret = new XsString(movelladot_pc_sdkPINVOKE.XsString_trimmed(swigCPtr), true);
    return ret;
  }

  public new char last() {
    char ret = movelladot_pc_sdkPINVOKE.XsString_last(swigCPtr);
    return ret;
  }

  public void toLower() {
    movelladot_pc_sdkPINVOKE.XsString_toLower(swigCPtr);
  }

  public void toUpper() {
    movelladot_pc_sdkPINVOKE.XsString_toUpper(swigCPtr);
  }

  public XsString lowered() {
    XsString ret = new XsString(movelladot_pc_sdkPINVOKE.XsString_lowered(swigCPtr), true);
    return ret;
  }

  public XsString uppered() {
    XsString ret = new XsString(movelladot_pc_sdkPINVOKE.XsString_uppered(swigCPtr), true);
    return ret;
  }

}

}
