
//  WARNING: COPYRIGHT (C) 2023 MOVELLA TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
//  THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
//  FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
//  TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
//  LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
//  INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
//  DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
//  IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
//  USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
//  XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
//  OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
//  COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
//  

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MovellaDotPcSdk {

public class XsVector : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XsVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XsVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XsVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          movelladot_pc_sdkPINVOKE.delete_XsVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public XsVector(uint sz, SWIGTYPE_p_double src) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_0(sz, SWIGTYPE_p_double.getCPtr(src)), true) {
  }

  public XsVector(uint sz) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_1(sz), true) {
  }

  public XsVector() : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_2(), true) {
  }

  public XsVector(XsVector other) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_3(XsVector.getCPtr(other)), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsVector(SWIGTYPE_p_double ref_, uint sz, XsDataFlags flags_) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_4(SWIGTYPE_p_double.getCPtr(ref_), sz, (int)flags_), true) {
  }

  public XsVector(SWIGTYPE_p_double ref_, uint sz) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_5(SWIGTYPE_p_double.getCPtr(ref_), sz), true) {
  }

  public XsVector(XsVector other, SWIGTYPE_p_double ref_, uint sz, XsDataFlags flags_) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_6(XsVector.getCPtr(other), SWIGTYPE_p_double.getCPtr(ref_), sz, (int)flags_), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsVector(XsVector other, SWIGTYPE_p_double ref_, uint sz) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_7(XsVector.getCPtr(other), SWIGTYPE_p_double.getCPtr(ref_), sz), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public XsVector(XsQuaternion quat, double deltaT) : this(movelladot_pc_sdkPINVOKE.new_XsVector__SWIG_8(XsQuaternion.getCPtr(quat), deltaT), true) {
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void assign(uint sz, SWIGTYPE_p_double src) {
    movelladot_pc_sdkPINVOKE.XsVector_assign(swigCPtr, sz, SWIGTYPE_p_double.getCPtr(src));
  }

  public void setSize(uint sz) {
    movelladot_pc_sdkPINVOKE.XsVector_setSize(swigCPtr, sz);
  }

  public uint size() {
    uint ret = movelladot_pc_sdkPINVOKE.XsVector_size(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double data() {
    global::System.IntPtr cPtr = movelladot_pc_sdkPINVOKE.XsVector_data(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_double at(uint index) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(movelladot_pc_sdkPINVOKE.XsVector_at__SWIG_0(swigCPtr, index), false);
    return ret;
  }

  public double value(uint index) {
    double ret = movelladot_pc_sdkPINVOKE.XsVector_value(swigCPtr, index);
    return ret;
  }

  public void setValue(uint index, double val) {
    movelladot_pc_sdkPINVOKE.XsVector_setValue(swigCPtr, index, val);
  }

  public double dotProduct(XsVector v) {
    double ret = movelladot_pc_sdkPINVOKE.XsVector_dotProduct(swigCPtr, XsVector.getCPtr(v));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cartesianLength() {
    double ret = movelladot_pc_sdkPINVOKE.XsVector_cartesianLength(swigCPtr);
    return ret;
  }

  public void normalize() {
    movelladot_pc_sdkPINVOKE.XsVector_normalize(swigCPtr);
  }

  public void setZero() {
    movelladot_pc_sdkPINVOKE.XsVector_setZero(swigCPtr);
  }

  public bool empty() {
    bool ret = movelladot_pc_sdkPINVOKE.XsVector_empty(swigCPtr);
    return ret;
  }

  public XsVector angularVelocityFromQuaternion(XsQuaternion quat, double deltaT) {
    XsVector ret = new XsVector(movelladot_pc_sdkPINVOKE.XsVector_angularVelocityFromQuaternion(swigCPtr, XsQuaternion.getCPtr(quat), deltaT), false);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isEqual(XsVector other, double epsilon) {
    bool ret = movelladot_pc_sdkPINVOKE.XsVector_isEqual(swigCPtr, XsVector.getCPtr(other), epsilon);
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_double_t toVector() {
    SWIGTYPE_p_std__vectorT_double_t ret = new SWIGTYPE_p_std__vectorT_double_t(movelladot_pc_sdkPINVOKE.XsVector_toVector(swigCPtr), true);
    return ret;
  }

  public void zero() {
    movelladot_pc_sdkPINVOKE.XsVector_zero(swigCPtr);
  }

  public void fill(double val) {
    movelladot_pc_sdkPINVOKE.XsVector_fill(swigCPtr, val);
  }

  public void swap(XsVector b) {
    movelladot_pc_sdkPINVOKE.XsVector_swap(swigCPtr, XsVector.getCPtr(b));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void append(XsVector other) {
    movelladot_pc_sdkPINVOKE.XsVector_append(swigCPtr, XsVector.getCPtr(other));
    if (movelladot_pc_sdkPINVOKE.SWIGPendingException.Pending) throw movelladot_pc_sdkPINVOKE.SWIGPendingException.Retrieve();
  }

  public void clear() {
    movelladot_pc_sdkPINVOKE.XsVector_clear(swigCPtr);
  }

  public void reverse() {
    movelladot_pc_sdkPINVOKE.XsVector_reverse(swigCPtr);
  }

}

}
